---
sidebar: sidebar 
permalink: trident-docker/known-issues-docker.html 
keywords: known issues, trident, trident for docker, docker 
summary: Informationen zu bekannten Problemen bei der Verwendung von Trident mit Docker 
---
= Bekannte Probleme und Einschränkungen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informationen zu bekannten Problemen und Einschränkungen bei der Verwendung von Trident mit Docker



== Das Upgrade des Trident Docker Volume Plug-ins auf 20.10 und höher aus älteren Versionen führt zu einem Upgrade-Fehler, ohne dass solche Datei- oder Verzeichnisfehler auftreten.

.Behelfslösung
. Deaktivieren Sie das Plugin.
+
[source, console]
----
docker plugin disable -f netapp:latest
----
. Entfernen Sie das Plug-in.
+
[source, console]
----
docker plugin rm -f netapp:latest
----
. Installieren Sie das Plug-in neu, indem Sie das Zusatzmodul bereitstellen `config` Parameter.
+
[source, console]
----
docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json
----




== Volume-Namen müssen mindestens 2 Zeichen lang sein.


NOTE: Dies ist eine Docker-Client-Einschränkung. Der Client interpretiert einen einzelnen Zeichennamen als Windows-Pfad. https://github.com/moby/moby/issues/25773["Siehe Bug 25773"^].



== Docker Swarm verfügt über bestimmte Verhaltensweisen, die verhindern, dass Trident diese bei jeder Storage- und Treiberkombination unterstützen kann.

* Docker Swarm verwendet derzeit Volume-Namen anstelle der Volume-ID als eindeutige Volume-Kennung.
* Volume-Anforderungen werden gleichzeitig an jeden Node in einem Swarm-Cluster gesendet.
* Volume-Plug-ins (einschließlich Trident) müssen unabhängig auf jedem Node in einem Swarm-Cluster ausgeführt werden. Aufgrund der Funktionsweise von ONTAP und der Funktionsweise der `ontap-nas` und `ontap-san`-Treiber sind sie die einzigen, die innerhalb dieser Einschränkungen arbeiten können.


Der Rest der Fahrer unterliegt Problemen wie Rennbedingungen, die dazu führen können, dass eine große Anzahl von Volumes für eine einzelne Anfrage ohne einen eindeutigen „Gewinner“ erstellt wird; zum Beispiel hat Element eine Funktion, die es Volumes ermöglicht, den gleichen Namen, aber unterschiedliche IDs zu haben.

NetApp hat das Docker-Team Feedback gegeben, lässt aber keinen Anzeichen für einen zukünftigen Regressanspruch haben.



== Wenn eine FlexGroup bereitgestellt wird, stellt ONTAP keine zweite FlexGroup bereit, wenn die zweite FlexGroup über einen oder mehrere Aggregate verfügt, die mit der bereitgestellten FlexGroup gemeinsam genutzt werden.
