---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, Trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, fc, nvme 
summary: Sie müssen die erforderlichen Protokollvoraussetzungen auf Ihrem Host installieren und konfigurieren, bevor Sie Trident bereitstellen können. 
---
= Voraussetzungen für die Bereitstellung
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die erforderlichen Protokollvoraussetzungen auf Ihrem Host installieren und konfigurieren, bevor Sie Trident bereitstellen können.



== Überprüfen Sie die Anforderungen

* Stellen Sie sicher, dass Ihre Implementierung alle Anforderungen erfüllt link:../trident-get-started/requirements.html["Anforderungen"].
* Vergewissern Sie sich, dass eine unterstützte Version von Docker installiert ist. Wenn Ihre Docker Version veraltet ist, https://docs.docker.com/engine/install/["Installieren oder aktualisieren Sie sie"^].
+
[source, console]
----
docker --version
----
* Stellen Sie sicher, dass die Protokollvoraussetzungen auf Ihrem Host installiert und konfiguriert sind.




=== NFS Tools

Installieren Sie die NFS-Tools unter Verwendung der Befehle für Ihr Betriebssystem.

[role="tabbed-block"]
====
.RHEL 8 ODER HÖHER
--
[source, console]
----
sudo yum install -y nfs-utils
----
--
.Ubuntu
--
[source, console]
----
sudo apt-get install -y nfs-common
----
--
====

WARNING: Starten Sie die Worker-Nodes nach der Installation der NFS-Tools neu, um einen Fehler beim Anschließen von Volumes an Container zu vermeiden.



=== ISCSI-Tools

Installieren Sie die iSCSI-Tools mit den Befehlen für Ihr Betriebssystem.

[role="tabbed-block"]
====
.RHEL 8 ODER HÖHER
--
. Installieren Sie die folgenden Systempakete:
+
[source, console]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. Überprüfen Sie, ob die Version von iscsi-Initiator-utils 6.2.0.874-2.el7 oder höher ist:
+
[source, console]
----
rpm -q iscsi-initiator-utils
----
. Scannen auf manuell einstellen:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Multipathing aktivieren:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: Unbedingt `etc/multipath.conf` Enthält `find_multipaths no` Unter `defaults`.

. Stellen Sie das sicher `iscsid` Und `multipathd` Laufen:
+
[source, console]
----
sudo systemctl enable --now iscsid multipathd
----
. Aktivieren und starten `iscsi`:
+
[source, console]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. Installieren Sie die folgenden Systempakete:
+
[source, console]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. Stellen Sie sicher, dass Open-iscsi-Version 2.0.874-5ubuntu2.10 oder höher (für bionic) oder 2.0.874-7.1ubuntu6.1 oder höher (für Brennweite) ist:
+
[source, console]
----
dpkg -l open-iscsi
----
. Scannen auf manuell einstellen:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Multipathing aktivieren:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: Unbedingt `etc/multipath.conf` Enthält `find_multipaths no` Unter `defaults`.

. Stellen Sie das sicher `open-iscsi` Und `multipath-tools` Sind aktiviert und läuft:
+
[source, console]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----


--
====


== NVMe-Tools

Installieren Sie die NVMe Tools mithilfe der Befehle für Ihr Betriebssystem.

[NOTE]
====
* Für NVMe ist RHEL 9 oder höher erforderlich.
* Wenn die Kernel-Version Ihres Kubernetes Node zu alt ist oder das NVMe-Paket für Ihre Kernel-Version nicht verfügbar ist, müssen Sie möglicherweise die Kernel-Version Ihres Node mit dem NVMe-Paket auf eine aktualisieren.


====
[role="tabbed-block"]
====
.RHEL 9
--
[source, console]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.Ubuntu
--
[source, console]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
====


== FC Tools

Installieren Sie die FC-Tools unter Verwendung der Befehle für Ihr Betriebssystem.

* Geben Sie bei der Verwendung von Worker-Nodes, die RHEL/Red hat Enterprise Linux CoreOS (RHCOS) mit FC PVs ausführen, die Option mountOption in der StorageClass an `discard`, um Inline-Speicherplatz zurückzunehmen. Siehe https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Red hat Dokumentation"^].


[role="tabbed-block"]
====
.RHEL 8 ODER HÖHER
--
. Installieren Sie die folgenden Systempakete:
+
[source, console]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. Multipathing aktivieren:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: Unbedingt `etc/multipath.conf` Enthält `find_multipaths no` Unter `defaults`.

. Stellen Sie sicher, dass `multipathd` Folgendes ausgeführt wird:
+
[source, console]
----
sudo systemctl enable --now multipathd
----


--
.Ubuntu
--
. Installieren Sie die folgenden Systempakete:
+
[source, console]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. Multipathing aktivieren:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: Unbedingt `etc/multipath.conf` Enthält `find_multipaths no` Unter `defaults`.

. Stellen Sie sicher, dass `multipath-tools` aktiviert und ausgeführt wird:
+
[source, console]
----
sudo systemctl status multipath-tools
----


--
====