---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, service type, service level, cloud volumes 
summary: Sehen Sie sich die Konfigurationsoptionen an, die für Ihre Trident Konfigurationen verfügbar sind. 
---
= Optionen für die Storage-Konfiguration
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sehen Sie sich die Konfigurationsoptionen an, die für Ihre Trident Konfigurationen verfügbar sind.



== Globale Konfigurationsoptionen

Diese Konfigurationsoptionen sind für alle Trident-Konfigurationen anwendbar, unabhängig davon, welche Storage-Plattform genutzt wird.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `version`  a| 
Versionsnummer der Konfigurationsdatei
 a| 
`1`



| `storageDriverName`  a| 
Name des Speichertreibers
 a| 
`ontap-nas`, `ontap-san`, `ontap-nas-economy`,
`ontap-nas-flexgroup`, `solidfire-san`



| `storagePrefix`  a| 
Optionales Präfix für Volume-Namen Standard: `netappdvp_`.
 a| 
`staging_`



| `limitVolumeSize`  a| 
Optionale Einschränkung von Volume-Größen. Standard: „“ (nicht erzwungen)
 a| 
`10g`

|===

TIP: Verwenden Sie (einschließlich der Standardeinstellung) keine `storagePrefix` Back-Ends für Elemente. Standardmäßig ignoriert der `solidfire-san` Treiber diese Einstellung und verwendet kein Präfix. NetApp empfiehlt die Verwendung einer bestimmten TenantID für die Docker-Volume-Zuordnung oder der Attributdaten, die mit der Docker-Version, der Treiberinfo und dem Rohnamen aus Docker gefüllt sind, falls eventuell Namenspunk verwendet wurden.

Es stehen Standardoptionen zur Verfügung, damit Sie sie nicht für jedes erstellte Volume angeben müssen. Der `size` Die Option ist für alle Controller-Typen verfügbar. Im Abschnitt zur ONTAP-Konfiguration finden Sie ein Beispiel dafür, wie Sie die Standard-Volume-Größe festlegen.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `size`  a| 
Optionale Standardgröße für neue Volumes. Standard: `1G`
 a| 
`10G`

|===


== ONTAP-Konfiguration

Zusätzlich zu den oben genannten globalen Konfigurationswerten stehen bei Verwendung von ONTAP folgende Optionen auf oberster Ebene zur Verfügung.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `managementLIF`  a| 
IP-Adresse des ONTAP Management LIF. Sie können einen vollqualifizierten Domänennamen (FQDN) angeben.
 a| 
`10.0.0.1`



| `dataLIF`  a| 
IP-Adresse des LIF-Protokolls.

*ONTAP NAS Treiber*: NetApp empfiehlt die Angabe `dataLIF`. Wenn nicht angegeben, ruft Trident die DatenLIFs von der SVM ab. Sie können einen vollständig qualifizierten Domänennamen (FQDN) angeben, der für die NFS-Mount-Vorgänge verwendet werden soll. Dadurch können Sie ein Round-Robin-DNS erstellen, um den Lastausgleich über mehrere DatenLIFs hinweg zu ermöglichen.

*ONTAP SAN-Treiber*: Nicht für iSCSI oder FC angeben. Trident verwendet link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP selektive LUN-Zuordnung"^] zur Erkennung der für eine Multi-Path-Sitzung erforderlichen iSCSI oder FC LIFs. Eine Warnung wird erzeugt, wenn `dataLIF` explizit definiert ist.
 a| 
`10.0.0.2`



| `svm`  a| 
Storage Virtual Machine zu verwenden (erforderlich, falls Management LIF eine Cluster-LIF ist)
 a| 
`svm_nfs`



| `username`  a| 
Benutzername zur Verbindung mit dem Speichergerät
 a| 
`vsadmin`



| `password`  a| 
Passwort für die Verbindung mit dem Speichergerät
 a| 
`secret`



| `aggregate`  a| 
Aggregat für die Bereitstellung (optional, wenn eingestellt, muss der SVM zugewiesen werden) Für den `ontap-nas-flexgroup` Treiber wird diese Option ignoriert. Zur Bereitstellung eines FlexGroup Volumes werden alle der SVM zugewiesenen Aggregate verwendet.
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Optionale, fail-Provisioning-Funktion, wenn die Nutzung über diesem Prozentsatz liegt
 a| 
`75%`



| `nfsMountOptions`  a| 
Feingranulare Steuerung der NFS-Mount-Optionen; standardmäßig „-o nfsvers=3“. *Nur verfügbar für die `ontap-nas` und `ontap-nas-economy` Fahrer*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Siehe Informationen zur NFS-Host-Konfiguration hier"^].
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Trident erstellt und verwaltet pro Node `igroups` wie `netappdvp`.

Dieser Wert kann nicht geändert oder weggelassen werden.

*Nur für die verfügbar `ontap-san` Fahrer*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Maximale anforderbare Volume-Größe.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Maximale Anzahl der qtrees pro FlexVol, die im Bereich [50, 300] liegen müssen, die Standardeinstellung ist 200.

* Für die `ontap-nas-economy` Treiber: Mit dieser Option kann die maximale Anzahl von qtrees pro FlexVol* angepasst werden.
 a| 
`300`



 a| 
`sanType`
| *Nur für Treiber unterstützt `ontap-san`.* Verwenden Sie diese Option, um für iSCSI, `nvme` für NVMe/TCP oder `fcp` für SCSI über Fibre Channel (FC) auszuwählen `iscsi`. | `iscsi` Falls leer 


| `limitVolumePoolSize` | * `ontap-san-economy` `ontap-san-economy`Nur für und Treiber unterstützt.* Begrenzung der FlexVol-Größe bei den wirtschaftlichen Faktoren ONTAP ONTAP-nas und ONTAP-SAN  a| 
`300g`

|===
Es stehen Standardoptionen zur Verfügung, um zu vermeiden, dass sie auf jedem von Ihnen erstellten Volume angegeben werden müssen:

[cols="1,3,2"]
|===
| Option | Beschreibung | Beispiel 


| `spaceReserve`  a| 
Modus für Speicherplatzreservierung; `none` (Thin Provisioning) oder `volume` (Dick)
 a| 
`none`



| `snapshotPolicy`  a| 
Zu verwendende Snapshot-Richtlinie, Standard ist `none`
 a| 
`none`



| `snapshotReserve`  a| 
Der Prozentsatz der Snapshot-Reserve ist standardmäßig „“, um den ONTAP-Standardwert zu akzeptieren
 a| 
`10`



| `splitOnClone`  a| 
Teilen Sie einen Klon bei der Erstellung von seinem übergeordneten Element auf. Dies ist standardmäßig der Standardwert `false`
 a| 
`false`



| `encryption`  a| 
Aktiviert NetApp Volume Encryption (NVE) auf dem neuen Volume, standardmäßig aktiviert `false`. NVE muss im Cluster lizenziert und aktiviert sein, damit diese Option verwendet werden kann.

Wenn auf dem Backend NAE aktiviert ist, wird jedes in Trident bereitgestellte Volume NAE aktiviert.

Weitere Informationen finden Sie unter link:../trident-reco/security-reco.html["Funktionsweise von Trident mit NVE und NAE"].
 a| 
Richtig



| `unixPermissions`  a| 
NAS-Option für bereitgestellte NFS-Volumes, standardmäßig auf `777`
 a| 
`777`



| `snapshotDir`  a| 
NAS-Option für den Zugriff auf das `.snapshot` Verzeichnis.
 a| 
„Wahr“ für NFSv4 „falsch“ für NFSv3



| `exportPolicy`  a| 
NAS-Option für die zu verwendende NFS-Exportrichtlinie, standardmäßig auf `default`
 a| 
`default`



| `securityStyle`  a| 
NAS-Option für Zugriff auf das bereitgestellte NFS-Volume.

NFS unterstützt `mixed` Und `unix` Sicherheitsstile. Die Standardeinstellung lautet `unix`.
 a| 
`unix`



| `fileSystemType`  a| 
SAN-Option zum Auswählen des Dateisystemtyps, standardmäßig auf `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
Zu verwendende Tiering-Richtlinie, Standardwert ist `none`.
 a| 
`none`



| `skipRecoveryQueue`  a| 
Beim Löschen eines Volumes wird die Wiederherstellungswarteschlange im Speicher umgangen und das Volume sofort gelöscht.
 a| 
``

|===


=== Skalierungsoptionen

Die `ontap-nas` Treiber und `ontap-san` erstellen eine ONTAP FlexVol für jedes Docker Volume. ONTAP unterstützt bis zu 1000 FlexVols pro Cluster-Node mit einem Cluster von maximal 12,000 FlexVol Volumes. Wenn die Anforderungen Ihres Docker Volumes diese Einschränkung erfüllen, ist der Treiber aufgrund der zusätzlichen Funktionen von FlexVols `ontap-nas`, wie Snapshots auf Docker Volume-Ebene und Klonen, die bevorzugte NAS-Lösung.

Wenn Sie mehr Docker Volumes benötigen, als durch die FlexVol-Limits unterstützt werden können, wählen Sie die Option `ontap-nas-economy` Oder im `ontap-san-economy` Treiber.

Der `ontap-nas-economy` Treiber erstellt Docker Volumes als ONTAP qtrees innerhalb eines Pools automatisch gemanagter FlexVol Volumes. Qtrees bieten eine wesentlich größere Skalierung – bis zu 100,000 pro Cluster-Node und 2,400,000 pro Cluster – zu Lasten einiger Funktionen.  `ontap-nas-economy`Snapshots oder Klonen mit granularem Docker Volume werden vom Treiber nicht unterstützt.


NOTE: Der `ontap-nas-economy` Treiber wird derzeit in Docker Swarm nicht unterstützt, da Docker Swarm die Volume-Erstellung nicht über mehrere Nodes hinweg orchestriert.

Der `ontap-san-economy` Treiber erstellt Docker Volumes als ONTAP-LUNs in einem gemeinsamen Pool von automatisch gemanagten FlexVol-Volumes. Somit ist jede FlexVol nicht auf nur eine LUN beschränkt und bietet eine bessere Skalierbarkeit für SAN-Workloads. Je nach Storage Array unterstützt ONTAP bis zu 16384 LUNs pro Cluster. Da es sich bei den Volumes um LUNs handelt, unterstützt dieser Treiber granulare Docker Snapshots und Klone.

Wählen Sie den `ontap-nas-flexgroup` Treiber, um die Parallelität zu einem einzelnen Volume zu erhöhen, das bis in den Petabyte-Bereich mit Milliarden von Dateien anwachsen kann. Zu den idealen Anwendungsfällen für FlexGroups gehören KI/ML/DL, Big Data und Analysen, Softwareentwicklung, Streaming, Datei-Repositorys und so weiter. Trident verwendet bei der Bereitstellung eines FlexGroup Volumes alle Aggregate, die einer SVM zugewiesen sind. Die Unterstützung von FlexGroup in Trident muss darüber hinaus Folgendes beachtet werden:

* ONTAP Version 9.2 oder höher erforderlich.
* Ab diesem Text unterstützt FlexGroups nur NFS v3.
* Empfohlen, die 64-Bit-NFSv3-IDs für die SVM zu aktivieren.
* Die empfohlene Mindestgröße für FlexGroup Mitglieder/Volumes beträgt 100 GiB.
* Klonen wird für FlexGroup Volumes nicht unterstützt.


Informationen zu FlexGroups und Workloads, die für FlexGroups geeignet sind, finden Sie im https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["Best Practices und Implementierungsleitfaden für NetApp FlexGroup Volumes"^].

Um erweiterte Funktionen und umfassende Skalierbarkeit in derselben Umgebung zu erhalten, können Sie mehrere Instanzen des Docker Volume Plug-ins ausführen, wobei eine verwendet und eine andere `ontap-nas-economy` verwendet `ontap-nas` wird.



=== Benutzerdefinierte ONTAP-Rolle für Trident

Sie können eine ONTAP-Cluster-Rolle mit minimaler Privileges erstellen, sodass Sie nicht die ONTAP-Administratorrolle verwenden müssen, um Vorgänge in Trident auszuführen. Wenn Sie den Benutzernamen in eine Trident-Back-End-Konfiguration aufnehmen, verwendet Trident die ONTAP-Cluster-Rolle, die Sie für die Durchführung der Vorgänge erstellt haben.

Weitere Informationen zum Erstellen benutzerdefinierter Trident-Rollen finden Sie unterlink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Trident Custom-Role Generator"].

[role="tabbed-block"]
====
.Verwenden der ONTAP CLI
--
. Erstellen Sie eine neue Rolle mit dem folgenden Befehl:
+
`security login role create <role_name\> -cmddirname "command" -access all -vserver <svm_name\>`

. Erstellen Sie einen Benutzernamen für den Trident-Benutzer:
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`

. Ordnen Sie die Rolle dem Benutzer zu:
+
`security login modify username <user_name\> -vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.Verwenden Von System Manager
--
Führen Sie die folgenden Schritte im ONTAP System Manager durch:

. *Erstellen Sie eine benutzerdefinierte Rolle*:
+
.. Um eine benutzerdefinierte Rolle auf Cluster-Ebene zu erstellen, wählen Sie *Cluster > Einstellungen* aus.
+
(Oder) um eine benutzerdefinierte Rolle auf SVM-Ebene zu erstellen, wählen Sie *Storage > Storage VMs > > `required SVM` Einstellungen > Benutzer und Rollen* aus.

.. Wählen Sie das Pfeilsymbol (*->*) neben *Users and Roles*.
.. Wählen Sie unter *Rollen* *+Hinzufügen* aus.
.. Definieren Sie die Regeln für die Rolle und klicken Sie auf *Speichern*.


. *Rolle dem Trident-Benutzer zuordnen*: + Führen Sie auf der Seite *Benutzer und Rollen* folgende Schritte aus:
+
.. Wählen Sie unter *Benutzer* das Symbol Hinzufügen *+*.
.. Wählen Sie den gewünschten Benutzernamen aus, und wählen Sie im Dropdown-Menü für *Rolle* eine Rolle aus.
.. Klicken Sie Auf *Speichern*.




--
====
Weitere Informationen finden Sie auf den folgenden Seiten:

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["Benutzerdefinierte Rollen für die Administration von ONTAP"^] Oder link:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["Definieren benutzerdefinierter Rollen"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["Arbeiten Sie mit Rollen und Benutzern"^]




=== Beispiel für ONTAP-Konfigurationsdateien

.NFS-Beispiel für <code>ontap-nas</code> Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "defaults": {
    "size": "10G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.NFS-Beispiel für <code>ontap-nas-flexgroup</code> Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-flexgroup",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "defaults": {
    "size": "100G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.NFS-Beispiel für <code>ontap-nas-economy</code> Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
----
====
.ISCSI-Beispiel für <code>ontap-san</code> Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.NFS-Beispiel für <code>ontap-san-economy</code> Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi_eco",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.NVMe/TCP – Beispiel für <code>ontap-san</code> Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username": "vsadmin",
  "password": "password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.SCSI über FC-Beispiel für <code> ONTAP-</code>-Treiber
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username": "vsadmin",
  "password": "password",
  "useREST": true
}
----
====


== Konfiguration von Element Software

Zusätzlich zu den Werten einer globalen Konfiguration sind bei Verwendung von Element Software (NetApp HCI/SolidFire) diese Optionen verfügbar.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `Endpoint`  a| 
\https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
ISCSI-IP-Adresse und -Port
 a| 
10.0.0.7:3260 Uhr



| `TenantName`  a| 
SolidFireF Mandanten zu verwenden (erstellt, falls nicht gefunden)
 a| 
`docker`



| `InitiatorIFace`  a| 
Geben Sie die Schnittstelle an, wenn der iSCSI-Datenverkehr auf eine nicht-Standardschnittstelle beschränkt wird
 a| 
`default`



| `Types`  a| 
QoS-Spezifikationen
 a| 
Siehe das Beispiel unten



| `LegacyNamePrefix`  a| 
Präfix für aktualisierte Trident Installationen. Wenn Sie eine Version von Trident vor 1.3.2 verwendet und ein Upgrade mit vorhandenen Volumes durchführen, müssen Sie diesen Wert einstellen, um auf die alten Volumes zuzugreifen, die über die Volume-Name-Methode zugeordnet wurden.
 a| 
`netappdvp-`

|===
Der `solidfire-san` Der Treiber unterstützt Docker Swarm nicht.



=== Beispiel für eine Konfigurationsdatei für die Element Software

[source, json]
----
{
  "version": 1,
  "storageDriverName": "solidfire-san",
  "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
  "SVIP": "10.0.0.7:3260",
  "TenantName": "docker",
  "InitiatorIFace": "default",
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----