---
sidebar: sidebar 
permalink: trident-docker/upgrade-uninstall-docker.html 
keywords: uninstall, Trident, trident for docker, docker, upgrade trident for docker 
summary: 'Sie können ein Upgrade von Trident für Docker sicher durchführen, ohne die verwendeten Volumes zu beeinträchtigen. Während des Upgrade-Prozesses wird es einen kurzen Zeitraum geben, in dem `docker volume` Befehle, die auf das Plugin gerichtet sind, nicht erfolgreich sind, und Anwendungen können keine Volumes mounten, bis das Plugin wieder ausgeführt wird. Unter den meisten Umständen dauert das nur wenige Sekunden.' 
---
= Aktualisieren oder deinstallieren Sie Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade von Trident für Docker sicher durchführen, ohne die verwendeten Volumes zu beeinträchtigen. Während des Upgrade-Prozesses wird es einen kurzen Zeitraum geben, in dem `docker volume` Befehle, die auf das Plugin gerichtet sind, nicht erfolgreich sind, und Anwendungen können keine Volumes mounten, bis das Plugin wieder ausgeführt wird. Unter den meisten Umständen dauert das nur wenige Sekunden.



== Upgrade

Führen Sie die folgenden Schritte aus, um Trident für Docker zu aktualisieren.

.Schritte
. Liste der vorhandenen Volumes:
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
. Deaktivieren Sie das Plugin:
+
[listing]
----
docker plugin disable -f netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Upgrade des Plug-ins:
+
[listing]
----
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
----
+

NOTE: Die Version 18.01 von Trident ersetzt nDVP. Sie sollten direkt vom Bild auf das `netapp/trident-plugin` Bild upgraden `netapp/ndvp-plugin`.

. Plug-in aktivieren:
+
[listing]
----
docker plugin enable netapp:latest
----
. Vergewissern Sie sich, dass das Plug-in aktiviert ist:
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----
. Vergewissern Sie sich, dass die Volumes sichtbar sind:
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----



IMPORTANT: Wenn Sie ein Upgrade von einer alten Version von Trident (vor 20.10) auf Trident 20.10 oder höher durchführen, kann es zu einem Fehler kommen. Weitere Informationen finden Sie unter link:known-issues-docker.html["Bekannte Probleme"^]. Wenn Sie in den Fehler laufen, sollten Sie zuerst das Plugin deaktivieren, dann entfernen Sie das Plugin, und installieren Sie dann die erforderliche Trident-Version, indem Sie einen zusätzlichen Konfigurationsparameter übergeben: `docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json`



== Deinstallieren

Führen Sie die folgenden Schritte aus, um Trident für Docker zu deinstallieren.

.Schritte
. Entfernen Sie alle Volumes, die das Plugin erstellt.
. Deaktivieren Sie das Plugin:
+
[listing]
----
docker plugin disable netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Entfernen Sie das Plugin:
+
[listing]
----
docker plugin rm netapp:latest
----

