---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: 'Um Volumes zu erstellen, verwenden Sie bei Bedarf die Standardbefehle `docker volume` mit dem angegebenen Trident-Treibernamen.' 
---
= Arbeiten mit Volumes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volumes können ganz einfach mit den Standardbefehlen erstellt, geklont und entfernt werden. Der bei Bedarf angegebene Trident-Treibername wird dabei verwendet `docker volume`.



== Erstellen eines Volumes

* Erstellen Sie ein Volume mit einem Treiber unter Verwendung des Standardnamens:
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
* Volume mit einer bestimmten Trident-Instanz erstellen:
+
[source, console]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: Falls Sie keine angeben link:volume-driver-options.html["Optionen"^], Die Standardeinstellungen für den Treiber werden verwendet.

* Überschreiben Sie die Standard-Volumegröße. Im folgenden Beispiel wird gezeigt, wie Sie ein 20-GiB-Volume mit einem Treiber erstellen:
+
[source, console]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: Die Volume-Größen werden als Strings angegeben, die einen ganzzahligen Wert mit optionalen Einheiten enthalten (Beispiel: 10G, 20GB, 3tib). Wenn keine Einheiten angegeben werden, lautet der Standardwert G. Einheiten der Größe können entweder als Befugnisse von 2 (B, KiB, MiB, gib, tib) oder als Befugnis von 10 (B, KB, MB, GB, TB) angegeben werden. Auf Kurzschluss und Einheiten werden 2 Kräfte (G = gib, T = tib, …) verwendet.





== Entfernen Sie ein Volume

* Entfernen Sie das Volume wie jedes andere Docker Volume:
+
[source, console]
----
docker volume rm firstVolume
----
+

IMPORTANT: Bei Verwendung des `solidfire-san` Treiber, im obigen Beispiel wird das Volume gelöscht und gelöscht.



Führen Sie die folgenden Schritte aus, um Trident für Docker zu aktualisieren.



== Klonen Sie ein Volume

Bei der Verwendung des `ontap-nas` , `ontap-san` , Und `solidfire-san` Speichertreiber, Trident kann Volumes klonen. Bei der Verwendung des `ontap-nas-flexgroup` oder `ontap-nas-economy` Treiber, Klonen wird nicht unterstützt. Wenn aus einem bestehenden Volume ein neues Volume erstellt wird, wird ein neuer Snapshot erstellt.

* Überprüfen Sie das Volume, um die Snapshots aufzuzählen:
+
[source, console]
----
docker volume inspect <volume_name>
----
* Erstellen Sie ein neues Volume von einem vorhandenen Volume aus. Dadurch wird ein neuer Snapshot erstellt:
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* Erstellen Sie ein neues Volume anhand eines vorhandenen Snapshots auf einem Volume. Dadurch wird kein neuer Snapshot erstellt:
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== Beispiel

[source, console]
----
docker volume inspect firstVolume

[
  {
    "Driver": "ontap-nas",
    "Labels": null,
    "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
    "Name": "firstVolume",
    "Options": {},
    "Scope": "global",
    "Status": {
      "Snapshots": [
        {
          "Created": "2017-02-10T19:05:00Z",
          "Name": "hourly.2017-02-10_1505"
        }
      ]
    }
  }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== Zugriff auf extern erstellte Volumes

Sie können über Trident * nur* auf extern erstellte Blockgeräte (oder deren Clones) zugreifen, wenn sie keine Partitionen haben und wenn ihr Dateisystem von Trident unterstützt wird (z.B.: Ein `ext4`-formatiertes `/dev/sdc1` wird nicht über Trident zugänglich sein).
