---
settings:
  name: Astra Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: trident-rn.html
  versions:
  - name: Astra Trident
    url: "/trident"
    version-number: '23.01'
  - name: Astra Trident
    url: "/trident-2210"
    version-number: '22.10'
  - name: Astra Trident
    url: "/trident-2207"
    version-number: '22.07'
  - name: Astra Trident
    url: "/trident-2204"
    version-number: '22.04'
  - name: Astra Trident
    url: "/trident-2201"
    version-number: '22.01'
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: Astra Trident Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/trident-rn.html"
  - section: trident-concepts
  - section: trident-get-started
  - section: trident-managing-k8s
  - section: trident-use
  - section: trident-docker
  - title: FAQs
    url: "/faq.html"
  - title: Unterstützung
    url: "/get-help.html"
  - title: Fehlerbehebung
    url: "/troubleshooting.html"
  - section: trident-reco
  - section: trident-reference
  - title: Frühere Versionen
    url: "/earlier-versions.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Die komplette Astra Dokumentation
