---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: NetApp verbessert seine Produkte und Services kontinuierlich. Hier finden Sie einige der neuesten Funktionen, Verbesserungen und Fehlerkorrekturen in der neuesten Version von Trident. 
---
= Was ist neu
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Versionshinweise enthalten Informationen zu neuen Funktionen, Verbesserungen und Fehlerbehebungen in der neuesten Version von NetApp Trident.


WARNING: Der `tridentctl` Binary for Linux, die in der ZIP-Datei des Installationsprogramms bereitgestellt wird, ist die getestete und unterstützte Version. Beachten Sie, dass der `macos` Binärdateien sind im enthalten `/extras` Ein Teil der ZIP-Datei wird nicht getestet oder unterstützt.



== Was ist neu in Version 25.10?

Erfahren Sie mehr über die Neuerungen in Trident und Trident Protect, einschließlich Verbesserungen, Fehlerbehebungen und veralteter Funktionen.



=== Trident



==== Vorgestellt Werden

* *Kubernetes*:
+
** Zusätzlich zu ONTAP -SAN (iSCSI und FC) wurde die Unterstützung für CSI Volume Group Snapshots mit den v1beta1 Volume Group Snapshot Kubernetes APIs für ONTAP-NAS NFS- und ONTAP -SAN-Economy-Treiber hinzugefügt. Sehenlink:https://docs.netapp.com/us-en/trident/trident-use/vol-group-snapshots.html["Arbeiten mit Volumegruppen-Snapshots"^] .
** Unterstützung für automatisiertes Workload-Failover mit erzwungener Volume-Trennung für die Treiber ONTAP-NAS und ONTAP-NAS-Economy (ohne SMB in beiden NAS-Treibern) sowie für die Treiber ONTAP-SAN und ONTAP-SAN-Economy hinzugefügt. Sehenlink:https://docs.netapp.com/us-en/trident/trident-reco/force-detach.html["Automatisierung des Failovers zustandsbehafteter Anwendungen mit Trident"^] .
** Verbesserte Trident Knotenkonkurrenz für höhere Skalierbarkeit bei Knotenoperationen für FCP-Volumes.
** ONTAP AFX-Unterstützung für den ONTAP NAS-Treiber hinzugefügt. Sehenlink:https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html["ONTAP NAS-Konfigurationsoptionen und -Beispiele"^] .
** Es wurde Unterstützung für die Konfiguration von CPU- und Speicherressourcenanforderungen und -grenzen für Trident Container über TridentOrchestrator CR- und Helm-Chart-Werte hinzugefügt. (link:https://github.com/NetApp/trident/issues/1000["Ausgabe Nr. 1000"] ,link:https://github.com/NetApp/trident/issues/927["Ausgabe Nr. 927"] ,link:https://github.com/NetApp/trident/issues/853["Ausgabe Nr. 853"] ,link:https://github.com/NetApp/trident/issues/592["Ausgabe Nr. 592"] ,link:https://github.com/NetApp/trident/issues/110["Ausgabe Nr. 110"] ).
** FC-Unterstützung für die ASAr2-Persönlichkeit hinzugefügt. Sehenlink:https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["ONTAP SAN-Konfigurationsoptionen und -Beispiele"^] .
** Es wurde eine Option hinzugefügt, um Prometheus-Metriken mit HTTPS anstelle von HTTP bereitzustellen. Sehenlink:https://docs.netapp.com/us-en/trident/trident-use/monitor-trident.html["Monitoring von Trident"^] .
** Eine Option wurde hinzugefügt `--no-rename` Beim Importieren eines Volumes soll der ursprüngliche Name beibehalten werden, die Verwaltung des Lebenszyklus des Volumes soll jedoch Trident überlassen werden. Sehenlink:https://docs.netapp.com/us-en/trident/trident-use/vol-import.html["Volumes importieren"^] .
** Die Trident Bereitstellung erfolgt nun mit der Prioritätsklasse „system-cluster-kritisch“.


* Es wurde eine Option hinzugefügt, mit der der Trident -Controller die Host-Netzwerkfunktionen über Helm, Operator und tridentctl nutzen kann (link:https://github.com/NetApp/trident/issues/858["Ausgabe Nr. 858"] ).
* Dem ANF-Treiber wurde die manuelle QoS-Unterstützung hinzugefügt, wodurch er in Trident 25.10 produktionsreif ist; diese experimentelle Erweiterung wurde in Trident 25.06 eingeführt.




==== Experimentelle Verbesserungen


NOTE: Nicht für den Einsatz in Produktionsumgebungen.

* *[Technische Vorschau]*: Zusätzlich zur bereits vorhandenen technischen Vorschau für den ONTAP -SAN-Treiber (iSCSI- und FCP-Protokolle in Unified ONTAP 9) wurde die Unterstützung für Parallelverarbeitung für ONTAP-NAS (nur NFS) und ONTAP -SAN (NVMe für Unified ONTAP 9) hinzugefügt.




==== Korrekturen

* **Kubernetes**:
+
** Die Namensinkonsistenz des CSI node-driver-registrar-Containers wurde behoben, indem Linux DaemonSet auf node-driver-registrar standardisiert wurde, um der Namensgebung von Windows DaemonSet und Container-Images zu entsprechen.
** Es wurde ein Problem behoben, bei dem Exportrichtlinien für ältere Qtrees nicht ordnungsgemäß aktualisiert wurden.


* *Openshift*:
+
** Problem behoben: Trident -Node-Pod startete auf Windows-Nodes in Openshift nicht, weil SCC allowHostDirVolumePlugin auf false gesetzt hatte (link:https://github.com/NetApp/trident/issues/950["Ausgabe Nr. 950"] ).


* Behoben: Kubernetes API QPS wurde nicht über Helm festgelegt (link:https://github.com/NetApp/trident/issues/975["Ausgabe Nr. 975"] ).
* Es wurde ein Fehler behoben, der das Mounten eines Persistent Volume Claim (PVC) basierend auf einem Snapshot eines NVMe-basierten XFS-Dateisystems auf demselben Kubernetes-Knoten unmöglich machte.
* Das Problem mit der Änderung der UUID nach einem Neustart des Hosts/Docker im NDVP-Modus wurde behoben, indem pro Backend eindeutige/gemeinsame Subsystemnamen hinzugefügt wurden (z. B. netappdvp_subsystem).
* Behobene Mount-Fehler für iSCSI-Volumes beim Trident Upgrade von Versionen vor 23.10 auf 24.10 und höher, wodurch das Problem „ungültiger SANType“ behoben wurde.
* Problem behoben, bei dem der Trident Backend-Status nicht ohne Neustart des Trident -Controllers auf Online/Offline umgeschaltet wurde.
* Behoben wurde ein zeitweise auftretender Rennfehler, der zu einer langsamen PVC-Größenänderung führte.
* Behoben: Snapshots wurden bei Fehlern beim Klonen von Volumes nicht bereinigt.
* Es wurde ein Fehler behoben, der dazu führte, dass ein Volume nicht mehr freigegeben wurde, wenn sein Gerätepfad vom Kernel geändert wurde.
* Behoben: Fehler beim Entfernen des Volumes aus der Bereitstellungsphase aufgrund eines bereits geschlossenen LUKS-Geräts.
* Problem behoben, bei dem langsame Speicheroperationen zu ContextDeadline-Fehlern führten.
* Der Trident Operator wartet bis zum Erreichen des konfigurierbaren k8s-Timeouts, um die Trident -Version zu überprüfen.




=== Trident Protect

NetApp Trident Protect bietet erweiterte Funktionen für das Applikations-Datenmanagement, mit denen die Funktionalität und Verfügbarkeit zustandsbehafteter Kubernetes-Applikationen auf der Basis von NetApp ONTAP Storage-Systemen und der NetApp Trident CSI Storage-bereitstellung verbessert werden.



==== Vorgestellt Werden

* Hinzugefügte Anmerkungen zur Steuerung der Snapshot-CR-Timeouts für geplante und Backup-CRs:
+
** `protect.trident.netapp.io/snapshot-completion-timeout`
** `protect.trident.netapp.io/volume-snapshots-ready-to-use-timeout`
** `protect.trident.netapp.io/volume-snapshots-created-timeout`
+
Sehenlink:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-protect-apps.html["Unterstützte Backup- und Zeitplananmerkungen"^] .



* Dem Zeitplan-CR wurde eine Anmerkung hinzugefügt, um das PVC-Bindungs-Timeout zu konfigurieren, das vom Backup-CR verwendet wird: `protect.trident.netapp.io/pvc-bind-timeout-sec` Die Sehenlink:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-protect-apps.html["Unterstützte Backup- und Zeitplananmerkungen"^] .
* Verbessert `tridentctl-protect` Backup- und Snapshot-Listen mit einem neuen Feld zur Anzeige von Ausführungs-Hook-Fehlern.




== Änderungen vom 25.06.2



=== Trident



==== Korrekturen

* *Kubernetes*: Kritisches Problem behoben, bei dem beim Trennen von Volumes von Kubernetes-Knoten falsche iSCSI-Geräte erkannt wurden.




== Änderungen in 25.06.1



=== Trident


IMPORTANT: Kunden, die SolidFire verwenden, sollten aufgrund eines bekannten Problems beim Aufheben der Veröffentlichung von Volumes kein Upgrade auf 25.06.1 durchführen.  Um dieses Problem zu beheben, wird in Kürze 25.06.2 veröffentlicht.



==== Korrekturen

* *Kubernetes*:
+
** Ein Problem wurde behoben, bei dem NQNs nicht überprüft wurden, bevor sie von Subsystemen getrennt wurden.
** Ein Problem wurde behoben, bei dem mehrere Versuche, ein LUKS-Gerät zu schließen, zu Fehlern beim Trennen von Volumes führten.
** Behoben: Unstance des iSCSI-Volumes, wenn sich der Gerätepfad seit seiner Erstellung geändert hat.
** Blockieren Sie das Klonen von Volumes über Speicherklassen hinweg.


* *OpenShift*: Ein Problem behoben, bei dem die iSCSI-Knotenvorbereitung mit OCP 4.19 fehlschlug.
* Das Timeout beim Klonen eines Volumes mit SolidFire -Backends wurde erhöht (link:https://github.com/NetApp/trident/issues/1008["Ausgabe #1008"] ).




== Änderungen in 25.06



=== Trident



==== Vorgestellt Werden

* *Kubernetes*:
+
** Unterstützung für CSI Volume Group Snapshots mit  `v1beta1` Volume Group Snapshot Kubernetes-APIs für ONTAP-SAN iSCSI-Treiber. Siehe link:https://docs.netapp.com/us-en/trident/trident-use/vol-group-snapshots.html["Arbeiten mit Volumegruppen-Snapshots"^].
+

NOTE: VolumeGroupSnapshot ist eine Beta-Funktion in Kubernetes mit Beta-APIs. Für VolumeGroupSnapshot ist mindestens Kubernetes 1.32 erforderlich.

** Zusätzlich zu iSCSI wurde die Unterstützung für ONTAP ASA r2 für NVMe/TCP hinzugefügt. Sehenlink:https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["ONTAP SAN-Konfigurationsoptionen und -Beispiele"^] .
** Sichere SMB-Unterstützung für ONTAP-NAS- und ONTAP-NAS-Economy-Volumes hinzugefügt. Active Directory-Benutzer und -Gruppen können jetzt mit SMB-Volumes für erhöhte Sicherheit verwendet werden. Siehe link:https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html#enable-secure-smb["Sicheres SMB aktivieren"^].
** Verbesserte Trident-Knoten-Parallelität für höhere Skalierbarkeit bei Knotenvorgängen für iSCSI-Volumes.
** Hinzugefügt  `--allow-discards` beim Öffnen von LUKS-Volumes, um Discard/TRIM-Befehle zur Speicherplatzrückgewinnung zu ermöglichen.
** Verbesserte Leistung beim Formatieren von LUKS-verschlüsselten Volumes.
** Verbesserte LUKS-Bereinigung für ausgefallene, aber teilweise formatierte LUKS-Geräte.
** Verbesserte Trident-Knoten-Idempotenz zum Anhängen und Trennen von NVMe-Volumes.
** Hinzugefügt  `internalID` Feld zur Trident-Volume-Konfiguration für den ONTAP-SAN-Economy-Treiber.
** Unterstützung für die Volume-Replikation mit SnapMirror für NVMe-Backends hinzugefügt. Siehe link:https://docs.netapp.com/us-en/trident/trident-use/vol-volume-replicate.html["Replizieren Sie Volumes mit SnapMirror"^].






==== Experimentelle Verbesserungen


NOTE: Nicht für den Einsatz in Produktionsumgebungen.

* [Tech Preview] Ermöglicht gleichzeitige Trident-Controller-Operationen über die  `--enable-concurrency` Feature-Flag. Dadurch können Controller-Operationen parallel ausgeführt werden, was die Leistung in stark ausgelasteten oder großen Umgebungen verbessert.
+

NOTE: Diese Funktion ist experimentell und unterstützt derzeit begrenzte parallele Arbeitsabläufe mit dem ONTAP-SAN-Treiber (iSCSI- und FCP-Protokolle).

* [Technische Vorschau] Manuelle QOS-Unterstützung mit dem ANF-Treiber hinzugefügt.




==== Korrekturen

* *Kubernetes*:
+
** Ein Problem mit CSI NodeExpandVolume wurde behoben, bei dem Multipath-Geräte inkongruente Größen aufweisen konnten, wenn die zugrunde liegenden SCSI-Festplatten nicht verfügbar waren.
** Fehler beim Bereinigen doppelter Exportrichtlinien für ONTAP-NAS- und ONTAP-NAS-Economy-Treiber behoben.
** Behoben: GCNV-Volumes verwenden standardmäßig NFSv3, wenn  `nfsMountOptions` ist deaktiviert; jetzt werden sowohl NFSv3- als auch NFSv4-Protokolle unterstützt. Wenn  `nfsMountOptions` nicht angegeben ist, wird die Standard-NFS-Version des Hosts (NFSv3 oder NFSv4) verwendet.
** Bereitstellungsproblem bei der Installation von Trident mit Kustomize behoben ( link:https://github.com/NetApp/trident/issues/831["Ausgabe #831"] ).
** Fehlende Exportrichtlinien für PVCs, die aus Snapshots erstellt wurden, behoben ( link:https://github.com/NetApp/trident/issues/1016["Ausgabe #1016"] ).
** Problem behoben, bei dem die ANF-Volume-Größen nicht automatisch in 1-GiB-Schritten ausgerichtet werden.
** Problem bei der Verwendung von NFSv3 mit Bottlerocket behoben.


* Problem behoben, bei dem ONTAP-NAS-Economy-Volumes trotz Größenänderungsfehlern auf bis zu 300 TB erweitert wurden.
* Problem behoben, bei dem Klon-Split-Vorgänge bei Verwendung der ONTAP REST API synchron ausgeführt wurden.




==== Veraltete Funktionen:

* *Kubernetes*: Mindestens unterstütztes Kubernetes auf v1.27 aktualisiert.




=== Trident Protect

NetApp Trident Protect bietet erweiterte Funktionen für das Applikations-Datenmanagement, mit denen die Funktionalität und Verfügbarkeit zustandsbehafteter Kubernetes-Applikationen auf der Basis von NetApp ONTAP Storage-Systemen und der NetApp Trident CSI Storage-bereitstellung verbessert werden.



==== Vorgestellt Werden

* Verbesserte Wiederherstellungszeiten, die die Möglichkeit bieten, häufiger vollständige Sicherungen durchzuführen.
* Verbesserte Granularität der Anwendungsdefinition und selektive Wiederherstellung mit Group-Version-Kind (GVK)-Filterung.
* Effiziente Neusynchronisierung und Rückwärtsreplikation bei Verwendung von AppMirrorRelationship (AMR) mit NetApp SnapMirror, um eine vollständige PVC-Replikation zu vermeiden.
* Möglichkeit hinzugefügt, EKS Pod Identity zum Erstellen von AppVault-Buckets zu verwenden, sodass die Angabe eines Geheimnisses mit den Bucket-Anmeldeinformationen für EKS-Cluster nicht mehr erforderlich ist.
* Die Möglichkeit hinzugefügt, das Wiederherstellen von Beschriftungen und Anmerkungen im Wiederherstellungsnamespace bei Bedarf zu überspringen.
* AppMirrorRelationship (AMR) prüft jetzt, ob eine Quell-PVC-Erweiterung vorliegt und führt bei Bedarf die entsprechende Erweiterung auf dem Ziel-PVC durch.




==== Korrekturen

* Fehler behoben, bei dem Snapshot-Annotationswerte aus früheren Snapshots auf neuere Snapshots angewendet wurden. Alle Snapshot-Annotationen werden jetzt korrekt angewendet.
* Definiert standardmäßig ein Geheimnis für die Data Mover-Verschlüsselung (Kopia/Restic), falls nicht definiert.
* Verbesserte Validierung und Fehlermeldungen für die S3-Appvault-Erstellung hinzugefügt.
* AppMirrorRelationship (AMR) repliziert PVs jetzt nur noch im gebundenen Zustand, um fehlgeschlagene Versuche zu vermeiden.
* Problem behoben, bei dem beim Abrufen von AppVaultContent auf einem AppVault mit einer großen Anzahl von Backups Fehler angezeigt wurden.
* KubeVirt VMSnapshots sind von Wiederherstellungs- und Failover-Vorgängen ausgeschlossen, um Fehler zu vermeiden.
* Problem mit Kopia behoben, bei dem Snapshots vorzeitig entfernt wurden, weil der Standardaufbewahrungsplan von Kopia die vom Benutzer im Zeitplan festgelegten Einstellungen überschrieb.




== Änderungen in 25.02.1



=== Trident



==== Korrekturen

* *Kubernetes*:
+
** Es wurde ein Problem im Trident-Operator behoben, bei dem sidecar-Bildnamen und -Versionen falsch ausgefüllt wurden, wenn eine nicht standardmäßige Bildregistrierung verwendet wurde (link:https://github.com/NetApp/trident/issues/983["Ausgabe #983"]).
** Behebung des Problems, bei dem Multipath-Sitzungen während eines ONTAP Failover Giveback nicht wiederhergestellt werden können (link:https://github.com/NetApp/trident/issues/961["Ausgabe #961"]).






== Änderungen in 25.02

Ab Trident 25.02 enthält die neue Zusammenfassung weitere Informationen zu Verbesserungen, Fixes und Korrekturen für Trident und Trident Protect Versionen.



=== Trident



==== Vorgestellt Werden

* *Kubernetes*:
+
** Zusätzliche Unterstützung für ONTAP ASA r2 für iSCSI.
** Unterstützung für Force-Trennen für ONTAP-NAS-Volumes bei Szenarios zum Herunterfahren eines nicht anmutigen Knotens hinzugefügt. Die neuen ONTAP-NAS-Volumes verwenden jetzt von Trident gemanagte Exportrichtlinien pro Volume. Bereitstellung eines Upgrade-Pfads für vorhandene Volumes, um zu dem neuen Richtlinienmodell für den Export bei einer Veröffentlichung ohne Beeinträchtigung aktiver Workloads zu wechseln
** CloneFromSnapshot-Anmerkung hinzugefügt.
** Zusätzliche Unterstützung für Namespace-übergreifendes Klonen von Volumes.
** Verbesserte iSCSI-Korrektur bei der Selbstheilung, um eine erneute Überprüfung durch exakte Host-, Kanal-, Ziel- und LUN-ID einzuleiten.
** Unterstützung für Kubernetes 1.32 hinzugefügt.


* *OpenShift*:
+
** Unterstützung für die automatische iSCSI-Node-Vorbereitung für RHCOS auf ROSA-Clustern hinzugefügt.
** Unterstützung für OpenShift-Virtualisierung für ONTAP-Treiber hinzugefügt.


* Zusätzliche Fibre-Channel-Unterstützung für ONTAP-SAN-Treiber.
* Unterstützung für NVMe LUKS hinzugefügt.
* Für alle Basisbilder auf ein Scratch-Bild umgeschaltet.
* ISCSI-Verbindungsstatus-Erkennung und Protokollierung hinzugefügt, wenn iSCSI-Sitzungen angemeldet sein sollen, aber nicht (link:https://github.com/NetApp/trident/issues/961["Ausgabe #961"]).
* Zusätzliche Unterstützung für SMB Volumes mit google-Cloud-NetApp-Volumes Treiber.
* Unterstützung hinzugefügt, damit ONTAP Volumes die Wiederherstellungswarteschlange beim Löschen überspringen können.
* Unterstützung zum Überschreiben von Standardbildern mit SHAs anstelle von Tags hinzugefügt.
* Image-Pull-Secrets-Flag zum tridentctl-Installer hinzugefügt.




==== Korrekturen

* *Kubernetes*:
+
** Fehlende Knoten-IP-Adressen aus automatischen Export-Richtlinien () wurden behobenlink:https://github.com/NetApp/trident/issues/965["Ausgabe #965"].
** Automatische Exportrichtlinien wurden für ONTAP-NAS-Economy vorzeitig auf die Richtlinie pro Volume umgeschaltet.
** Die Backend-Konfig-Anmeldeinformationen wurden korrigiert, um alle verfügbaren AWS ARN-Partitionen zu unterstützen (link:https://github.com/NetApp/trident/issues/913["Ausgabe #913"]).
** Option hinzugefügt, um den Auto-Konfigurator-Abgleich im Trident-Operator zu deaktivieren (link:https://github.com/NetApp/trident/issues/924["Ausgabe #924"]).
** Zusätzlicher SicherheitContext für csi-Resizer Container (link:https://github.com/NetApp/trident/issues/976["Ausgabe #976"]).






=== Trident Protect

NetApp Trident Protect bietet erweiterte Funktionen für das Applikations-Datenmanagement, mit denen die Funktionalität und Verfügbarkeit zustandsbehafteter Kubernetes-Applikationen auf der Basis von NetApp ONTAP Storage-Systemen und der NetApp Trident CSI Storage-bereitstellung verbessert werden.



==== Vorgestellt Werden

* Backup- und Restore-Unterstützung für KubeVirt/OpenShift-Virtualisierungs-VMs für Volumes-Modus: Datei- und Volume-Modus: Block (RAW-Gerät)-Storage hinzugefügt. Diese Unterstützung ist mit allen Trident-Treibern kompatibel und erweitert die vorhandenen Schutzfunktionen bei der Replizierung von Speicher mithilfe von NetApp SnapMirror mit Trident Protect.
* Es wurde die Möglichkeit hinzugefügt, das Freeze-Verhalten auf Anwendungsebene für Kubevirt-Umgebungen zu kontrollieren.
* Unterstützung für die Konfiguration von AutoSupport-Proxy-Verbindungen wurde hinzugefügt.
* Es wurde die Möglichkeit hinzugefügt, einen Schlüssel für die Data Mover-Verschlüsselung (Kopia/Restic) zu definieren.
* Es wurde die Möglichkeit hinzugefügt, einen Ausführungshaken manuell auszuführen.
* Es wurde die Möglichkeit hinzugefügt, während der Installation von Trident Protect Sicherheitskontext Constraints (SCCs) zu konfigurieren.
* Unterstützung für die Konfiguration von nodeSelector während der Installation von Trident Protect hinzugefügt.
* Unterstützung für HTTP-/HTTPS-Egress-Proxy für AppVault-Objekte wurde hinzugefügt.
* Erweiterter Ressourcenfilter zum Aktivieren des Ausschlusses von Ressourcen mit Clusterbereich.
* Unterstützung für das AWS-Sitzungs-Token in S3 AppVault-Anmeldedaten wurde hinzugefügt.
* Unterstützung für die Ressourcenerfassung nach Hooks für die Ausführung vor dem Snapshot hinzugefügt.




==== Korrekturen

* Das Management temporärer Volumes wurde verbessert, um die Warteschlange für die ONTAP-Volume-Recovery zu überspringen.
* SCC-Anmerkungen werden nun auf die ursprünglichen Werte zurückgesetzt.
* Höhere Effizienz der Wiederherstellung mit Unterstützung von parallelen Operationen
* Verbesserte Unterstützung für Ausführungshaken-Timeouts für größere Anwendungen.




== Änderungen in 24.10.1



=== Vorgestellt Werden

* *Kubernetes*: Zusätzliche Unterstützung für Kubernetes 1.32.
* ISCSI-Verbindungsstatus-Erkennung und Protokollierung hinzugefügt, wenn iSCSI-Sitzungen angemeldet sein sollen, aber nicht (link:https://github.com/NetApp/trident/issues/961["Ausgabe #961"]).




=== Korrekturen

* Fehlende Knoten-IP-Adressen aus automatischen Export-Richtlinien () wurden behobenlink:https://github.com/NetApp/trident/issues/965["Ausgabe #965"].
* Automatische Exportrichtlinien wurden für ONTAP-NAS-Economy vorzeitig auf die Richtlinie pro Volume umgeschaltet.
* Aktualisierte Abhängigkeiten von Trident und Trident-ASUP für die Adresse CVE-2024-45337 und CVE-2024-45310.
* Logouts für zeitweise fehlerhafte nicht-CHAP-Portale während der iSCSI-Selbstheilung entfernt (link:https://github.com/NetApp/trident/issues/961["Ausgabe #961"]).




== Änderungen in 24.10



=== Vorgestellt Werden

* Google Cloud NetApp Volumes Treiber ist jetzt für NFS-Volumes allgemein verfügbar und unterstützt das zonenbasierte Provisioning.
* Die GCP Workload-Identität wird mit GKE als NetApp-Identität für Google Cloud Volumes verwendet.
* Konfigurationsparameter zu ONTAP-SAN- und ONTAP-SAN-Economy-Treibern hinzugefügt `formatOptions`, um Benutzern die Angabe von LUN-Formatoptionen zu ermöglichen.
* Verringerte Azure NetApp Files-Mindestgröße für ein Volume auf 50 gib. Azure neue Mindestgröße wird voraussichtlich ab November verfügbar sein.
* Konfigurationsparameter hinzugefügt `denyNewVolumePools`, um ONTAP-NAS-Economy- und ONTAP-SAN-Economy-Treiber auf vorhandene FlexVol-Pools zu beschränken.
* Erkennung für das Hinzufügen, Entfernen oder Umbenennen von Aggregaten aus der SVM über alle ONTAP-Treiber hinweg hinzugefügt.
* 18 MiB Overhead wurden zu LUKS-LUNs hinzugefügt, um sicherzustellen, dass die gemeldete PVC-Größe nutzbar ist.
* Verbesserte ONTAP-SAN- und ONTAP-SAN-Economy-Knotenstufe und Entstaunung der Fehlerbehandlung, damit Geräte nach einem Ausfall nicht mehr entfernt werden können.
* Es wurde ein benutzerdefinierter Rollengenerator hinzugefügt, mit dem Kunden eine minimalistische Rolle für Trident in ONTAP erstellen können.
* Zusätzliche Protokollierung für die Fehlerbehebung hinzugefügt `lsscsi` (link:https://github.com/NetApp/trident/issues/792["Ausgabe #792"]).




==== Kubernetes

* Neue Trident-Funktionen für Kubernetes-native Workflows hinzugefügt:
+
** Datensicherung
** Datenmigration
** Disaster Recovery
** Applikationsmobilität
+
link:./trident-protect/learn-about-trident-protect.html["Erfahren Sie mehr über Trident Protect"].



* Eine neue Flagge hinzugefügt `--k8s-api-qps` an Installateure, um den QPS-Wert festzulegen, der von Trident zur Kommunikation mit dem Kubernetes-API-Server verwendet wird.
* Flag zu Installern für das automatische Management von Speicherprotokollabhängigkeiten auf Kubernetes-Cluster-Nodes hinzugefügt `--node-prep`. Kompatibilität mit Amazon Linux 2023 iSCSI Storage-Protokoll getestet und verifiziert
* Unterstützung für Force-Trennen für ONTAP-NAS-Economy-Volumes bei nicht-graziösen Shutdown-Szenarien für Knoten wurde hinzugefügt.
* Neue ONTAP-NAS-Economy NFS-Volumes verwenden bei der Back-End-Option Exportrichtlinien gemäß qtree `autoExportPolicy`. Qtrees werden zum Zeitpunkt der Veröffentlichung nur den Node-restriktiven Exportrichtlinien zugeordnet, um die Zugriffssteuerung und die Sicherheit zu verbessern. Vorhandene qtrees werden auf das neue Exportrichtlinien-Modell umgestellt, wenn Trident das Volume ohne Beeinträchtigung aktiver Workloads von allen Nodes wieder veröffentlicht.
* Unterstützung für Kubernetes 1.31 hinzugefügt.




==== Experimentelle Verbesserungen

* Technische Vorschau für Fibre-Channel-Unterstützung auf ONTAP-SAN-Treiber hinzugefügt




=== Korrekturen

* *Kubernetes*:
+
** Festancher Aufnahme Webhook verhindert Trident Helm Installationen (link:https://github.com/NetApp/trident/issues/839["Ausgabe #839"]).
** Fester Affinitätsschlüssel in Ruderkartenwerten (link:https://github.com/NetApp/trident/issues/898["Ausgabe #898"]).
** Behoben tridentControllerPluginNodeSelector/tridentNodePluginNodeSelector funktioniert nicht mit "true" Wert (link:https://github.com/NetApp/trident/issues/899["Ausgabe #899"]).
** Gelöschte Momentaufnahmen, die während des Klonens erstellt wurden (link:https://github.com/NetApp/trident/issues/901["Ausgabe #901"]).


* Unterstützung für Windows Server 2019 hinzugefügt.
* Behoben `go mod tidy`in Trident repo (link:https://github.com/NetApp/trident/issues/767["Ausgabe #767"]).




=== Abschreibungen

* *Kubernetes:*
+
** Aktualisiertes, mindestens unterstütztes Kubernetes auf 1.25
** Unterstützung für POD-Sicherheitsrichtlinie wurde entfernt.






=== Neubranding von Produkten

Ab Version 24.10 wird Astra Trident unter dem neuen Namen Trident (NetApp Trident) firmiere. Dieses Rebranding hat keine Auswirkungen auf Funktionen, unterstützte Plattformen oder Interoperabilität für Trident.



== Änderungen in 24.06



=== Vorgestellt Werden

* **WICHTIG**: Der `limitVolumeSize` Parameter beschränkt jetzt die qtree/LUN Größen in den ONTAP Economy Treibern. Verwenden Sie den neuen  `limitVolumePoolSize` Parameter, um die FlexVol-Größen in diesen Treibern zu steuern. (link:https://github.com/NetApp/trident/issues/341["Ausgabe #341"]).
* Zusätzliche Möglichkeit für iSCSI Selbstheilung, SCSI-Scans durch exakte LUN-ID zu initiieren, wenn veraltete Initiatorgruppen verwendet werden (link:https://github.com/NetApp/trident/issues/883["Ausgabe #883"]).
* Zusätzliche Unterstützung für Volume-Klonvorgänge und Größenänderungsvorgänge, die zulässig waren, selbst wenn sich das Backend im unterbrochenen Modus befindet.
* Benutzerdefinierte Protokolleinstellungen für den Trident-Controller, die an Trident-Node-Pods weitergegeben werden sollen, wurden hinzugefügt.
* Unterstützung in Trident hinzugefügt, um standardmäßig REST anstelle von ONTAPI (ZAPI) für ONTAP Version 9.15.1 und höher zu verwenden.
* Zusätzliche Unterstützung für benutzerdefinierte Volume-Namen und Metadaten auf den ONTAP Storage-Back-Ends für neue persistente Volumes.
* Erweitert den `azure-netapp-files` (ANF)-Treiber, um das Snapshot-Verzeichnis standardmäßig automatisch zu aktivieren, wenn die NFS-Mount-Optionen auf NFS-Version 4.x eingestellt sind
* Bottlerocket-Unterstützung für NFS-Volumes hinzugefügt.
* Unterstützung für die technische Vorschau von Google Cloud NetApp Volumes hinzugefügt.




==== Kubernetes

* Unterstützung für Kubernetes 1.30 hinzugefügt.
* Zusätzliche Fähigkeit für Trident DemonSet, Zombie-Mounts und Restverfolgungsdateien beim Start zu reinigen (link:https://github.com/NetApp/trident/issues/883["Ausgabe #883"]).
* PVC-Beschriftung für dynamischen Import von LUKS-Volumes ( ) hinzugefügt `trident.netapp.io/luksEncryption`link:https://github.com/NetApp/trident/issues/849["Ausgabe #849"].
* ANF-Treiber wurde um Topologiebewusstsein erweitert.
* Unterstützung für Windows Server 2022-Knoten hinzugefügt.




=== Korrekturen

* Fehler bei der Trident-Installation aufgrund veralteter Transaktionen behoben.
* Tridentctl wurde behoben, um Warnmeldungen von Kubernetes ( ) zu ignorierenlink:https://github.com/NetApp/trident/issues/892["Ausgabe #892"].
* Die Priorität des Trident-Controllers wurde in `0` (link:https://github.com/NetApp/trident/issues/887["Ausgabe #887"]) geändert `SecurityContextConstraint`.
* ONTAP -Treiber akzeptieren jetzt Volume-Größen unter 20 MiB ( link:https://github.com/NetApp/trident/issues/885["Problem[#885"] ).
* Trident wurde korrigiert, um zu verhindern, dass FlexVol Volumes während des Größenänderungsvorgangs für den ONTAP-SAN-Treiber verkleinert werden.
* Fehler beim Import von ANF-Volumes mit NFS v4.1 behoben.




== Änderungen in 24.02



=== Vorgestellt Werden

* Unterstützung für Cloud Identity wurde zugefügt.
+
** AKS mit ANF – Azure Workload Identity wird als Cloud-Identität verwendet.
** EKS mit FSxN – AWS IAM-Rolle wird als Cloud-Identität verwendet.


* Unterstützung für die Installation von Trident als Add-on auf EKS Cluster von der EKS Konsole hinzugefügt.
* Zusätzliche Möglichkeit zum Konfigurieren und Deaktivieren der iSCSI-Selbstheilung (link:https://github.com/NetApp/trident/issues/864["Ausgabe #864"]).
* ONTAP-Treiber wurden um Amazon FSX Personality erweitert, um die Integration mit AWS IAM und SecretsManager zu ermöglichen und Trident zu ermöglichen FSX-Volumes mit Backups zu löschen (link:https://github.com/NetApp/trident/issues/453["Ausgabe #453"]).




==== Kubernetes

* Unterstützung für Kubernetes 1.29 hinzugefügt.




=== Korrekturen

* ACP-Warnmeldungen wurden behoben, wenn ACP nicht aktiviert ist (link:https://github.com/NetApp/trident/issues/866["Ausgabe #866"]).
* Es wurde eine Verzögerung von 10 Sekunden hinzugefügt, bevor eine Klonaufteilung während der Snapshot-Löschung für ONTAP-Treiber durchgeführt wird, wenn ein Klon mit dem Snapshot verknüpft ist.




=== Abschreibungen

* In-toto-Teststationen-Framework aus Multi-Plattform-Image-Manifesten entfernt.




== Änderungen in 23.10



=== Korrekturen

* Feste Volume-Erweiterung, wenn eine neu angeforderte Größe kleiner ist als die gesamte Volume-Größe für ontap-nas und ontap-nas-flexgroup-Storage-Treiber (link:https://github.com/NetApp/trident/issues/834["Ausgabe #834"^]).
* Feste Volume-Größe zur Anzeige nur nutzbarer Größe des Volumes beim Import für ontap-nas und ontap-nas-flexgroup-Storage-Treiber (link:https://github.com/NetApp/trident/issues/722["Ausgabe #722"^]).
* FlexVol Namenskonvertierung für ONTAP-NAS-Economy wurde korrigiert.
* Fehler bei der Trident-Initialisierung auf einem Windows Node wurde beim Neubooten des Node behoben.




=== Vorgestellt Werden



==== Kubernetes

Unterstützung für Kubernetes 1.28 hinzugefügt.



==== Trident

* Unterstützung für die Nutzung von Azure Managed Identities (AMI) mit Azure-netapp-Files Storage-Treibern hinzugefügt.
* Zusätzliche Unterstützung für NVMe over TCP für den ONTAP-SAN-Treiber.
* Zusätzliche Möglichkeit, die Bereitstellung eines Volumes anzuhalten, wenn das Backend vom Benutzer auf „ausgesetzt“ gesetzt wird (link:https://github.com/NetApp/trident/issues/558["Ausgabe #558"^]).




== Änderungen in 23.07.1

*Kubernetes:* Behobene Dämonenlöschung zur Unterstützung von Upgrades ohne Ausfallzeiten (link:https://github.com/NetApp/trident/issues/740["Ausgabe #740"^]).



== Änderungen in 23.07



=== Korrekturen



==== Kubernetes

* Trident Upgrade wurde korrigiert, um alte Pods, die sich im Abschlusszustand befinden, zu ignorieren (link:https://github.com/NetApp/trident/issues/740["Ausgabe #740"^]).
* Tolerierung zur Definition „transient-trident-Version-pod“ hinzugefügt (link:https://github.com/NetApp/trident/issues/795["Ausgabe #795"^]).




==== Trident

* Feste ONTAPI (ZAPI)-Anforderungen, um sicherzustellen, dass die LUN-Seriennummern abgefragt werden, wenn LUN-Attribute zur Identifizierung und Behebung von Ghost-iSCSI-Geräten während der Node-Staging-Vorgänge abgerufen werden.
* Fehlerbehandlung im Speichertreibercode (link:https://github.com/NetApp/trident/issues/816["Ausgabe #816"^]).
* Feste Quota-Größe bei Verwendung von ONTAP-Treibern mit use-Rest=true.
* Erstellung von LUN-Klonen in ontap-san-Economy wurde korrigiert.
* Informationsfeld veröffentlichen von zurücksetzen `rawDevicePath` Bis `devicePath`; Zusätzliche Logik zum Ausfüllen und Wiederherstellen (in einigen Fällen) `devicePath` Feld.




=== Vorgestellt Werden



==== Kubernetes

* Unterstützung für den Import vorbereitgestellter Snapshots wurde hinzugefügt.
* Minimierte Bereitstellung und Dämonset linux-Berechtigungen (link:https://github.com/NetApp/trident/issues/817["Ausgabe #817"^]).




==== Trident

* Es wird kein Statusfeld mehr für „Online“ Volumes und Snapshots gemeldet.
* Aktualisiert den Back-End-Status, wenn das ONTAP-Backend offline ist (link:https://github.com/NetApp/trident/issues/801["Probleme #801"^], link:https://github.com/NetApp/trident/issues/543["#543"^]).
* Die LUN-Seriennummer wird während des Workflows „ControllerVolumePublish“ immer abgerufen und veröffentlicht.
* Zusätzliche Logik zur Überprüfung der Seriennummer und Größe des iSCSI Multipath-Geräts hinzugefügt.
* Zusätzliche Überprüfung für iSCSI-Volumes, um sicherzustellen, dass das richtige Multipath-Gerät nicht bereitgestellt wird.




==== Experimentelle Verbesserung

Unterstützung für NVMe over TCP für den ONTAP-SAN-Treiber wurde um eine technische Vorschau erweitert.



==== Dokumentation

Viele organisatorische und formatierte Verbesserungen wurden vorgenommen.



=== Abschreibungen



==== Kubernetes

* Unterstützung für v1beta1-Snapshots wurde entfernt.
* Unterstützung für Pre-CSI-Volumes und Speicherklassen wurde entfernt.
* Aktualisiertes, mindestens unterstütztes Kubernetes auf 1.22




== Änderungen in 23.04


IMPORTANT: Volume-Trennung für ONTAP-SAN-*-Volumes erzwingen wird nur bei Kubernetes-Versionen mit aktiviertem Non-Graceful Node Shutdown Feature Gate unterstützt. Die Option zum erzwingen der Trennung muss während der Installation mithilfe des aktiviert sein `--enable-force-detach` Flag für das Trident Installationsprogramm.



=== Korrekturen

* Trident-Operator zur Verwendung von IPv6-localhost für die Installation festgelegt, wenn in Spec angegeben.
* Trident Operator Cluster-Rollenberechtigungen wurden festgelegt, um mit den Bundle-Berechtigungen synchronisiert zu werden (link:https://github.com/NetApp/trident/issues/799["Ausgabe #799"^]).
* Problem beim Anhängen von RAW-Block-Volumes auf mehreren Knoten im RWX-Modus behoben.
* Unterstützung von FlexGroup-Klonen und Volume-Import für SMB-Volumes wurde korrigiert.
* Das Problem, dass der Trident Controller nicht sofort heruntergefahren werden konnte, wurde behoben (link:https://github.com/NetApp/trident/issues/811["Ausgabe #811"]).
* Es wurde ein Fix zur Auflistung aller igroup-Namen hinzugefügt, die mit einer angegebenen LUN verbunden sind, die mit ontap-san-* Treibern bereitgestellt wurde.
* Korrektur hinzugefügt, um die Ausführung externer Prozesse bis zum Abschluss zu ermöglichen.
* Kompilierungsfehler für s390-Architektur (link:https://github.com/NetApp/trident/issues/537["Ausgabe #537"]).
* Falsche Protokollierungsebene während der Volume-Mount-Vorgänge (link:https://github.com/NetApp/trident/issues/781["Ausgabe #781"]).
* Fehler bei der Assertion des potenziellen Typs (link:https://github.com/NetApp/trident/issues/802["Ausgabe #802"]).




=== Vorgestellt Werden

* Kubernetes:
+
** Unterstützung für Kubernetes 1.27 hinzugefügt.
** Unterstützung für den Import von LUKS-Volumes wurde hinzugefügt.
** Zusätzliche Unterstützung für den ReadWriteOncePod PVC-Zugriffsmodus.
** Unterstützung für Force-Trennen für ONTAP-SAN-*-Volumes während nicht-Graceful Node Shutdown-Szenarien hinzugefügt.
** Alle ONTAP-SAN-* Volumes verwenden nun Initiatorgruppen pro Node. LUNs werden nur Initiatorgruppen zugeordnet, während sie aktiv auf diesen Nodes veröffentlicht werden, um unsere Sicherheit zu verbessern. Bestehende Volumes werden opportunistisch auf das neue igroup Schema umgestellt, wenn Trident feststellt, dass es sicher ist, dies zu tun, ohne aktive Workloads zu beeinträchtigen (link:https://github.com/NetApp/trident/issues/758["Ausgabe #758"]).
** Verbesserte die Trident-Sicherheit durch Bereinigung nicht genutzter Trident-gemanagter Initiatorgruppen aus ONTAP-SAN-* Back-Ends.


* Zusätzliche Unterstützung für SMB Volumes mit Amazon FSX für die ontap-nas-Wirtschaft und ontap-nas-flexgroup-Storage-Treiber.
* Unterstützung von SMB-Freigaben mit ontap-nas, ontap-nas-Economy und ontap-nas-Flexgroup-Storage-Treibern hinzugefügt.
* Unterstützung für arm64 Knoten (link:https://github.com/NetApp/trident/issues/732["Ausgabe #732"]).
* Verbessertes Trident Shutdown-Verfahren durch Deaktivieren von API-Servern zuerst (link:https://github.com/NetApp/trident/issues/811["Ausgabe #811"]).
* Cross-Plattform-Build-Unterstützung für Windows- und arm64-Hosts zu Makefile hinzugefügt; siehe BUILD.md.




=== Abschreibungen

**Kubernetes:** bei der Konfiguration von ONTAP-san- und ontap-san-Economy-Treibern werden nicht mehr über Back-End-Scoped-Initiatorgruppen erstellt (link:https://github.com/NetApp/trident/issues/758["Ausgabe #758"]).



== Änderungen in 23.01.1



=== Korrekturen

* Trident-Operator zur Verwendung von IPv6-localhost für die Installation festgelegt, wenn in Spec angegeben.
* Die Berechtigungen für die Trident Operator Cluster-Rolle wurden festgelegt, um mit den Bundle-Berechtigungen synchronisiert zu werden link:https://github.com/NetApp/trident/issues/799["Ausgabe #799"^].
* Korrektur hinzugefügt, um die Ausführung externer Prozesse bis zum Abschluss zu ermöglichen.
* Problem beim Anhängen von RAW-Block-Volumes auf mehreren Knoten im RWX-Modus behoben.
* Unterstützung von FlexGroup-Klonen und Volume-Import für SMB-Volumes wurde korrigiert.




== Änderungen in 23.01


IMPORTANT: Kubernetes 1.27 wird jetzt in Trident unterstützt. Führen Sie ein Upgrade von Trident durch, bevor Sie ein Upgrade auf Kubernetes durchführen.



=== Korrekturen

* Kubernetes: Zusätzliche Optionen zum Ausschließen der Pod-Erstellung von Sicherheitsrichtlinien, um Trident-Installationen über Helm ( zu behebenlink:https://github.com/NetApp/trident/issues/794["Ausgaben #783, #794"^]).




=== Vorgestellt Werden

.Kubernetes
* Zusätzliche Unterstützung für Kubernetes 1.26
* Verbesserung der allgemeinen Trident RBAC-Ressourcenauslastung (link:https://github.com/NetApp/trident/issues/757["Ausgabe #757"^]).
* Verbesserte Automatisierung zum Erkennen und Beheben defekter oder veralteter iSCSI Sitzungen auf Host Nodes
* Unterstützung für Erweiterung der LUKS-verschlüsselten Volumes hinzugefügt.
* Kubernetes: Unterstützung für die Rotation von Anmeldeinformationen für LUKS-verschlüsselte Volumes hinzugefügt.


.Trident
* Unterstützung für SMB-Volumes mit Amazon FSX für NetApp ONTAP für den ONTAP-nas-Storage-Treiber hinzugefügt.
* Unterstützung für NTFS-Berechtigungen bei der Verwendung von SMB-Volumes hinzugefügt.
* Zusätzlicher Support für Storage Pools für GCP Volumes mit CVS Service Level.
* Unterstützung für optionale Verwendung von flexgroupAggregateList bei der Erstellung von FlexGroups mit dem ontap-nas-flexgroup Storage-Treiber hinzugefügt.
* Verbesserte Performance für den ONTAP-nas-wirtschaftlichen Speichertreiber beim Management mehrerer FlexVol-Volumes
* Aktivierte Daten-LIF-Updates für alle ONTAP-NAS-Speichertreiber.
* Aktualisierte die Namenskonvention für Trident Deployment und DemonSet zur Berücksichtigung des Host-Node-Betriebssystems.




=== Abschreibungen

* Kubernetes: Aktualisierte die minimal unterstützte Version von Kubernetes auf 1.21.
* DataLIFs sollten beim Konfigurieren von oder `ontap-san-economy` Treibern nicht mehr angegeben werden `ontap-san`.




== Änderungen in 22.10

*Sie müssen die folgenden wichtigen Informationen lesen, bevor Sie auf Trident 22.10 upgraden.*

[WARNING]
.<strong>-Informationen über Trident 22.10 </strong>
====
* Kubernetes 1.25 wird jetzt in Trident unterstützt. Vor dem Upgrade auf Kubernetes 1.25 müssen Sie Trident auf 22.10 aktualisieren.
* Trident setzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, mit einem empfohlenen Wert von `find_multipaths: no` in der Multipath.conf Datei.
+
Verwendung einer Konfiguration ohne Multipathing oder Verwendung von `find_multipaths: yes` Oder `find_multipaths: smart` Der Wert in der Multipath.conf-Datei führt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` Seit der Version 21.07.



====


=== Korrekturen

* Problem wurde speziell mit dem ONTAP Back-End behoben, das mit erstellt wurde `credentials` Feld nicht online während 22.07.0 Upgrade (link:https://github.com/NetApp/trident/issues/759["Ausgabe #759"^]).
* **Docker:** hat ein Problem behoben, das dazu führt, dass das Docker Volume Plugin in einigen Umgebungen nicht startet (link:https://github.com/NetApp/trident/issues/548["Ausgabe #548"^] Und link:https://github.com/NetApp/trident/issues/760["Ausgabe #760"^]).
* SLM-Problem speziell für ONTAP SAN-Back-Ends behoben, um sicherzustellen, dass nur eine Teilmenge der DatenLIFs veröffentlicht werden, die zu Reporting-Nodes gehören.
* Es wurde ein Performance-Problem behoben, bei dem unnötige Scans für iSCSI-LUNs beim Anschließen eines Volumes aufgetreten sind.
* Granulare Wiederholungen im Trident iSCSI Workflow wurden entfernt, um ein schnelles Fehlschlagen zu ermöglichen und externe Wiederholungsintervalle zu verringern.
* Das Problem wurde behoben, bei dem beim Spülen eines iSCSI-Geräts ein Fehler zurückgegeben wurde, als das entsprechende Multipath-Gerät bereits gespült wurde.




=== Vorgestellt Werden

* Kubernetes:
+
** Zusätzliche Unterstützung für Kubernetes 1.25 Vor dem Upgrade auf Kubernetes 1.25 müssen Sie Trident auf 22.10 aktualisieren.
** Hinzufügung eines separaten ServiceAccount, ClusterRole und ClusterBinding für die Trident Deployment und DemonSet, um zukünftige Berechtigungsverbesserungen zu ermöglichen.
** Zusätzlicher Support für link:https://docs.netapp.com/us-en/trident/trident-use/volume-share.html["Namespace-übergreifende Volume-Freigabe"].


* Trident Ist Alles `ontap-*` Storage-Treiber arbeiten jetzt mit der ONTAP REST API.
* Neuer Operator yaml hinzugefügt (`bundle_post_1_25.yaml`) Ohne A `PodSecurityPolicy` Die Kubernetes 1.25 unterstützen.
* Hinzugefügt link:https://docs.netapp.com/us-en/trident/trident-reco/security-luks.html["Unterstützung für LUKS-verschlüsselte Volumes"] Für `ontap-san` Und `ontap-san-economy` Storage-Treiber:
* Unterstützung für Windows Server 2019-Knoten hinzugefügt.
* Hinzugefügt link:https://docs.netapp.com/us-en/trident/trident-use/anf.html["Unterstützung für SMB Volumes auf Windows Nodes"] Durch die `azure-netapp-files` Storage-Treiber:
* Die automatische MetroCluster-Umschalterkennung für ONTAP-Treiber ist jetzt allgemein verfügbar.




=== Abschreibungen

* **Kubernetes:** Aktualisiert unterstützt mindestens Kubernetes auf 1.20.
* Astra Data Store (ADS)-Treiber entfernt.
* Unterstützung für wurde entfernt `yes` Und `smart` Optionen für `find_multipaths` Wenn Sie Multipathing für Worker-Node für iSCSI konfigurieren.




== Änderungen in 22.07



=== Korrekturen

**Kubernetes**

* Problem wurde behoben, um boolesche Werte und Zahlenwerte für die Node-Auswahl bei der Konfiguration von Trident mit Helm oder dem Trident Operator zu behandeln. (link:https://github.com/NetApp/trident/issues/700["GitHub Ausgabe #700"^])
* Problem beim Umgang mit Fehlern aus dem nicht-CHAP-Pfad behoben, sodass kubelet erneut versuchen wird, wenn er fehlschlägt. link:https://github.com/NetApp/trident/issues/736["GitHub Ausgabe #736"^])




=== Vorgestellt Werden

* Übergang von k8s.gcr.io zu Registry.k8s.io als Standard-Registry für CSI-Bilder
* ONTAP-SAN Volumes werden jetzt Initiatorgruppen pro Node verwenden und LUNs nur Initiatorgruppen zuordnen, während diese Nodes aktiv veröffentlicht werden, um unsere Sicherheit zu verbessern. Vorhandene Volumes werden opportun auf das neue igroup-Schema umgeschaltet, wenn Trident feststellt, dass der Einsatz sicher ist, ohne dass aktive Workloads beeinträchtigt werden.
* Enthält eine ResourceQuota mit Trident-Installationen, um sicherzustellen, dass Trident DemonSet geplant ist, wenn die PriorityClass-Nutzung standardmäßig beschränkt ist.
* Unterstützung für Netzwerkfunktionen für den Azure NetApp Files-Treiber hinzugefügt. (link:https://github.com/NetApp/trident/issues/717["GitHub Ausgabe #717"^])
* Technische Vorschau Automatische MetroCluster-Umschalterkennung zu ONTAP-Treibern hinzugefügt. (link:https://github.com/NetApp/trident/issues/228["GitHub Ausgabe #228"^])




=== Abschreibungen

* **Kubernetes:** Aktualisiert unterstützt mindestens Kubernetes auf 1.19.
* Back-End-Konfiguration ermöglicht nicht mehr mehrere Authentifizierungstypen in einer einzigen Konfiguration.




=== Umzüge

* Der AWS CVS-Treiber (veraltet seit 22.04) wurde entfernt.
* Kubernetes
+
** Keine unnötige SYS_ADMIN-Funktion von Node-Pods entfernt.
** Verringert die Nodevorbereitung auf einfache Host-Info und aktive Serviceerkennung, um eine Bestätigung für den bestmöglichen Aufwand zu machen, dass NFS/iSCSI-Dienste auf Worker-Knoten verfügbar sind.






=== Dokumentation

Ein neuer link:https://docs.netapp.com/us-en/trident/trident-reference/pod-security.html["Pod-Sicherheitsstandards"]Abschnitt (PSS) wurde hinzugefügt, in dem die von Trident bei der Installation aktivierten Berechtigungen detailliert aufgeführt sind.



== Änderungen in 22.04

NetApp verbessert seine Produkte und Services kontinuierlich. Im Folgenden finden Sie einige der neuesten Funktionen von Trident. Frühere Versionen finden Sie unter https://docs.netapp.com/us-en/trident/earlier-versions.html["Frühere Versionen der Dokumentation"].


IMPORTANT: Wenn Sie ein Upgrade von früheren Trident Versionen durchführen und Azure NetApp Files verwenden, finden Sie das ``location`` Der Parameter config ist jetzt ein Pflichtfeld, singleton.



=== Korrekturen

* Verbessertes Analysieren von iSCSI-Initiatornamen. (link:https://github.com/NetApp/trident/issues/681["GitHub Ausgabe #681"^])
* Das Problem wurde behoben, bei dem CSI-Speicherklassenparameter nicht zulässig waren. (link:https://github.com/NetApp/trident/issues/598["GitHub Ausgabe #598"^])
* Doppelte Schlüsseldeklaration im Trident CRD behoben. (link:https://github.com/NetApp/trident/issues/671["GitHub Ausgabe #671"^])
* Fehlerhafte CSI-Snapshot-Protokolle wurden korrigiert. (link:https://github.com/NetApp/trident/issues/629["GitHub Ausgabe #629"^]))
* Problem beim Aufheben der Veröffentlichung von Volumes auf gelöschten Nodes behoben. (link:https://github.com/NetApp/trident/issues/691["GitHub Ausgabe #691"^])
* Zusätzliche Bearbeitung von Inkonsistenzen im Dateisystem auf Blockgeräten. (link:https://github.com/NetApp/trident/issues/656["GitHub Ausgabe #656"^])
* Problem beim Ziehen von Bildern mit automatischer Unterstützung beim Einstellen des behoben `imageRegistry` Markierung während der Installation. (link:https://github.com/NetApp/trident/issues/715["GitHub Ausgabe #715"^])
* Es wurde ein Problem behoben, bei dem der Azure NetApp Files-Treiber ein Volume mit mehreren Exportregeln nicht klonen konnte.




=== Vorgestellt Werden

* Eingehende Verbindungen zu den sicheren Endpunkten von Trident erfordern jetzt mindestens TLS 1.3. (link:https://github.com/NetApp/trident/issues/698["GitHub Ausgabe #698"^])
* Trident fügt jetzt HSTS-Header zu den Antworten von seinen sicheren Endpunkten hinzu.
* Trident versucht nun, die Azure NetApp Files unix Berechtigungsfunktion automatisch zu aktivieren.
* *Kubernetes*: Trident Demonset wird jetzt in der Klasse mit System-Node-kritischer Priorität ausgeführt. (link:https://github.com/NetApp/trident/issues/694["GitHub Ausgabe #694"^])




=== Umzüge

E-Series-Treiber (deaktiviert seit 20.07) wurde entfernt.



== Änderungen in 22.01.1



=== Korrekturen

* Problem beim Aufheben der Veröffentlichung von Volumes auf gelöschten Nodes behoben. (link:https://github.com/NetApp/trident/issues/691["GitHub Ausgabe #691"])
* Fester Panik beim Zugriff auf Nil-Felder für den aggregierten Speicherplatz in den ONTAP API Antworten.




== Änderungen in 22.01.0



=== Korrekturen

* *Kubernetes:* Erhöhung der Neuzulassung der Knotenregistrierung für große Cluster.
* Das Problem wurde behoben, bei dem der Azure-netapp-Files Treiber von mehreren Ressourcen mit demselben Namen verwirrt werden konnte.
* ONTAP SAN IPv6 DataLIFs funktionieren jetzt, wenn sie mit Klammern angegeben werden.
* Das Problem wurde behoben, bei dem der Import eines bereits importierten Volumes das EOF zurückgibt, sodass PVC in den ausstehenden Zustand zurückbleibt. (link:https://github.com/NetApp/trident/issues/489["GitHub Ausgabe #489"])
* Das Problem wurde behoben, wenn die Trident Performance langsamer wird, wenn mehr als 32 Snapshots auf einem SolidFire Volume erstellt werden.
* SHA-1 wurde durch SHA-256 bei der Erstellung eines SSL-Zertifikats ersetzt.
* Azure NetApp Files-Treiber wurde behoben, um doppelte Ressourcennamen zu erlauben und Vorgänge auf einen einzelnen Speicherort zu beschränken.
* Azure NetApp Files-Treiber wurde behoben, um doppelte Ressourcennamen zu erlauben und Vorgänge auf einen einzelnen Speicherort zu beschränken.




=== Vorgestellt Werden

* Verbesserungen von Kubernetes:
+
** Zusätzliche Unterstützung für Kubernetes 1.23
** Fügen Sie bei der Installation über Trident Operator oder Helm Planungsoptionen für Trident Pods hinzu. (link:https://github.com/NetApp/trident/issues/651["GitHub Ausgabe #651"^])


* Erlauben Sie regionenübergreifende Volumes im GCP-Treiber. (link:https://github.com/NetApp/trident/issues/633["GitHub Ausgabe #633"^])
* Unterstützung für die Option „unixPermissions“ für Azure NetApp Files Volumes wurde hinzugefügt. (link:https://github.com/NetApp/trident/issues/666["GitHub Ausgabe #666"^])




=== Abschreibungen

Die Trident REST-Schnittstelle kann nur unter 127.0.0.1 oder [: 1] Adressen zuhören und bedient werden



== Änderungen in 21.10.1


WARNING: In der Version v21.10.0 kann der Trident Controller in den CrashLoopBackOff-Status versetzt werden, wenn ein Node entfernt und dann wieder zum Kubernetes Cluster hinzugefügt wird. Dieses Problem wurde in der Version 21,10,1 behoben (GitHub Ausgabe 669).



=== Korrekturen

* Beim Import eines Volumes auf ein GCP CVS Backend wurde eine potenzielle Race-Bedingung behoben, die zu einem Import führt.
* Es wurde ein Problem behoben, durch das der Trident Controller in den CrashLoopBackOff-Status versetzt werden kann, wenn ein Node entfernt und dann wieder zum Kubernetes Cluster hinzugefügt wird (GitHub Ausgabe 669).
* Das Problem wurde behoben, bei dem SVMs nicht mehr erkannt wurden, wenn kein SVM-Name angegeben wurde (GitHub Problem 612).




== Änderungen in 21.10.0



=== Korrekturen

* Es wurde ein Problem behoben, bei dem Klone von XFS-Volumes nicht auf demselben Node wie das Quell-Volume gemountet werden konnten (GitHub Ausgabe 514).
* Problem behoben, bei dem Trident beim Herunterfahren einen schwerwiegenden Fehler protokolliert hat (GitHub Problem 597).
* Kubernetes-bezogene Fixes:
+
** Der verwendete Speicherplatz eines Volume wird als Mindestrückstellunggröße bei der Erstellung von Snapshots mit zurückgegeben `ontap-nas` Und `ontap-nas-flexgroup` Treiber (GitHub Ausgabe 645).
** Problem behoben wo `Failed to expand filesystem` Fehler wurde nach der Volume-Größe protokolliert (GitHub-Problem 560).
** Problem behoben, in dem ein POD feststecken konnte `Terminating` State (GitHub Ausgabe 572).
** Den Fall an der Stelle behoben, an der ein `ontap-san-economy` FlexVol könnte voll von Snapshot-LUNs sein (GitHub Ausgabe 533).
** Problem mit dem benutzerdefinierten YAML-Installationsprogramm mit einem anderen Bild wurde behoben (GitHub Ausgabe 613).
** Berechnung der Snapshot-Größe wurde korrigiert (GitHub Ausgabe 611).
** Es wurde ein Problem behoben, bei dem alle Trident Installer einfaches Kubernetes als OpenShift identifizieren konnten (GitHub Ausgabe 639).
** Der Trident-Operator hat den Abgleich behoben, wenn der Kubernetes-API-Server nicht erreichbar ist (GitHub Ausgabe 599).






=== Vorgestellt Werden

* Zusätzlicher Support für `unixPermissions` Option für GCP-CVS Performance Volumes:
* Zusätzliche Unterstützung für für für Skalierung optimierte CVS Volumes in GCP im Bereich von 600 gib bis 1 tib.
* Verbesserungen im Zusammenhang mit Kubernetes:
+
** Zusätzliche Unterstützung für Kubernetes 1.22
** Trident Operator und Helm Chart wurde für die Verwendung mit Kubernetes 1.22 aktiviert (GitHub Ausgabe 628).
** Bedienerbild zu hinzugefügt `tridentctl` Image-Befehl (GitHub Ausgabe 570).






=== Experimentelle Verbesserungen

* Zusätzliche Unterstützung für Volume-Replikation im `ontap-san` Treiber.
* Zusätzliche *Tech Preview* REST-Unterstützung für die `ontap-nas-flexgroup`, `ontap-san`, und `ontap-nas-economy` Treiber.




== Bekannte Probleme

Bekannte Probleme erkennen Probleme, die eine erfolgreiche Verwendung des Produkts verhindern könnten.

* Wenn Sie ein Kubernetes-Cluster von 1.24 auf 1.25 oder höher aktualisieren, auf dem Trident installiert ist, müssen Sie values.yaml aktualisieren, um den `helm upgrade` Befehl auf `true` festzulegen `excludePodSecurityPolicy` oder hinzuzufügen `--set excludePodSecurityPolicy=true`, bevor Sie das Cluster aktualisieren können.
* Trident erzwingt jetzt ein Leerzeichen `fsType` (`fsType=""`) für Volumes, die nicht die in ihrer StorageClass angegebene haben `fsType`. Bei der Arbeit mit Kubernetes 1.17 oder höher unterstützt Trident die Bereitstellung eines Leereinschübe `fsType` für NFS-Volumes. Für iSCSI-Volumes müssen Sie die auf Ihrer StorageClass festlegen, wenn Sie `fsType` einen mit einem Sicherheitskontext erzwingen `fsGroup`.
* Wenn Sie ein Back-End über mehrere Trident Instanzen hinweg verwenden, sollte jede Back-End-Konfigurationsdatei einen anderen Wert für ONTAP Back-Ends haben `storagePrefix` oder einen anderen für SolidFire Back-Ends verwenden `TenantName`. Trident kann Volumes nicht erkennen, die von anderen Instanzen von Trident erstellt wurden. Der Versuch, ein vorhandenes Volume auf ONTAP oder SolidFire Back-Ends zu erstellen, ist erfolgreich, da Trident die Volume-Erstellung als einen idempotenten Vorgang behandelt. Wenn `storagePrefix` sich die Volumes unterscheiden oder `TenantName` nicht, kann es zu Namenskollisionen für Volumes kommen, die auf demselben Backend erstellt wurden.
* Bei der Installation von Trident (mit `tridentctl` oder dem Trident Operator) und der Verwendung von `tridentctl` zum Verwalten von Trident sollten Sie sicherstellen, dass die `KUBECONFIG` Umgebungsvariable eingestellt ist. Dies ist notwendig, um den Kubernetes-Cluster anzugeben, der `tridentctl` gegen den eingesetzt werden soll. Wenn Sie mit mehreren Kubernetes-Umgebungen arbeiten, sollten Sie sicherstellen, dass die `KUBECONFIG` Datei korrekt bezogen wird.
* Um Online-Speicherplatzrückgewinnung für iSCSI PVS durchzuführen, muss das zugrunde liegende Betriebssystem auf dem Worker-Node möglicherweise Mount-Optionen an das Volume übergeben werden. Dies gilt für RHEL/Red hat Enterprise Linux CoreOS (RHCOS)-Instanzen, die den;-Wert benötigen `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Mount-Option"^], um Online-Blockverwerfen zu unterstützen. Stellen Sie sicher, dass die verwerfen mountOption in Ihrem^] enthalten[`StorageClass` ist.
* Wenn Sie mehr als eine Instanz von Trident pro Kubernetes-Cluster haben, kann Trident nicht mit anderen Instanzen kommunizieren und keine anderen Volumes erkennen, die sie erstellt haben. Dies führt zu unerwartetem und falschem Verhalten, wenn mehr als eine Instanz in einem Cluster ausgeführt wird. Pro Kubernetes-Cluster sollte es nur eine Instanz von Trident geben.
* Wenn Trident-basierte `StorageClass` Objekte aus Kubernetes gelöscht werden, während Trident offline ist, entfernt Trident die entsprechenden Storage-Klassen nicht aus seiner Datenbank, wenn sie wieder online geschaltet werden. Sie sollten diese Speicherklassen mit oder der REST-API löschen `tridentctl`.
* Wenn ein Benutzer ein von Trident bereitgestelltes PV löscht, bevor die entsprechende PVC gelöscht wird, löscht Trident nicht automatisch das Back-Volume. Sie sollten das Volume über die REST-API entfernen `tridentctl`.
* ONTAP kann nicht gleichzeitig mehr als ein FlexGroup gleichzeitig bereitstellen, es sei denn, der Satz der Aggregate ist auf jede Bereitstellungsanforderung beschränkt.
* Wenn Sie Trident über IPv6 verwenden, sollten Sie und `dataLIF` in der Backend-Definition in eckigen Klammern angeben `managementLIF`. ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``Beispiel: .
+

NOTE: Sie können die Angabe auf einem ONTAP-SAN-Backend nicht `dataLIF` machen. Trident erkennt alle verfügbaren iSCSI LIFs und verwendet diese zur Einrichtung der Multipath-Sitzung.

* Wenn Sie das verwenden `solidfire-san` Treiber mit OpenShift 4.5, stellen Sie sicher, dass die zugrunde liegenden Worker-Knoten MD5 als CHAP-Authentifizierungsalgorithmus verwenden. Sichere, FIPS-konforme CHAP-Algorithmen SHA1, SHA-256 und SHA3-256 sind mit Element 12.7 erhältlich.




== Weitere Informationen

* https://github.com/NetApp/trident["Trident GitHub"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Trident Blogs"^]

