---
sidebar: sidebar 
permalink: trident-use/backends.html 
keywords: backends, storage system, anf, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, fsx 
summary: Ein Backend definiert die Beziehung zwischen Trident und einem Storage-System. Er erzählt Trident, wie man mit diesem Storage-System kommuniziert und wie Trident Volumes daraus bereitstellen sollte. 
---
= Back-Ends konfigurieren
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Backend definiert die Beziehung zwischen Trident und einem Storage-System. Er erzählt Trident, wie man mit diesem Storage-System kommuniziert und wie Trident Volumes daraus bereitstellen sollte.

Trident bietet automatisch Back-Ends-Storage-Pools an, die den von einer Storage-Klasse definierten Anforderungen entsprechen. Erfahren Sie, wie Sie das Backend für Ihr Storage-System konfigurieren.

* link:anf.html["Konfigurieren Sie ein Azure NetApp Files-Backend"^]
* link:gcnv.html["Google Cloud NetApp Volumes-Back-End konfigurieren"^]
* link:gcp.html["Konfigurieren Sie ein Back-End für Cloud Volumes Service für Google Cloud Platform"^]
* link:element.html["Konfigurieren Sie ein NetApp HCI- oder SolidFire-Backend"^]
* link:ontap-nas.html["Konfigurieren Sie ein Backend mit ONTAP- oder Cloud Volumes ONTAP-NAS-Treibern"^]
* link:ontap-san.html["Konfigurieren Sie ein Backend mit ONTAP- oder Cloud Volumes ONTAP-SAN-Treibern"^]
* link:trident-fsx.html["Verwenden Sie Trident mit Amazon FSX für NetApp ONTAP"^]

