---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Erfahren Sie mehr über die Konfiguration eines ONTAP-Backends mit ONTAP-SAN-Treibern. 
---
= Übersicht über ONTAP SAN-Treiber
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Konfiguration eines ONTAP Backend mit ONTAP- und Cloud Volumes ONTAP-SAN-Treibern.



== Details zum ONTAP-SAN-Treiber

Trident stellt die folgenden SAN-Speichertreiber für die Kommunikation mit dem ONTAP-Cluster bereit. Unterstützte Zugriffsmodi sind: _ReadWriteOnce_ (RWO), _ReadOnly Many_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Treiber | Protokoll | VolumeModus | Unterstützte Zugriffsmodi | Unterstützte Filesysteme 


| `ontap-san`  a| 
ISCSI SCSI über FC
 a| 
Block-Storage
 a| 
RWO, ROX, RWX, RWOP
 a| 
Kein Filesystem, rohes Block-Gerät



| `ontap-san`  a| 
ISCSI SCSI über FC
 a| 
Dateisystem
 a| 
RWO, RWOP

ROX und RWX sind im Filesystem-Volume-Modus nicht verfügbar.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san`  a| 
NVMe/TCP

Siehe <<Weitere Überlegungen zu NVMe/TCP>>.
 a| 
Block-Storage
 a| 
RWO, ROX, RWX, RWOP
 a| 
Kein Filesystem, rohes Block-Gerät



| `ontap-san`  a| 
NVMe/TCP

Siehe <<Weitere Überlegungen zu NVMe/TCP>>.
 a| 
Dateisystem
 a| 
RWO, RWOP

ROX und RWX sind im Filesystem-Volume-Modus nicht verfügbar.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Block-Storage
 a| 
RWO, ROX, RWX, RWOP
 a| 
Kein Filesystem, rohes Block-Gerät



| `ontap-san-economy`  a| 
ISCSI
 a| 
Dateisystem
 a| 
RWO, RWOP

ROX und RWX sind im Filesystem-Volume-Modus nicht verfügbar.
 a| 
`xfs`, `ext3`, `ext4`

|===
[WARNING]
====
* Nutzung `ontap-san-economy` Nur wenn die Nutzungszahl für persistente Volumes voraussichtlich höher ist als link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Unterstützte ONTAP-Volume-Größen"^].
* Nutzung `ontap-nas-economy` Nur wenn die Nutzungszahl für persistente Volumes voraussichtlich höher ist als link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Unterstützte ONTAP-Volume-Größen"^] Und das `ontap-san-economy` Treiber kann nicht verwendet werden.
* Verwenden Sie ihn nicht `ontap-nas-economy` Wenn Sie die Notwendigkeit von Datensicherung, Disaster Recovery oder Mobilität erwarten.
* NetApp empfiehlt nicht die Verwendung von FlexVol Autogrow in allen ONTAP-Treibern außer ONTAP-san. Als Workaround unterstützt Trident die Verwendung von Snapshot-Reserve und skaliert FlexVol-Volumen entsprechend.


====


== Benutzerberechtigungen

Trident geht davon aus, dass es entweder als ONTAP- oder SVM-Administrator ausgeführt wird, wobei der Cluster-Benutzer oder ein `vsadmin` SVM-Benutzer oder ein Benutzer mit einem anderen Namen und derselben Rolle verwendet `admin` wird. Bei Implementierungen von Amazon FSX for NetApp ONTAP rechnet Trident damit, als ONTAP- oder SVM-Administrator ausgeführt zu werden. Dabei verwendet er den Cluster- `fsxadmin`Benutzer, einen `vsadmin` SVM-Benutzer oder einen Benutzer mit einem anderen Namen mit derselben Rolle. Der `fsxadmin` Benutzer ist ein eingeschränkter Ersatz für den Cluster-Admin-Benutzer.


NOTE: Wenn Sie den Parameter verwenden `limitAggregateUsage`, sind Administratorberechtigungen für den Cluster erforderlich. Wenn Amazon FSX for NetApp ONTAP mit Trident verwendet wird, funktioniert der `limitAggregateUsage` Parameter nicht mit den `vsadmin` Benutzerkonten und `fsxadmin`. Der Konfigurationsvorgang schlägt fehl, wenn Sie diesen Parameter angeben.

Es ist zwar möglich, eine restriktivere Rolle in ONTAP zu erstellen, die ein Trident-Treiber verwenden kann, wir empfehlen sie jedoch nicht. Bei den meisten neuen Versionen von Trident sind zusätzliche APIs erforderlich, die berücksichtigt werden müssten, was Upgrades schwierig und fehleranfällig macht.



== Weitere Überlegungen zu NVMe/TCP

Trident unterstützt das NVMe-Protokoll (Non-Volatile Memory Express) unter Verwendung des `ontap-san` Treibers, einschließlich:

* IPv6
* Snapshots und Klone von NVMe Volumes
* Größe eines NVMe Volumes ändern
* Importieren eines NVMe Volumes, das außerhalb von Trident erstellt wurde, damit sein Lebenszyklus durch Trident gemanagt werden kann
* NVMe-natives Multipathing
* Ordnungsgemäßes oder unzumutbar Herunterfahren der K8s-Nodes (24.06)


Trident unterstützt Folgendes nicht:

* Dh-HMAC-CHAP, das von nativ von NVMe unterstützt wird
* Multipathing für Device Mapper (DM
* LUKS-Verschlüsselung

