---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Durch den Einsatz von Trident mit Amazon FSX for NetApp ONTAP kann sichergestellt werden, dass Ihre Kubernetes-Cluster, die im Amazon Elastic Kubernetes Service (EKS) ausgeführt werden, persistente Block- und dateibasierte Volumes mit ONTAP bereitstellen können.' 
---
= Installation Von Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident optimiert das Amazon FSX für NetApp ONTAP Storage-Management in Kubernetes, damit sich Ihre Entwickler und Administratoren voll und ganz auf den Applikationseinsatz konzentrieren können.

Sie können Trident mit einer der folgenden Methoden installieren:

* Helm
* EKS-Add-on


Wenn Sie die Snapshot-Funktionalität nutzen möchten, installieren Sie das Add-On für den CSI-Snapshot-Controller. Weitere Informationen finden Sie unter link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Snapshot-Funktionalität für CSI-Volumes aktivieren"^] .



== Trident über Helm installieren

. Laden Sie das Trident-Installationspaket herunter
+
Das Trident-Installationspaket enthält alles, was Sie für die Bereitstellung des Trident-Bedieners und die Installation von Trident benötigen. Laden Sie die neueste Version des Trident-Installers herunter und extrahieren Sie sie aus dem Abschnitt „Assets“ auf GitHub.

+
[source, console]
----
wget https://github.com/NetApp/trident/releases/download/v25.02.0/trident-installer-25.02.0.tar.gz
tar -xf trident-installer-25.02.0.tar.gz
cd trident-installer
----
. Legen Sie die Werte für *Cloud Provider* und *Cloud Identity* unter Verwendung der folgenden Umgebungsvariablen fest:
+
Das folgende Beispiel installiert Trident und setzt das `cloud-provider` Flag auf `$CP`, und `cloud-identity` auf `$CI`:

+
[source, console]
----
helm install trident trident-operator-100.2502.0.tgz \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
Mit dem Befehl können `helm list` Sie Installationsdetails wie Name, Namespace, Diagramm, Status, App-Version und Revisionsnummer überprüfen.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----




== Installieren Sie Trident über das EKS-Add-on

Das Trident EKS Add-on enthält die neuesten Sicherheitspatches und Bug Fixes. Es wurde von AWS für die Zusammenarbeit mit Amazon EKS validiert. Mit dem EKS-Add-on können Sie sicherstellen, dass Ihre Amazon EKS-Cluster sicher und stabil sind und den Arbeitsaufwand für die Installation, Konfiguration und Aktualisierung von Add-Ons verringern.



=== Voraussetzungen

Stellen Sie sicher, dass folgende Voraussetzungen erfüllt sind, bevor Sie das Trident Add-on für AWS EKS konfigurieren:

* Ein Amazon EKS Cluster-Konto mit Add-on-Abonnement
* AWS Berechtigungen für den AWS Marketplace:
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* AMI-Typ: Amazon Linux 2 (AL2_x86_64) oder Amazon Linux 2 Arm(AL2_ARM_64)
* Knotentyp: AMD oder ARM
* Ein bestehendes Amazon FSX für NetApp ONTAP-Filesystem




=== Aktivieren Sie das Trident Add-on für AWS

[role="tabbed-block"]
====
.Eksctl
--
Mit dem folgenden Beispielbefehl wird das Trident EKS Add-On installiert:

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> \
--service-account-role-arn arn:aws:iam::<account_id>:role/<role_name> --force
----
--
.Management-Konsole
--
. Öffnen Sie die Amazon EKS Konsole unter https://console.aws.amazon.com/eks/home#/clusters[].
. Wählen Sie im linken Navigationsbereich *Cluster* aus.
. Wählen Sie den Namen des Clusters aus, für den Sie das NetApp Trident-CSI-Add-On konfigurieren möchten.
. Wählen Sie *Add-ons* und dann *Weitere Add-Ons*.
. Gehen Sie auf der Seite *Add-ons auswählen* wie folgt vor:
+
.. Aktivieren Sie im Abschnitt EKS-Addons des AWS Marketplace das Kontrollkästchen *Trident by NetApp*.
.. Wählen Sie *Weiter*.


. Gehen Sie auf der Seite *Ausgewählte Add-Ons konfigurieren*-Einstellungen wie folgt vor:
+
.. Wählen Sie die *Version* aus, die Sie verwenden möchten.
.. Für *IAM-Rolle auswählen* lassen Sie bei *nicht gesetzt*.
.. Folgen Sie dem *Add-on-Konfigurationsschema* und setzen Sie den Parameter configurationValues im Abschnitt *Konfigurationswerte* auf die Rolle-arn, die Sie im vorherigen Schritt erstellt haben (Wert sollte im folgenden Format sein:
+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'"

}
----
+
Wenn Sie für die Konfliktlösungsmethode Überschreiben auswählen, können eine oder mehrere Einstellungen für das vorhandene Add-On mit den Amazon EKS-Zusatzeinstellungen überschrieben werden. Wenn Sie diese Option nicht aktivieren und es einen Konflikt mit Ihren bestehenden Einstellungen gibt, schlägt der Vorgang fehl. Sie können die resultierende Fehlermeldung verwenden, um den Konflikt zu beheben. Bevor Sie diese Option auswählen, stellen Sie sicher, dass das Amazon EKS-Add-On keine Einstellungen verwaltet, die Sie selbst verwalten müssen.



. Wählen Sie *Weiter*.
. Wählen Sie auf der Seite *Überprüfen und Hinzufügen* *Erstellen*.
+
Nachdem die Installation des Add-ons abgeschlossen ist, wird das installierte Add-on angezeigt.



--
.AWS CLI
--
. Erstellen Sie die `add-on.json` Datei:
+
[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.02.1-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----
+

NOTE: Ersetzen Sie `<role ARN>` diese durch die ARN der Rolle, die im vorherigen Schritt erstellt wurde.

. Installieren Sie das Trident EKS-Add-On.
+
[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----


--
====


=== Aktualisieren Sie das Trident EKS-Add-On

[role="tabbed-block"]
====
.Eksctl
--
* Überprüfen Sie die aktuelle Version des FSxN Trident CSI-Add-ons. Ersetzen Sie `my-cluster` den Cluster-Namen.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Beispielausgabe:*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.02.1-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Aktualisieren Sie das Add-on auf die Version, DIE unter UPDATE zurückgegeben wurde, DIE in der Ausgabe des vorherigen Schritts VERFÜGBAR ist.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.02.1-eksbuild.1 --cluster my-cluster --force
----


Wenn Sie die Option entfernen `--force` und eine der Amazon EKS-Zusatzeinstellungen mit Ihren vorhandenen Einstellungen in Konflikt steht, schlägt die Aktualisierung des Amazon EKS-Zusatzes fehl. Sie erhalten eine Fehlermeldung, um den Konflikt zu beheben. Bevor Sie diese Option angeben, stellen Sie sicher, dass das Amazon EKS-Add-On keine Einstellungen verwaltet, die Sie verwalten müssen, da diese Einstellungen mit dieser Option überschrieben werden. Weitere Informationen zu anderen Optionen für diese Einstellung finden Sie unter link:https://eksctl.io/usage/addons/["Add-Ons"]. Weitere Informationen zum Field Management von Amazon EKS Kubernetes finden Sie unter link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Außendienstmanagement von Kubernetes"].

--
.Management-Konsole
--
. Öffnen Sie die Amazon EKS Konsole https://console.aws.amazon.com/eks/home#/clusters[].
. Wählen Sie im linken Navigationsbereich *Cluster* aus.
. Wählen Sie den Namen des Clusters aus, für den Sie das NetApp Trident-CSI-Add-On aktualisieren möchten.
. Wählen Sie die Registerkarte *Add-ons*.
. Wählen Sie *Trident by NetApp* und dann *Bearbeiten*.
. Gehen Sie auf der Seite *Configure Trident by NetApp* wie folgt vor:
+
.. Wählen Sie die *Version* aus, die Sie verwenden möchten.
.. Erweitern Sie die *Optionale Konfigurationseinstellungen* und ändern Sie sie nach Bedarf.
.. Wählen Sie *Änderungen speichern*.




--
.AWS CLI
--
Im folgenden Beispiel wird das EKS-Add-on aktualisiert:

[source, console]
----
aws eks update-addon --cluster-name my-cluster netapp_trident-operator vpc-cni --addon-version v25.02.1-eksbuild.1 \
    --service-account-role-arn <role-ARN> --configuration-values '{}' --resolve-conflicts --preserve
----
--
====


=== Deinstallieren Sie das Trident EKS-Add-On bzw. entfernen Sie es

Sie haben zwei Optionen zum Entfernen eines Amazon EKS-Add-ons:

* *Add-on-Software auf Ihrem Cluster beibehalten* – Diese Option entfernt die Amazon EKS-Verwaltung aller Einstellungen. Amazon EKS kann Sie auch nicht mehr über Updates informieren und das Amazon EKS-Add-On automatisch aktualisieren, nachdem Sie ein Update gestartet haben. Die Add-on-Software auf dem Cluster bleibt jedoch erhalten. Mit dieser Option wird das Add-On zu einer selbstverwalteten Installation anstatt zu einem Amazon EKS-Add-on. Bei dieser Option haben Add-on keine Ausfallzeiten. Behalten Sie die Option im Befehl bei `--preserve` , um das Add-on beizubehalten.
* *Entfernen Sie Add-on-Software komplett aus Ihrem Cluster* – NetApp empfiehlt, das Amazon EKS-Add-on nur dann aus Ihrem Cluster zu entfernen, wenn es keine Ressourcen auf Ihrem Cluster gibt, die davon abhängen. Entfernen Sie die `--preserve` Option aus dem `delete` Befehl, um das Add-On zu entfernen.



NOTE: Wenn dem Add-On ein IAM-Konto zugeordnet ist, wird das IAM-Konto nicht entfernt.

[role="tabbed-block"]
====
.Eksctl
--
Mit dem folgenden Befehl wird das Trident EKS-Add-On deinstalliert:

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
.Management-Konsole
--
. Öffnen Sie die Amazon EKS Konsole unter https://console.aws.amazon.com/eks/home#/clusters[].
. Wählen Sie im linken Navigationsbereich *Cluster* aus.
. Wählen Sie den Namen des Clusters aus, für den Sie das NetApp Trident CSI-Add-On entfernen möchten.
. Wählen Sie die Registerkarte *Add-ons* und dann *Trident by NetApp*.*
. Wählen Sie *Entfernen*.
. Gehen Sie im Dialogfeld *Remove netapp_Trident-Operator confirmation* wie folgt vor:
+
.. Wenn Amazon EKS die Verwaltung der Einstellungen für das Add-On einstellen soll, wählen Sie *auf Cluster beibehalten* aus. Führen Sie diese Option aus, wenn Sie die Add-on-Software auf dem Cluster beibehalten möchten, damit Sie alle Einstellungen des Add-ons selbst verwalten können.
.. Geben Sie *netapp_Trident-Operator* ein.
.. Wählen Sie *Entfernen*.




--
.AWS CLI
--
Ersetzen `my-cluster` Sie den Namen des Clusters, und führen Sie dann den folgenden Befehl aus.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
====