---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy.html 
keywords: deploy, Trident, methods, operator, tridentctl, helm, tanzu, vmware 
summary: 'Sie können Trident mit dem Trident-Operator (manuell oder mit Helm) oder mit installieren `tridentctl`. In diesem Thema finden Sie wichtige Informationen zur Auswahl des richtigen Installationsprozesses.' 
---
= Erfahren Sie mehr über die Trident Installation
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um sicherzustellen, dass Trident in einer Vielzahl von Umgebungen und Organisationen installiert werden kann, bietet NetApp verschiedene Installationsoptionen. Sie können Trident mit dem Trident-Operator (manuell oder mit Helm) oder mit installieren `tridentctl`. In diesem Thema finden Sie wichtige Informationen zur Auswahl des richtigen Installationsprozesses.



== Wichtige Informationen zu Trident 24.06

*Sie müssen die folgenden wichtigen Informationen über Trident lesen.*

.<strong>-Informationen über Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.32 wird jetzt in Trident unterstützt. Upgrade von Trident vor dem Upgrade von Kubernetes.
* Trident setzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, wobei der empfohlene Wert `find_multipaths: no` in der Multipath.conf Datei verwendet wird.
+
Verwendung einer Konfiguration ohne Multipathing oder Verwendung von `find_multipaths: yes` Oder `find_multipaths: smart` Der Wert in der Multipath.conf-Datei führt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` Seit der Version 21.07.



=====
====


== Bevor Sie beginnen

Unabhängig von Ihrem Installationspfad müssen Sie Folgendes haben:

* Vollständige Berechtigungen für einen unterstützten Kubernetes-Cluster, auf dem eine unterstützte Version von Kubernetes und aktivierte Funktionsanforderungen ausgeführt werden. Überprüfen Sie die link:requirements.html["Anforderungen"] Entsprechende Details.
* Zugriff auf ein unterstütztes NetApp Storage-System.
* Kann Volumes von allen Kubernetes Worker-Nodes aus mounten
* Einem Linux-Host mit `kubectl` (Oder `oc`, Falls Sie OpenShift nutzen) ist installiert und konfiguriert, um den Kubernetes-Cluster zu managen, den Sie verwenden möchten.
* Der `KUBECONFIG` Umgebungsvariable auf die Kubernetes-Cluster-Konfiguration verweisen.
* Bei Verwendung von Kubernetes mit Docker Enterprise https://docs.docker.com/ee/ucp/user-access/cli/["Führen Sie die entsprechenden Schritte aus, um den CLI-Zugriff zu aktivieren"^].



TIP: Wenn Sie sich nicht mit dem vertraut gemacht haben link:../trident-concepts/intro.html["Grundkonzepte"^], Ist jetzt eine tolle Zeit, um das zu tun.



== Wählen Sie Ihre Installationsmethode

Wählen Sie die für Sie richtige Installationsmethode aus. Sie sollten auch die Überlegungen zu prüfen link:kubernetes-deploy.html#move-between-installation-methods["Bewegen zwischen Methoden"] Bevor Sie Ihre Entscheidung treffen.



=== Verwenden des Betreibers von Trident

Egal, ob Sie sie manuell bereitstellen oder mithilfe von Helm arbeiten – der Trident Operator ist eine hervorragende Möglichkeit, die Installation zu vereinfachen und Trident-Ressourcen dynamisch zu managen. Sie können sogar link:../trident-get-started/kubernetes-customize-deploy.html["Individuelle Anpassung der Trident Implementierung"]die Attribute in der benutzerdefinierten Ressource (CR) verwenden `TridentOrchestrator`.

Die Vorteile der Verwendung des Trident-Mitarbeiters:

.<strong> Trident-Objekt </strong>
[%collapsible]
====
Der Trident Operator erstellt automatisch die folgenden Objekte für Ihre Kubernetes-Version.

* Servicekonto für den Betreiber
* ClusterRole und ClusterRoleBinding an das ServiceAccount
* Dedizierte PodSecurityPolicy (für Kubernetes 1.25 und früher)
* Der Bediener selbst


====
.<strong>-</strong>
[%collapsible]
====
Der Trident-Operator mit Cluster-Umfang verwaltet Ressourcen, die einer Trident-Installation auf Cluster-Ebene zugeordnet sind. Dies reduziert Fehler, die bei der Verwaltung von Clusterressourcen mit einem Namespace-Scoped-Operator auftreten können. Dies ist wichtig für die Selbstheilung und das Patching.

====
.<strong> Verheilen cappecackeIT </strong>
[%collapsible]
====
Der Bediener überwacht die Trident-Installation und ergreift aktiv Maßnahmen, um Probleme zu beheben, z. B. wenn die Bereitstellung gelöscht wird oder versehentlich geändert wird. Es wird ein `trident-operator-<generated-id>` Pod erstellt, der ein CR mit einer Trident-Installation verknüpft `TridentOrchestrator`. Dadurch wird sichergestellt, dass nur eine Instanz von Trident im Cluster vorhanden ist und das Setup kontrolliert wird, um sicherzustellen, dass die Installation idempotent ist. Wenn Änderungen an der Installation vorgenommen werden (z. B. Löschen der Bereitstellung oder Knotendemonsatz), identifiziert der Bediener diese und korrigiert sie einzeln.

====
.<strong> Vermittlhat Updates für vorhandene InstalleIT </strong>
[%collapsible]
====
Sie können eine vorhandene Implementierung einfach mit dem Bediener aktualisieren. Sie müssen nur die bearbeiten `TridentOrchestrator` CR, um Aktualisierungen für eine Installation durchzuführen.

Stellen Sie sich beispielsweise ein Szenario vor, in dem Sie Trident aktivieren müssen, um Debug-Protokolle zu generieren. Um dies zu `spec.debug` tun, patchen Sie Ihre `TridentOrchestrator` auf `true`:

[listing]
----
kubectl patch torc <trident-orchestrator-name> -n trident --type=merge -p '{"spec":{"debug":true}}'
----
Nachher `TridentOrchestrator` Wird aktualisiert, verarbeitet der Bediener die Updates und Patches für die vorhandene Installation. Dies kann dazu führen, dass neue Pods erstellt werden, um die Installation entsprechend zu ändern.

====
.<strong> Retinstallbeam </strong>
[%collapsible]
====
Der im Cluster enthaltene Trident Operator ermöglicht die saubere Entfernung von im Cluster-Umfang enthaltenen Ressourcen. Benutzer können Trident vollständig deinstallieren und einfach neu installieren.

====
.<strong> </strong> für Kubernetes Upgrade
[%collapsible]
====
Wenn die Kubernetes-Version des Clusters auf eine unterstützte Version aktualisiert wird, aktualisiert der Betreiber automatisch eine vorhandene Trident-Installation und ändert diese, um sicherzustellen, dass sie die Anforderungen der Kubernetes-Version erfüllt.


NOTE: Wenn das Cluster auf eine nicht unterstützte Version aktualisiert wird, verhindert der Bediener die Installation von Trident. Wenn Trident bereits zusammen mit dem Bediener installiert wurde, wird eine Warnung angezeigt, die anzeigt, dass Trident auf einer nicht unterstützten Kubernetes-Version installiert ist.

====


=== Wird Verwendet `tridentctl`

Wenn Sie eine vorhandene Bereitstellung haben, die aktualisiert werden muss, oder wenn Sie Ihre Bereitstellung stark anpassen möchten, sollten Sie dies in Betracht ziehen. Dies ist die konventionelle Methode zur Bereitstellung von Trident.

Die Manifeste für Trident-Ressourcen werden generiert. Dazu gehören die Bereitstellung, das Dämonset, das Dienstkonto und die Clusterrolle, die Trident im Rahmen seiner Installation erstellt.


NOTE: Ab der Version 22.04 werden AES-Schlüssel nicht mehr bei jeder Installation von Trident neu generiert. Mit dieser Version installiert Trident ein neues geheimes Objekt, das in allen Installationen fortbesteht. Dies bedeutet, `tridentctl` dass in 22.04 frühere Versionen von Trident deinstalliert werden können, aber frühere Versionen können 22.04-Installationen nicht deinstallieren. Wählen Sie die entsprechende Installation_method_ aus.



== Wählen Sie den Installationsmodus aus

Bestimmen Sie Ihren Bereitstellungsprozess auf der Grundlage des von Ihrem Unternehmen benötigten _Installations-Modus_ (Standard, Offline oder Remote).

[role="tabbed-block"]
====
.Standardinstallation
--
Dies ist der einfachste Weg, Trident zu installieren und funktioniert für die meisten Umgebungen, die keine Netzwerkeinschränkungen auferlegen. Standard-Installationsmodus verwendet Standardregistrierungen, um erforderliche Trident (`docker.io`) und CSI (`registry.k8s.io`) Bilder zu speichern.

Wenn Sie den Standardmodus verwenden, führt das Trident-Installationsprogramm folgende Schritte aus:

* Ruft die Container-Images über das Internet ab
* Erstellt ein Deployment- oder Node-Dämonset, das Trident-Pods auf allen infrage kommenden Nodes im Kubernetes-Cluster hochfährt


--
.Offline-Installation
--
Der Offline-Installationsmodus kann an einem luftgekapselten oder sicheren Ort erforderlich sein. In diesem Szenario können Sie eine einzelne private, gespiegelte Registry oder zwei gespiegelte Registryrien erstellen, um die erforderlichen Trident- und CSI-Images zu speichern.


NOTE: Unabhängig von Ihrer Registrierungskonfiguration müssen CSI-Bilder in einer Registrierung enthalten sein.

--
.Remote-Installation
--
Hier finden Sie einen allgemeinen Überblick über den Remote-Installationsprozess:

* Stellen Sie die entsprechende Version von `kubectl` auf dem Remote-Computer bereit, von dem aus Sie Trident bereitstellen möchten.
* Kopieren Sie die Konfigurationsdateien aus dem Kubernetes-Cluster und legen Sie die fest `KUBECONFIG` Umgebungsvariable auf dem Remotecomputer.
* Initiieren Sie A `kubectl get nodes` Befehl zum Überprüfen, ob eine Verbindung mit dem erforderlichen Kubernetes-Cluster hergestellt werden kann.
* Führen Sie die Implementierung von der Remote-Maschine aus, indem Sie die standardmäßigen Installationsschritte verwenden.


--
====


== Wählen Sie den Prozess basierend auf Methode und Modus aus

Nachdem Sie Ihre Entscheidungen getroffen haben, wählen Sie den entsprechenden Prozess aus.

[cols="2"]
|===
| Methode | Installationsmodus 


| Trident-Operator (manuell)  a| 
link:kubernetes-deploy-operator.html["Standardinstallation"]

link:kubernetes-deploy-operator-mirror.html["Offline-Installation"]



| Betreiber von Trident (Helm)  a| 
link:kubernetes-deploy-helm.html["Standardinstallation"]

link:kubernetes-deploy-helm-mirror.html["Offline-Installation"]



| `tridentctl`  a| 
link:kubernetes-deploy-tridentctl.html["Standard- oder Offline-Installation"]

|===


== Wechseln zwischen den Installationsmethoden

Sie können sich entscheiden, Ihre Installationsmethode zu ändern. Bevor Sie dies tun, sollten Sie folgendes bedenken:

* Verwenden Sie immer dieselbe Methode für die Installation und Deinstallation von Trident. Wenn Sie mit bereitgestellt haben `tridentctl`, sollten Sie die entsprechende Version der Binärdatei verwenden `tridentctl`, um Trident zu deinstallieren. Wenn Sie die Installation mit dem Operator ausführen, sollten Sie den CR bearbeiten `TridentOrchestrator` und `spec.uninstall=true` Trident deinstallieren.
* Wenn Sie über eine operatorbasierte Bereitstellung verfügen, die Sie entfernen und stattdessen verwenden möchten `tridentctl`, um Trident bereitzustellen, sollten Sie zunächst Trident bearbeiten `TridentOrchestrator` und auf „Deinstallieren“ setzen `spec.uninstall=true`. Dann löschen `TridentOrchestrator` und die Bedienerbereitstellung. Sie können dann installieren mit `tridentctl`.
* Wenn Sie über eine manuelle, bedienerbasierte Implementierung verfügen und die Helm-basierte Trident Operator-Implementierung verwenden möchten, sollten Sie zuerst den Operator manuell deinstallieren und dann die Helm-Installation durchführen. So kann Helm den Trident-Operator mit den erforderlichen Beschriftungen und Anmerkungen implementieren. Wenn dies nicht der Fall ist, schlägt die Bereitstellung des Helm-basierten Trident-Operators mit einem Fehler bei der Labelvalidierung und einem Validierungsfehler bei der Annotation fehl. Wenn Sie eine haben `tridentctl`-Basierte Bereitstellung, können Sie Helm-basierte Implementierung nutzen, ohne Probleme zu verursachen.




== Andere bekannte Konfigurationsoptionen

Bei der Installation von Trident auf VMware Tanzu Portfolio-Produkten:

* Das Cluster muss privilegierte Workloads unterstützen.
* Der `--kubelet-dir` Flag sollte auf den Speicherort des kubelet-Verzeichnisses gesetzt werden. Standardmäßig ist dies `/var/vcap/data/kubelet`.
+
Festlegen der Kubelet-Position unter Verwendung `--kubelet-dir` Ist für Trident Operator, Helm und bekannt `tridentctl` Implementierungen.


