---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: Sie können den Trident-Operator bereitstellen und Trident mit Helm installieren. Dieser Vorgang gilt für Installationen, bei denen die von Trident benötigten Container-Images in einer privaten Registrierung gespeichert werden. 
---
= Trident-Operator mit Helm (Offline-Modus) implementieren
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Trident-Operator bereitstellen und Trident mit Helm installieren. Dieser Vorgang gilt für Installationen, bei denen die von Trident benötigten Container-Images in einer privaten Registrierung gespeichert werden. Wenn Sie keine private Bildregistrierung haben, verwenden Sie die link:kubernetes-deploy-helm.html["Standardimplementierung einsetzen"].



== Wichtige Informationen zu Trident 25.10

*Sie müssen die folgenden wichtigen Informationen über Trident lesen.*

.<strong>-Informationen über Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 wird jetzt in Trident unterstützt. Aktualisieren Sie Trident , bevor Sie Kubernetes aktualisieren.
* Trident setzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, wobei der empfohlene Wert `find_multipaths: no` in der Multipath.conf Datei verwendet wird.
+
Verwendung einer Konfiguration ohne Multipathing oder Verwendung von `find_multipaths: yes` Oder `find_multipaths: smart` Der Wert in der Multipath.conf-Datei führt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` Seit der Version 21.07.



=====
====


== Stellen Sie den Trident-Operator bereit, und installieren Sie Trident mithilfe von Helm

Den Trident verwendenlink:https://netapp.github.io/trident-helm-chart["Steuerruderdiagramm"^] Sie können den Trident -Operator bereitstellen und Trident in einem Schritt installieren.

Prüfen link:../trident-get-started/kubernetes-deploy.html["Die Übersicht über die Installation"] Um sicherzustellen, dass Sie die Installationsvoraussetzungen erfüllt haben, und die richtige Installationsoption für Ihre Umgebung ausgewählt haben.

.Bevor Sie beginnen
Zusätzlich zum link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["Voraussetzungen für die Implementierung"] Die Sie benötigen link:https://v3.helm.sh/["Helm Version 3"^].


IMPORTANT: Wenn Sie Trident in einem privaten Repository installieren und den `imageRegistry` Switch zur Angabe des Repository-Speicherorts verwenden, verwenden Sie ihn nicht `/netapp/` im Repository-Pfad.

.Schritte
. Trident Helm Repository hinzufügen:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
.  `helm install`Geben Sie einen Namen für die Bereitstellung und den Speicherort der Image-Registrierung an. Ihr link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Trident und CSI-Images"] kann sich in einer Registrierung oder in verschiedenen Registrierungen befinden, aber alle CSI-Bilder müssen sich in derselben Registrierung befinden. In den Beispielen `100.2506.0` ist die Version von Trident, die Sie installieren.
+
[role="tabbed-block"]
====
.Bilder in einer Registrierung
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.Bilder in verschiedenen Registern
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:25.10.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:25.10 --set tridentImage=<your-registry>/trident:25.10.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: Wenn Sie bereits einen Namespace für Trident erstellt haben, wird der `--create-namespace` Parameter erstellt keinen zusätzlichen Namespace.



Verwenden Sie können `helm list` So prüfen Sie Installationsdetails wie Name, Namespace, Diagramm, Status, App-Version, Und Revisionsnummer.



== Konfigurationsdaten während der Installation übergeben

Während der Installation gibt es zwei Möglichkeiten, die Konfigurationsdaten zu übergeben:

[cols="2"]
|===
| Option | Beschreibung 


| `--values` (Oder `-f`)  a| 
Geben Sie eine YAML-Datei mit Überschreibungen an. Dies kann mehrfach angegeben werden, und die rechteste Datei hat Vorrang.



| `--set`  a| 
Geben Sie Überschreibungen in der Befehlszeile an.

|===
Um beispielsweise den Standardwert von zu ändern `debug`, führen Sie den folgenden Befehl aus, wobei `100.2506.0` sich die Version von Trident befindet, die Sie installieren:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----
Führen Sie den folgenden Befehl aus, um den Wert nodePrep hinzuzufügen:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== Konfigurationsoptionen

Diese Tabelle und die `values.yaml` Datei, die Teil des Helm-Diagramms ist, enthält die Liste der Schlüssel und ihre Standardwerte.


WARNING: Entfernen Sie nicht die Standardaffinität aus der Datei values.yaml. Wenn Sie eine benutzerdefinierte Affinität bereitstellen möchten, erweitern Sie die Standardaffinität.

[cols="3"]
|===
| Option | Beschreibung | Standard 


| `nodeSelector` | Node-Etiketten für Pod-Zuweisung |  


| `podAnnotations` | Pod-Anmerkungen |  


| `deploymentAnnotations` | Anmerkungen zur Bereitstellung |  


| `tolerations` | Toleranzen für Pod-Zuweisung |  


| `affinity` | Affinität für Pod-Zuweisung  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: Entfernen Sie nicht die Standardaffinität aus der Datei values.yaml. Wenn Sie eine benutzerdefinierte Affinität bereitstellen möchten, erweitern Sie die Standardaffinität.



| `tridentControllerPluginNodeSelector` | Zusätzliche Node-Auswahl für Pods Siehe link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Allgemeines zu Controller-Pods und Node-Pods"] Entsprechende Details. |  


| `tridentControllerPluginTolerations` | Überschreibt Kubernetes-Toleranzen für Pods. Siehe link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Allgemeines zu Controller-Pods und Node-Pods"] Entsprechende Details. |  


| `tridentNodePluginNodeSelector` | Zusätzliche Node-Auswahl für Pods Siehe link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Allgemeines zu Controller-Pods und Node-Pods"] Entsprechende Details. |  


| `tridentNodePluginTolerations` | Überschreibt Kubernetes-Toleranzen für Pods. Siehe link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Allgemeines zu Controller-Pods und Node-Pods"] Entsprechende Details. |  


| `imageRegistry` | Identifiziert die Registrierung für die `trident-operator`, `trident` und andere Bilder. Lassen Sie das Feld leer, um die Standardeinstellung zu übernehmen. WICHTIG: Wenn Sie Trident in einem privaten Repository installieren, verwenden Sie den Schalter nicht im Repository-Pfad, wenn Sie den `imageRegistry` Repository-Speicherort angeben `/netapp/`. | „“ 


| `imagePullPolicy` | Legt die Richtlinie zum Abziehen von Bildern für den fest `trident-operator`. | `IfNotPresent` 


| `imagePullSecrets` | Legt die Abzugsgeheimnisse für das Bild fest `trident-operator`, `trident`, Und andere Bilder. |  


| `kubeletDir` | Ermöglicht das Überschreiben der Hostposition des internen Status von kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Ermöglicht die Einstellung der Protokollebene des Trident-Operators auf: `trace`, `debug`, `info`, `warn`, `error`, Oder `fatal`. | `"info"` 


| `operatorDebug` | Ermöglicht es, die Protokollebene des Trident-Operators auf Debug zu setzen. | `true` 


| `operatorImage` | Ermöglicht die vollständige Überschreibung des Bildes für `trident-operator`. | „“ 


| `operatorImageTag` | Ermöglicht das Überschreiben des Tags des `trident-operator` Bild: | „“ 


| `tridentIPv6` | Ermöglicht die Aktivierung von Trident für die Arbeit in IPv6-Clustern. | `false` 


| `tridentK8sTimeout`  a| 
Überschreibt das standardmäßige Timeout von 180 Sekunden für die meisten Kubernetes-API-Operationen (falls ungleich Null, in Sekunden).


NOTE: Der `tridentK8sTimeout` Der Parameter ist nur für die Trident -Installation anwendbar.
| `180` 


| `tridentHttpRequestTimeout` | Setzt das standardmäßige 90-Sekunden-Timeout für die HTTP-Anforderungen mit außer Kraft `0s` Ist eine unendliche Dauer für das Timeout. Negative Werte sind nicht zulässig. | `"90s"` 


| `tridentSilenceAutosupport` | Ermöglicht die Deaktivierung von regelmäßigen Trident AutoSupport-Berichten. | `false` 


| `tridentAutosupportImageTag` | Ermöglicht das Überschreiben des Tags des Images für den Trident AutoSupport-Container. | `<version>` 


| `tridentAutosupportProxy` | Aktiviert den Trident AutoSupport-Container, um über einen HTTP-Proxy per Telefon nach Hause zu telefonieren. | „“ 


| `tridentLogFormat` | Legt das Trident-Protokollierungsformat  oder `json`) fest(`text`. | `"text"` 


| `tridentDisableAuditLog` | Deaktiviert den Trident-Audit-Logger. | `true` 


| `tridentLogLevel` | Ermöglicht die Einstellung der Protokollebene von Trident auf: `trace`, , `debug`, , `info` `warn` `error` Oder `fatal`. | `"info"` 


| `tridentDebug` | Ermöglicht die Einstellung der Protokollebene von Trident auf `debug`. | `false` 


| `tridentLogWorkflows` | Ermöglicht die Aktivierung bestimmter Trident-Workflows für die Trace-Protokollierung oder Protokollunterdrückung. | „“ 


| `tridentLogLayers` | Ermöglicht die Aktivierung bestimmter Trident-Ebenen für die Trace-Protokollierung oder Protokollunterdrückung. | „“ 


| `tridentImage` | Ermöglicht die vollständige Überschreibung des Bildes für Trident. | „“ 


| `tridentImageTag` | Ermöglicht das Überschreiben des Tags des Bildes für Trident. | „“ 


| `tridentProbePort` | Ermöglicht das Überschreiben des Standardports, der für Kubernetes Liveness/Readiness-Sonden verwendet wird. | „“ 


| `windows` | Aktiviert die Installation von Trident auf dem Windows-Arbeitsknoten. | `false` 


| `enableForceDetach` | Ermöglicht das Aktivieren der Funktion „Zwangstrennung“. Sie können den erzwungenen Trennvorgang durch die Integration mit dem Node Health Check (NHC)-Operator automatisieren. Weitere Informationen finden Sie unterlink:../trident-reco/force-detach.html["Automatisierung des Failovers zustandsbehafteter Anwendungen mit Trident"] . | `false` 


| `excludePodSecurityPolicy` | Schließt die Sicherheitsrichtlinie des Operator POD von der Erstellung aus. | `false` 


| `nodePrep`  a| 
Ermöglicht Trident, die Nodes des Kubernetes-Clusters so vorzubereiten, dass Volumes mithilfe des angegebenen Daten-Storage-Protokolls gemanagt werden. *Derzeit `iscsi` wird nur der Wert unterstützt.*


NOTE: Ab OpenShift 4.19 ist die für diese Funktion unterstützte Mindestversion von Trident 25.06.1.
|  


| `resources`  a| 
Legt Kubernetes-Ressourcenlimits und -anforderungen für den Trident -Controller, den Knoten und die Operator-Pods fest.  Sie können CPU und Arbeitsspeicher für jeden Container und Sidecar konfigurieren, um die Ressourcenzuweisung in Kubernetes zu verwalten.

Weitere Informationen zum Konfigurieren von Ressourcenanforderungen und -limits finden Sie unterlink:https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/["Ressourcenverwaltung für Pods und Container"^] Die

[WARNING]
====
* Ändern Sie NICHT die Namen von Containern oder Feldern.
* Ändern Sie die Einrückung NICHT – die YAML-Einrückung ist für die korrekte Analyse entscheidend.


====
[NOTE]
====
* Es gelten standardmäßig keine Beschränkungen – nur Anfragen haben Standardwerte.
* Die Containernamen werden so aufgelistet, wie sie in den Pod-Spezifikationen erscheinen.
* Die Beiwagen sind unter jedem Hauptcontainer aufgeführt.
* Überprüfen Sie die TORCs `status.CurrentInstallationParams` Feld zur Anzeige der aktuell angewendeten Werte.


==== a| 
[source, yaml]
----
resources:
  controller:
    trident-main:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
          cpu:
          memory:
    csi-provisioner:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-attacher:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-resizer:
      requests:
        cpu: 3m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-snapshotter:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    trident-autosupport:
      requests:
        cpu: 1m
        memory: 30Mi
      limits:
        cpu:
        memory:
  node:
    linux:
      trident-main:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 1m
          memory: 10Mi
        limits:
          cpu:
          memory:
    windows:
      trident-main:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      liveness-probe:
        requests:
          cpu: 2m
          memory: 40Mi
        limits:
          cpu:
          memory:
  operator:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu:
      memory:
----
|===