---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, standard, registry 
summary: Sie können den Trident-Operator bereitstellen und Trident mit Helm installieren. Dieser Vorgang gilt für Installationen, bei denen die von Trident benötigten Container-Images nicht in einer privaten Registrierung gespeichert werden. 
---
= Trident Operator mit Helm (Standard-Modus) implementieren
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Trident-Operator bereitstellen und Trident mit Helm installieren. Dieser Vorgang gilt für Installationen, bei denen die von Trident benötigten Container-Images nicht in einer privaten Registrierung gespeichert werden. Wenn Sie über eine private Bildregistrierung verfügen, verwenden Sie die link:kubernetes-deploy-helm-mirror.html["Prozess für Offline-Implementierung"].



== Wichtige Informationen zu Trident 25.10

*Sie müssen die folgenden wichtigen Informationen über Trident lesen.*

.<strong>-Informationen über Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 wird jetzt in Trident unterstützt. Aktualisieren Sie Trident , bevor Sie Kubernetes aktualisieren.
* Trident setzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, wobei der empfohlene Wert `find_multipaths: no` in der Multipath.conf Datei verwendet wird.
+
Verwendung einer Konfiguration ohne Multipathing oder Verwendung von `find_multipaths: yes` Oder `find_multipaths: smart` Der Wert in der Multipath.conf-Datei führt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` Seit der Version 21.07.



=====
====


== Stellen Sie den Trident-Operator bereit, und installieren Sie Trident mithilfe von Helm

Verwendung von Trident link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Steuerruderdiagramm"^] Sie können den Trident Operator implementieren und Trident in einem Schritt installieren.

Prüfen link:../trident-get-started/kubernetes-deploy.html["Die Übersicht über die Installation"] Um sicherzustellen, dass Sie die Installationsvoraussetzungen erfüllt haben, und die richtige Installationsoption für Ihre Umgebung ausgewählt haben.

.Bevor Sie beginnen
Zusätzlich zum link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["Voraussetzungen für die Implementierung"] Die Sie benötigen link:https://v3.helm.sh/["Helm Version 3"^].

.Schritte
. Trident Helm Repository hinzufügen:
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
.  `helm install`Geben Sie einen Namen für Ihre Bereitstellung an, wie im folgenden Beispiel gezeigt, wo `100.2506.0` sich die Version von Trident befindet, die Sie installieren.
+
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --create-namespace --namespace <trident-namespace>
----
+

NOTE: Wenn Sie bereits einen Namespace für Trident erstellt haben, wird der `--create-namespace` Parameter erstellt keinen zusätzlichen Namespace.



Verwenden Sie können `helm list` So prüfen Sie Installationsdetails wie Name, Namespace, Diagramm, Status, App-Version, Und Revisionsnummer.



== Konfigurationsdaten während der Installation übergeben

Während der Installation gibt es zwei Möglichkeiten, die Konfigurationsdaten zu übergeben:

[cols="2"]
|===
| Option | Beschreibung 


| `--values` (Oder `-f`)  a| 
Geben Sie eine YAML-Datei mit Überschreibungen an. Dies kann mehrfach angegeben werden, und die rechteste Datei hat Vorrang.



| `--set`  a| 
Geben Sie Überschreibungen in der Befehlszeile an.

|===
Um beispielsweise den Standardwert von zu ändern `debug`, führen Sie den folgenden Befehl aus, wobei `100.2506.0` sich die Version von Trident befindet, die Sie installieren:

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----


== Konfigurationsoptionen

Diese Tabelle und die `values.yaml` Datei, die Teil des Helm-Diagramms ist, enthält die Liste der Schlüssel und ihre Standardwerte.

[cols="1,2,3"]
|===
| Option | Beschreibung | Standard 


| `nodeSelector` | Node-Etiketten für Pod-Zuweisung |  


| `podAnnotations` | Pod-Anmerkungen |  


| `deploymentAnnotations` | Anmerkungen zur Bereitstellung |  


| `tolerations` | Toleranzen für Pod-Zuweisung |  


| `affinity` | Affinität für Pod-Zuweisung  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: Entfernen Sie nicht die Standardaffinität aus der Datei values.yaml. Wenn Sie eine benutzerdefinierte Affinität bereitstellen möchten, erweitern Sie die Standardaffinität.



| `tridentControllerPluginNodeSelector` | Zusätzliche Node-Auswahl für Pods Siehe <<Allgemeines zu Controller-Pods und Node-Pods>> Entsprechende Details. |  


| `tridentControllerPluginTolerations` | Überschreibt Kubernetes-Toleranzen für Pods. Siehe <<Allgemeines zu Controller-Pods und Node-Pods>> Entsprechende Details. |  


| `tridentNodePluginNodeSelector` | Zusätzliche Node-Auswahl für Pods Siehe <<Allgemeines zu Controller-Pods und Node-Pods>> Entsprechende Details. |  


| `tridentNodePluginTolerations` | Überschreibt Kubernetes-Toleranzen für Pods. Siehe <<Allgemeines zu Controller-Pods und Node-Pods>> Entsprechende Details. |  


| `imageRegistry` | Identifiziert die Registrierung für die `trident-operator`, `trident` und andere Bilder. Lassen Sie das Feld leer, um die Standardeinstellung zu übernehmen. WICHTIG: Wenn Sie Trident in einem privaten Repository installieren, verwenden Sie den Schalter nicht im Repository-Pfad, wenn Sie den `imageRegistry` Repository-Speicherort angeben `/netapp/`. | `""` 


| `imagePullPolicy` | Legt die Richtlinie zum Abziehen von Bildern für den fest `trident-operator`. | `IfNotPresent` 


| `imagePullSecrets` | Legt die Abzugsgeheimnisse für das Bild fest `trident-operator`, `trident`, Und andere Bilder. |  


| `kubeletDir` | Ermöglicht das Überschreiben der Hostposition des internen Status von kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Ermöglicht die Einstellung der Protokollebene des Trident-Operators auf: `trace`, `debug`, `info`, `warn`, `error`, Oder `fatal`. | `"info"` 


| `operatorDebug` | Ermöglicht es, die Protokollebene des Trident-Operators auf Debug zu setzen. | `true` 


| `operatorImage` | Ermöglicht die vollständige Überschreibung des Bildes für `trident-operator`. | `""` 


| `operatorImageTag` | Ermöglicht das Überschreiben des Tags des `trident-operator` Bild: | `""` 


| `tridentIPv6` | Ermöglicht die Aktivierung von Trident für die Arbeit in IPv6-Clustern. | `false` 


| `tridentK8sTimeout` | Setzt das standardmäßige 30-Sekunden-Zeitlimit für die meisten Kubernetes-API-Vorgänge außer Kraft (wenn nicht Null, in Sekunden). | `0` 


| `tridentHttpRequestTimeout` | Setzt das standardmäßige 90-Sekunden-Timeout für die HTTP-Anforderungen mit außer Kraft `0s` Ist eine unendliche Dauer für das Timeout. Negative Werte sind nicht zulässig. | `"90s"` 


| `tridentSilenceAutosupport` | Ermöglicht die Deaktivierung von regelmäßigen Trident AutoSupport-Berichten. | `false` 


| `tridentAutosupportImageTag` | Ermöglicht das Überschreiben des Tags des Images für den Trident AutoSupport-Container. | `<version>` 


| `tridentAutosupportProxy` | Aktiviert den Trident AutoSupport-Container, um über einen HTTP-Proxy per Telefon nach Hause zu telefonieren. | `""` 


| `tridentLogFormat` | Legt das Trident-Protokollierungsformat  oder `json`) fest(`text`. | `"text"` 


| `tridentDisableAuditLog` | Deaktiviert den Trident-Audit-Logger. | `true` 


| `tridentLogLevel` | Ermöglicht die Einstellung der Protokollebene von Trident auf: `trace`, , `debug`, , `info` `warn` `error` Oder `fatal`. | `"info"` 


| `tridentDebug` | Ermöglicht die Einstellung der Protokollebene von Trident auf `debug`. | `false` 


| `tridentLogWorkflows` | Ermöglicht die Aktivierung bestimmter Trident-Workflows für die Trace-Protokollierung oder Protokollunterdrückung. | `""` 


| `tridentLogLayers` | Ermöglicht die Aktivierung bestimmter Trident-Ebenen für die Trace-Protokollierung oder Protokollunterdrückung. | `""` 


| `tridentImage` | Ermöglicht die vollständige Überschreibung des Bildes für Trident. | `""` 


| `tridentImageTag` | Ermöglicht das Überschreiben des Tags des Bildes für Trident. | `""` 


| `tridentProbePort` | Ermöglicht das Überschreiben des Standardports, der für Kubernetes Liveness/Readiness-Sonden verwendet wird. | `""` 


| `windows` | Aktiviert die Installation von Trident auf dem Windows-Arbeitsknoten. | `false` 


| `enableForceDetach` | Ermöglicht die Aktivierung der Funktion zum Abtrennen erzwingen. | Sie können den erzwungenen Trennvorgang durch die Integration mit dem Node Health Check (NHC)-Operator automatisieren. Weitere Informationen finden Sie unterlink:../trident-reco/force-detach.html["Automatisierung des Failovers zustandsbehafteter Anwendungen mit Trident"] . 


| `false` | `excludePodSecurityPolicy` | Schließt die Sicherheitsrichtlinie des Operator POD von der Erstellung aus. 


| `false` | `cloudProvider` | Auf einstellen `"Azure"` Bei Verwendung von verwalteten Identitäten oder einer Cloud-Identität auf einem AKS-Cluster. Bei Verwendung einer Cloud-Identität auf einem EKS Cluster auf „AWS“ einstellen. 


| `""` | `cloudIdentity` | Bei Verwendung der Cloud-Identität auf einem AKS-Cluster auf Workload-Identität („Azure.Workload.Identity/Client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx“) einstellen. Bei Verwendung der Cloud-Identität auf einem EKS-Cluster auf AWS iam-Rolle (“'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/Trident-role') einstellen. 


| `""` | `iscsiSelfHealingInterval` | Das Intervall, in dem die iSCSI-Selbstheilung aufgerufen wird. 


| `5m0s` | `iscsiSelfHealingWaitTime` | Die Dauer, nach der die iSCSI-Selbstheilung den Versuch startet, eine veraltete Sitzung durch Abmeldung und anschließende Anmeldung aufzulösen. 


| `7m0s` | `nodePrep` | Ermöglicht Trident , die Knoten des Kubernetes-Clusters für die Verwaltung von Volumes mithilfe des angegebenen Datenspeicherprotokolls vorzubereiten.  *Momentan, `iscsi` ist der einzige unterstützte Wert.*  HINWEIS: Ab OpenShift 4.19 ist die für diese Funktion unterstützte Mindestversion von Trident 25.06.1. 


|  | `enableConcurrency`  a| 
Ermöglicht gleichzeitige Trident -Controller-Operationen für verbesserten Durchsatz.


NOTE: *Technische Vorschau*: Diese Funktion ist experimentell und unterstützt derzeit eingeschränkte parallele Arbeitsabläufe mit den Treibern ONTAP-NAS (nur NFS) und ONTAP-SAN (NVMe für Unified ONTAP 9) sowie die bestehende technische Vorschau für den Treiber ONTAP-SAN (iSCSI- und FCP-Protokolle in Unified ONTAP 9).



| Falsch | `k8sAPIQPS`  a| 
Das vom Controller bei der Kommunikation mit dem Kubernetes-API-Server verwendete Limit für Abfragen pro Sekunde (QPS).  Der Burst-Wert wird automatisch basierend auf dem QPS-Wert festgelegt.



| `100`; optional | `resources`  a| 
Legt Kubernetes-Ressourcenlimits und -anforderungen für den Trident -Controller, den Knoten und die Operator-Pods fest. Sie können CPU und Arbeitsspeicher für jeden Container und Sidecar konfigurieren, um die Ressourcenzuweisung in Kubernetes zu verwalten.

Weitere Informationen zum Konfigurieren von Ressourcenanforderungen und -limits finden Sie unterlink:https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/["Ressourcenverwaltung für Pods und Container"^] Die

[WARNING]
====
* Ändern Sie NICHT die Namen von Containern oder Feldern.
* Ändern Sie die Einrückung NICHT – die YAML-Einrückung ist für die korrekte Analyse entscheidend.


====
[NOTE]
====
* Standardmäßig gelten keine Limits – nur Anfragen haben Standardwerte, die automatisch angewendet werden, sofern keine anderen Werte angegeben sind.
* Die Containernamen werden so aufgelistet, wie sie in den Pod-Spezifikationen erscheinen.
* Die Beiwagen sind unter jedem Hauptcontainer aufgeführt.
* Überprüfen Sie die TORCs `status.CurrentInstallationParams` Feld zur Anzeige der aktuell angewendeten Werte.


====


 a| 
[source, yaml]
----
resources:
  controller:
    trident-main:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
          cpu:
          memory:
    csi-provisioner:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-attacher:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-resizer:
      requests:
        cpu: 3m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-snapshotter:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    trident-autosupport:
      requests:
        cpu: 1m
        memory: 30Mi
      limits:
        cpu:
        memory:
  node:
    linux:
      trident-main:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 1m
          memory: 10Mi
        limits:
          cpu:
          memory:
    windows:
      trident-main:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      liveness-probe:
        requests:
          cpu: 2m
          memory: 40Mi
        limits:
          cpu:
          memory:
  operator:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu:
      memory:
----| `httpsMetrics` | Aktivieren Sie HTTPS für den Prometheus-Metrikendpunkt. 


| Falsch | `hostNetwork`  a| 
Ermöglicht die Host-Netzwerkverbindung für den Trident -Controller. Dies ist nützlich, wenn Sie den Frontend- und Backend-Datenverkehr in einem Netzwerk mit mehreren Heimnetzwerken trennen möchten.

|===


=== Allgemeines zu Controller-Pods und Node-Pods

Trident wird als einzelner Controller-Pod ausgeführt und zusätzlich als Node Pod auf jedem Worker-Node im Cluster. Der Node Pod muss auf einem beliebigen Host ausgeführt werden, auf dem Sie potenziell ein Trident Volume mounten möchten.

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Knotenauswahl"^] Und link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["Toleranzen und Verfleckungen"^] Werden verwendet, um die Ausführung eines Pod auf einem bestimmten oder bevorzugten Node einzuschränken. Verwenden von`ControllerPlugin` und `NodePlugin`, Sie können Bedingungen und Überschreibungen festlegen.

* Das Controller-Plug-in übernimmt Volume-Bereitstellung und -Management, beispielsweise Snapshots und Größenanpassungen.
* Das Node-Plug-in verarbeitet das Verbinden des Speichers mit dem Node.

