---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, Trident, methods, tridentctl, windows 
summary: 'Sie können Trident mit installieren `tridentctl`. Dieser Vorgang gilt für Installationen, bei denen die von Trident benötigten Container-Images entweder in einer privaten Registrierung gespeichert werden oder nicht.' 
---
= Installieren Sie mit tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Trident mit installieren `tridentctl`. Dieser Vorgang gilt für Installationen, bei denen die von Trident benötigten Container-Images entweder in einer privaten Registrierung gespeichert werden oder nicht. Informationen zum Anpassen der `tridentctl` Bereitstellung finden Sie unter link:kubernetes-customize-deploy-tridentctl.html["Tridentctl-Implementierung anpassen"].



== Wichtige Informationen zu Trident 25.06

*Sie müssen die folgenden wichtigen Informationen über Trident lesen.*

.<strong>-Informationen über Trident </strong>
[%collapsible%open]
====
* Kubernetes 1.27 wird jetzt in Trident unterstützt. Upgrade von Trident vor dem Upgrade von Kubernetes.
* Trident setzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, wobei der empfohlene Wert `find_multipaths: no` in der Multipath.conf Datei verwendet wird.
+
Verwendung einer Konfiguration ohne Multipathing oder Verwendung von `find_multipaths: yes` Oder `find_multipaths: smart` Der Wert in der Multipath.conf-Datei führt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` Seit der Version 21.07.



====


== Installieren Sie Trident mit `tridentctl`

Prüfen link:../trident-get-started/kubernetes-deploy.html["Die Übersicht über die Installation"] Um sicherzustellen, dass Sie die Installationsvoraussetzungen erfüllt haben, und die richtige Installationsoption für Ihre Umgebung ausgewählt haben.

.Bevor Sie beginnen
Melden Sie sich vor der Installation beim Linux-Host an, und überprüfen Sie, ob er einen funktionierenden link:requirements.html["Unterstützter Kubernetes-Cluster"^] Und dass Sie die erforderlichen Berechtigungen haben.


NOTE: Mit OpenShift, verwenden `oc` Statt `kubectl` In allen folgenden Beispielen, und melden Sie sich als *System:admin* zuerst mit dem Ausführen an `oc login -u system:admin` Oder `oc login -u kube-admin`.

[%collapsible%open]
====
. Überprüfen Sie Ihre Kubernetes Version:
+
[listing]
----
kubectl version
----
. Überprüfung der Berechtigungen für Cluster-Administratoren:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Überprüfen Sie, ob Sie einen Pod starten können, der ein Image aus dem Docker Hub verwendet, und ob er das Storage-System über das POD-Netzwerk erreichen kann:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== Schritt 1: Laden Sie das Trident Installer-Paket herunter

Das Trident-Installationspaket erstellt einen Trident-Pod, konfiguriert die CRD-Objekte, die zur Aufrechterhaltung ihres Status verwendet werden, und initialisiert die CSI-Sidcars, um Aktionen wie das Bereitstellen und Verbinden von Volumes mit den Cluster-Hosts durchzuführen. Laden Sie die neueste Version des Trident-Installers herunter und extrahieren Sie sie auslink:https://github.com/NetApp/trident/releases/latest["Die Sektion _Assets_ auf GitHub"^]. Aktualisieren Sie _<Trident-Installer-XX.XX.X.tar.gz>_ im Beispiel mit Ihrer ausgewählten Trident-Version.

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.06.0/trident-installer-25.06.0.tar.gz
tar -xf trident-installer-25.06.0.tar.gz
cd trident-installer
----


== Schritt 2: Installieren Sie Trident

Installieren Sie Trident im gewünschten Namespace, indem Sie den Befehl ausführen `tridentctl install`. Sie können weitere Argumente hinzufügen, um den Speicherort der Bildregistrierung anzugeben.

[role="tabbed-block"]
====
.Standardmodus
--
[listing]
----
./tridentctl install -n trident
----
--
.Bilder in einer Registrierung
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.06 --trident-image <your-registry>/trident:25.06.0
----
--
.Bilder in verschiedenen Registern
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.06 --trident-image <your-registry>/trident:25.06.0
----
--
====
Ihr Installationsstatus sollte so aussehen.

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=25.06.0
INFO Trident installation succeeded.
....
----


== Überprüfen Sie die Installation

Sie können Ihre Installation mithilfe des POD-Erstellungsstatus oder überprüfen `tridentctl`.



=== Den Status der Pod-Erstellung verwenden

Sie können überprüfen, ob die Trident-Installation abgeschlossen wurde, indem Sie den Status der erstellten Pods überprüfen:

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: Wenn das Installationsprogramm nicht erfolgreich abgeschlossen wurde, oder `trident-controller-<generated id>` (`trident-csi-<generated id>` In Versionen vor 23.01) hat keinen *laufenden* Status, die Plattform wurde nicht installiert. Nutzung `-d` Bis link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["Aktivieren Sie den Debug-Modus"] Und das Problem beheben.



=== Wird Verwendet `tridentctl`

Mit können Sie `tridentctl` die installierte Version von Trident überprüfen.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.06.0        | 25.06.0        |
+----------------+----------------+
----


== Beispielkonfigurationen

Die folgenden Beispiele zeigen Beispielkonfigurationen für die Installation von Trident mit `tridentctl`.

.Windows-Knoten
[%collapsible]
====
So aktivieren Sie die Ausführung von Trident auf Windows-Knoten:

[listing]
----
tridentctl install --windows -n trident
----
====
.Lösen erzwingen
[%collapsible]
====
Weitere Informationen zum gewaltsam Lösen finden Sie unter link:..trident-get-started/kubernetes-customize-deploy.html["Anpassen der Trident Operator-Installation"].

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====