= Timeout-Annotation für Data Mover
:allow-uri-read: 




== Timeout-Annotation für Data Mover

Bei Sicherungs- und Wiederherstellungsvorgängen können Sie die Anmerkung  `protect.trident.netapp.io/data-mover-timeout-sec` Zum Konfigurieren des Timeouts für Datenverschiebungsvorgänge. Diese Anmerkung gibt die maximale Zeit in Sekunden an, die ein Datenverschieber auf den Abschluss eines bestimmten Vorgangs warten soll, bevor ein Timeout auftritt. Dies ist besonders nützlich, wenn Netzwerkprobleme oder andere Faktoren zu Verzögerungen bei der Datenverschiebung führen können. Sie hilft, verzögerte Vorgänge zu erkennen und zu verarbeiten, anstatt ein allgemeines Timeout für den gesamten Prozess festzulegen. Wenn beispielsweise aufgrund von Netzwerkproblemen keine Fortschritte bei der Wiederherstellung von Volumedaten erzielt werden, wird der Vorgang basierend auf der angegebenen Dauer abgebrochen.

Sie können diese Annotation in Ihrer YAML-Datei wie unten gezeigt verwenden:

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
In diesem Beispiel schlägt die Annotation fehl.  `BackupRestore` Vorgang ab, wenn innerhalb von 2 Sekunden beim Wiederherstellungsvorgang kein Fortschritt eintritt.


NOTE: Wenn der Annotationswert kleiner oder gleich 0 ist, schlägt der Vorgang sofort fehl.
