---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Vor der Installation von Trident sollten Sie die folgenden allgemeinen Systemanforderungen überprüfen. Spezifische Back-Ends können zusätzliche Anforderungen haben. 
---
= Anforderungen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation von Trident sollten Sie die folgenden allgemeinen Systemanforderungen überprüfen. Spezifische Back-Ends können zusätzliche Anforderungen haben.



== Wichtige Informationen über Trident

*Sie müssen die folgenden wichtigen Informationen über Trident lesen.*

.<strong>-Informationen über Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.31 wird jetzt in Trident unterstützt. Upgrade von Trident vor dem Upgrade von Kubernetes.
* Trident setzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, wobei der empfohlene Wert `find_multipaths: no` in der Multipath.conf Datei verwendet wird.
+
Verwendung einer Konfiguration ohne Multipathing oder Verwendung von `find_multipaths: yes` Oder `find_multipaths: smart` Der Wert in der Multipath.conf-Datei führt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` Seit der Version 21.07.



=====
====


== Unterstützte Frontends (Orchestrators)

Trident unterstützt diverse Container-Engines und -Orchestrierungslösungen, darunter:

* Anthos On-Premises (VMware) und Anthos auf Bare Metal 1.16
* Kubernetes 1.25–1.31
* OpenShift 4.10 - 4.16
* Rancher Kubernetes Engine 2 (RKE2) v1.28.5+rke2r1


Der Trident-Operator wird durch folgende Versionen unterstützt:

* Anthos On-Premises (VMware) und Anthos auf Bare Metal 1.16
* Kubernetes 1.25–1.31
* OpenShift 4.10 - 4.16
* Rancher Kubernetes Engine 2 (RKE2) v1.28.5+rke2r1


Trident kann auch mit einer Vielzahl anderer, vollständig gemanagter und selbst gemanagter Kubernetes-Angebote eingesetzt werden, wie z. B. Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Mirantis Kubernetes Engine (MKE) und VMware Tanzu Portfolio.

Trident und ONTAP können als Speicheranbieter für verwendet werdenlink:https://kubevirt.io/["KubeVirt"].


WARNING: Lesen Sie, bevor Sie ein Kubernetes-Cluster von 1.24 auf 1.25 oder höher aktualisieren, auf dem Trident installiert link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["Aktualisieren einer Helm-Installation"]ist.



== Unterstützte Back-Ends (Storage)

Um Trident verwenden zu können, benötigen Sie eines oder mehrere der folgenden unterstützten Back-Ends:

* Amazon FSX für NetApp ONTAP
* Azure NetApp Dateien
* Cloud Volumes ONTAP
* Cloud Volumes Service für GCP
* FAS/All Flash FAS/Select 9.5 oder höher
* NetApp All-SAN-Array (ASA)
* NetApp HCI/Element Software 11 oder höher




== Anforderungen an die Funktionen

Die folgende Tabelle bietet einen Überblick über die mit dieser Version von Trident verfügbaren Funktionen und die unterstützten Versionen von Kubernetes.

[cols="3"]
|===
| Merkmal | Kubernetes-Version | Funktionstore erforderlich? 


| Trident  a| 
1.25 - 1.31
 a| 
Nein



| Volume Snapshots  a| 
1.25 - 1.31
 a| 
Nein



| PVC aus Volume Snapshots  a| 
1.25 - 1.31
 a| 
Nein



| ISCSI PV-Größe  a| 
1.25 - 1.31
 a| 
Nein



| Bidirektionales ONTAP-CHAP  a| 
1.25 - 1.31
 a| 
Nein



| Dynamische Exportrichtlinien  a| 
1.25 - 1.31
 a| 
Nein



| Trident Operator  a| 
1.25 - 1.31
 a| 
Nein



| CSI-Topologie  a| 
1.25 - 1.31
 a| 
Nein

|===


== Getestete Host-Betriebssysteme

Trident unterstützt zwar offiziell keine bestimmten Betriebssysteme, aber dafür ist bekannt, dass Folgendes funktioniert:

* Redhat CoreOS (RHCOS) Versionen, die von OpenShift Container Platform (AMD64 und ARM64) unterstützt werden
* RHEL 8 ODER HÖHER (AMD64 UND ARM64)
+

NOTE: Für NVMe/TCP ist RHEL 9 oder höher erforderlich.

* Ubuntu 22.04 oder höher (AMD64 und ARM64)
* Windows Server 2022


Standardmäßig wird Trident in einem Container ausgeführt und wird daher auf jedem Linux-Worker ausgeführt. Diese Mitarbeiter müssen jedoch in der Lage sein, die Volumes, die Trident bietet, mit dem standardmäßigen NFS-Client oder iSCSI-Initiator zu mounten, je nach den von Ihnen verwendeten Back-Ends.

Der `tridentctl` Utility läuft auch auf jeder dieser Linux-Distributionen.



== Host-Konfiguration

Alle Worker-Nodes im Kubernetes-Cluster müssen in der Lage sein, die Volumes, die Sie für Ihre Pods bereitgestellt haben, zu mounten. Um die Worker-Nodes vorzubereiten, müssen Sie auf der Grundlage Ihrer Treiberauswahl NFS-, iSCSI- oder NVMe-Tools installieren.

link:../trident-use/worker-node-prep.html["Bereiten Sie den Knoten „Worker“ vor"]



== Konfiguration des Storage-Systems

Trident erfordert möglicherweise Änderungen am Storage-System, bevor es von einer Backend-Konfiguration verwendet werden kann.

link:../trident-use/backends.html["Back-Ends konfigurieren"]



== Trident-Ports

Trident erfordert für die Kommunikation den Zugriff auf bestimmte Ports.

link:../trident-reference/ports.html["Trident-Ports"]



== Container-Images und entsprechende Kubernetes-Versionen

Bei Installationen mit Air-Gap-Technologie ist die folgende Liste eine Referenz für Container-Images, die zur Installation von Trident erforderlich sind. Überprüfen Sie mit dem `tridentctl images` Befehl die Liste der erforderlichen Container-Images.

[cols="2"]
|===
| Kubernetes-Versionen | Container-Image 


| v1.25.0, v1.26.0, v1.27.0, v1.28.0, v1.29.0, v1.30.0, v1.31.0  a| 
* docker.io/netapp/Trident:24.10.0
* docker.io/netapp/Trident-AutoSupport:24.10
* Registry.k8s.io/SIG-Storage/csi-provisioner:v5.1.0
* Registry.k8s.io/SIG-Storage/csi-Attacher:v4.7.0
* Registry.k8s.io/SIG-Storage/csi-resizer:v1.12.0
* Registry.k8s.io/SIG-Storage/csi-snapshotter:v8.1.0
* Registry.k8s.io/SIG-Storage/csi-Node-driver-Registrar:v2.12.0
* docker.io/netapp/Trident-Operator:24.10.0 (optional)


|===