---
sidebar: sidebar 
permalink: trident-concepts/vol-access-groups.html 
keywords: volume access groups, element, solidfire, chap, Trident, hci, netapp hci, storage system, access volumes, 
summary: Erfahren Sie mehr darüber, wie Trident Volume-Zugriffsgruppen verwendet. 
---
= Volume-Zugriffsgruppen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Verwendung von Trident https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["Volume-Zugriffsgruppen"^] .


NOTE: Ignorieren Sie diesen Abschnitt, wenn Sie CHAP verwenden. Dies wird empfohlen, um die Verwaltung zu vereinfachen und die unten beschriebene Skalierungsgrenze zu vermeiden. Wenn Sie Trident im CSI-Modus verwenden, können Sie diesen Abschnitt ignorieren. Trident verwendet CHAP, wenn es als erweiterte CSI-bereitstellung installiert ist.



== Erfahren Sie mehr über Volume Access Groups

Trident kann mithilfe von Volume-Zugriffsgruppen den Zugriff auf die von ihm bereitstehenden Volumes steuern. Wenn CHAP deaktiviert ist, erwartet es, dass eine Zugriffsgruppe mit dem Namen gefunden `trident` wird, es sei denn, Sie geben eine oder mehrere Zugriffsgruppen-IDs in der Konfiguration an.

Trident ordnet zwar neue Volumes den konfigurierten Zugriffsgruppen zu, erstellt oder verwaltet jedoch keine Zugriffsgruppen selbst. Die Zugriffsgruppen müssen vorhanden sein, bevor das Storage-Back-End zu Trident hinzugefügt wird. Sie müssen die iSCSI-IQNs von jedem Node im Kubernetes-Cluster enthalten, der die über dieses Back-End bereitgestellten Volumes mounten kann. In den meisten Installationen umfasst dies alle Worker Nodes im Cluster.

Bei Kubernetes-Clustern mit mehr als 64 Nodes sollten Sie mehrere Zugriffsgruppen verwenden. Jede Zugriffsgruppe kann bis zu 64 IQNs enthalten, und jedes Volume kann zu vier Zugriffsgruppen gehören. Bei maximal vier Zugriffsgruppen kann jeder Node in einem Cluster mit einer Größe von bis zu 256 Nodes auf beliebige Volumes zugreifen. Die neuesten Grenzwerte für Volume-Zugriffsgruppen finden Sie unter https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["Hier"^].

Wenn Sie die Konfiguration von einer Konfiguration ändern, die den Standard verwendet `trident` Zugriffsgruppe für eine Gruppe, die auch andere verwendet, geben Sie die ID für die ein `trident` Zugriffsgruppe in der Liste.
