---
sidebar: sidebar 
permalink: trident-protect/learn-about-trident-protect.html 
keywords: overview, concepts, features, use case, workloads, how workload factory works 
summary: Mit Trident Protect können Sie Ihre Anwendungen und Anwendungsdaten mithilfe von Trident schützen. 
---
= Erfahren Sie mehr über Trident Protect.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Trident Protect bietet fortschrittliche Anwendungsdatenverwaltungsfunktionen, die die Funktionalität und Verfügbarkeit zustandsbehafteter Kubernetes-Anwendungen verbessern, die von NetApp ONTAP -Speichersystemen und dem NetApp Trident CSI-Speicherbereitsteller unterstützt werden.  Trident Protect vereinfacht die Verwaltung, den Schutz und die Verschiebung von containerisierten Workloads zwischen öffentlichen Clouds und On-Premises-Umgebungen. Es bietet außerdem Automatisierungsfunktionen über seine API und CLI.

Sie können Anwendungen mit Trident Protect schützen, indem Sie benutzerdefinierte Ressourcen (CRs) erstellen oder die Trident Protect CLI verwenden.



== Was kommt als Nächstes?

Sie können sich vor der Installation über die Anforderungen von Trident Protect informieren:

* link:trident-protect-requirements.html["Anforderungen von Trident Protect"]

