---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: Wenn Ihre Umgebung die Anforderungen erfüllt, können Sie die folgenden Schritte ausführen, um Trident Protect zu installieren. 
---
= Installieren und konfigurieren Sie Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Ihre Umgebung die Anforderungen für Trident Protect erfüllt, können Sie mit den folgenden Schritten Trident Protect auf Ihrem Cluster installieren. Sie können Trident Protect von NetApp beziehen oder es von Ihrer eigenen privaten Registrierung installieren. Die Installation von einer privaten Registrierung ist hilfreich, wenn Ihr Cluster nicht auf das Internet zugreifen kann.


NOTE: Standardmäßig erfasst Trident Protect Support-Informationen, die bei allen NetApp-Supportfällen helfen, die Sie öffnen können, einschließlich Protokollen, Kennzahlen und Topologieinformationen zu Clustern und gemanagten Applikationen. Trident Protect sendet diese Support-Pakete nach einem täglichen Zeitplan an NetApp. Sie können diese Support-Bundle-Sammlung optional deaktivieren, wenn Sie Trident Protect installieren. Sie können jederzeit manuell link:trident-protect-generate-support-bundle.html["Generieren Sie ein Support-Bundle"]wählen.

[role="tabbed-block"]
====
.Installieren Sie Trident Protect von NetApp
--
.Schritte
. Trident Helm Repository hinzufügen:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Installieren Sie die Trident Protect CRDs:
+
[source, console]
----
helm install trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2410.1 --create-namespace --namespace trident-protect
----
. Verwenden Sie Helm, um Trident Protect mit einem der folgenden Befehle zu installieren. Ersetzen Sie `<name_of_cluster>` ihn durch einen Cluster-Namen, der dem Cluster zugewiesen wird und zum Identifizieren der Backups und Snapshots des Clusters verwendet wird:
+
** Trident Protect normal installieren:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2410.1 --create-namespace --namespace trident-protect
----
** Installieren Sie Trident Protect und deaktivieren Sie die geplanten täglichen Uploads von Trident Protect AutoSupport Support-Paketen:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set autoSupport.enabled=false --set clusterName=<name_of_cluster> --version 100.2410.1 --create-namespace --namespace trident-protect
----




--
.Installieren Sie Trident Protect aus einer privaten Registrierung
--
Sie können Trident Protect aus einer privaten Image-Registrierung installieren, wenn Ihr Kubernetes-Cluster nicht auf das Internet zugreifen kann. Ersetzen Sie in diesen Beispielen Werte in Klammern durch Informationen aus Ihrer Umgebung:

.Schritte
. Ziehen Sie die folgenden Bilder auf Ihren lokalen Computer, aktualisieren Sie die Tags und schieben Sie sie dann in Ihre private Registrierung:
+
[source, console]
----
netapp/controller:24.10.1
netapp/restic:24.10.1
netapp/kopia:24.10.1
netapp/trident-autosupport:24.10.0
netapp/exechook:24.10.1
netapp/resourcebackup:24.10.1
netapp/resourcerestore:24.10.1
netapp/resourcedelete:24.10.1
bitnami/kubectl:1.30.2
kubebuilder/kube-rbac-proxy:v0.16.0
----
+
Beispiel:

+
[source, console]
----
docker pull netapp/controller:24.10.1
----
+
[source, console]
----
docker tag netapp/controller:24.10.1 <private-registry-url>/controller:24.10.1
----
+
[source, console]
----
docker push <private-registry-url>/controller:24.10.1
----
. Trident Protect System Namespace erstellen:
+
[source, console]
----
kubectl create ns trident-protect
----
. Melden Sie sich bei der Registrierung an:
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Erstellen Sie einen Pull-Schlüssel, der für die Authentifizierung der privaten Registrierung verwendet werden soll:
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Trident Helm Repository hinzufügen:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Erstellen Sie eine Datei mit dem Namen `protectValues.yaml`, die die folgenden Trident Protect-Einstellungen enthält:
+
[source, yaml]
----
image:
  registry: <private-registry-url>
imagePullSecrets:
- name: regcred
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
  - name: regcred
webhooksCleanup:
  imagePullSecrets:
  - name: regcred
----
. Installieren Sie die Trident Protect CRDs:
+
[source, console]
----
helm install trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2410.1 --create-namespace --namespace trident-protect
----
. Verwenden Sie Helm, um Trident Protect mit einem der folgenden Befehle zu installieren. Ersetzen Sie `<name_of_cluster>` ihn durch einen Cluster-Namen, der dem Cluster zugewiesen wird und zum Identifizieren der Backups und Snapshots des Clusters verwendet wird:
+
** Trident Protect normal installieren:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2410.1 --create-namespace --namespace trident-protect -f protectValues.yaml
----
** Installieren Sie Trident Protect und deaktivieren Sie die geplanten täglichen Uploads von Trident Protect AutoSupport Support-Paketen:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set autoSupport.enabled=false --set clusterName=<name_of_cluster> --version 100.2410.1 --create-namespace --namespace trident-protect -f protectValues.yaml
----




--
====