---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: Wenn Ihre Umgebung die Anforderungen erfüllt, können Sie die folgenden Schritte ausführen, um Trident Protect zu installieren. 
---
= Installieren und konfigurieren Sie Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Ihre Umgebung die Anforderungen für Trident Protect erfüllt, können Sie mit den folgenden Schritten Trident Protect auf Ihrem Cluster installieren. Sie können Trident Protect von NetApp beziehen oder es von Ihrer eigenen privaten Registrierung installieren. Die Installation von einer privaten Registrierung ist hilfreich, wenn Ihr Cluster nicht auf das Internet zugreifen kann.



== Installieren Sie Trident Protect

[role="tabbed-block"]
====
.Installieren Sie Trident Protect von NetApp
--
.Schritte
. Trident Helm Repository hinzufügen:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Verwenden Sie Helm, um Trident Protect zu installieren. Ersetzen Sie `<name-of-cluster>` ihn durch einen Cluster-Namen, der dem Cluster zugewiesen wird und zum Identifizieren der Backups und Snapshots des Clusters verwendet wird:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2506.0 --create-namespace --namespace trident-protect
----


--
.Installieren Sie Trident Protect aus einer privaten Registrierung
--
Sie können Trident Protect aus einer privaten Image-Registrierung installieren, wenn Ihr Kubernetes-Cluster nicht auf das Internet zugreifen kann. Ersetzen Sie in diesen Beispielen Werte in Klammern durch Informationen aus Ihrer Umgebung:

.Schritte
. Ziehen Sie die folgenden Bilder auf Ihren lokalen Computer, aktualisieren Sie die Tags und schieben Sie sie dann in Ihre private Registrierung:
+
[source, console]
----
docker.io/netapp/controller:25.06.0
docker.io/netapp/restic:25.06.0
docker.io/netapp/kopia:25.06.0
docker.io/netapp/kopiablockrestore:25.06.0
docker.io/netapp/trident-autosupport:25.06.0
docker.io/netapp/exechook:25.06.0
docker.io/netapp/resourcebackup:25.06.0
docker.io/netapp/resourcerestore:25.06.0
docker.io/netapp/resourcedelete:25.06.0
docker.io/bitnami/kubectl:1.30.2
gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
----
+
Beispiel:

+
[source, console]
----
docker pull docker.io/netapp/controller:25.06.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.06.0 <private-registry-url>/controller:25.06.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.06.0
----
+

NOTE: Um das Helm-Chart zu erhalten, laden Sie es zunächst auf einen Rechner mit Internetzugang herunter. `helm pull trident-protect --version 100.2506.0 --repo https://netapp.github.io/trident-protect-helm-chart`Kopieren Sie anschließend das resultierende `trident-protect-100.2506.0.tgz` Datei in Ihre Offline-Umgebung übertragen und installieren mit `helm install trident-protect ./trident-protect-100.2506.0.tgz` anstelle der Repository-Referenz im letzten Schritt.

. Trident Protect System Namespace erstellen:
+
[source, console]
----
kubectl create ns trident-protect
----
. Melden Sie sich bei der Registrierung an:
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Erstellen Sie einen Pull-Schlüssel, der für die Authentifizierung der privaten Registrierung verwendet werden soll:
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Trident Helm Repository hinzufügen:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Erstellen Sie eine Datei mit dem Namen `protectValues.yaml`. Stellen Sie sicher, dass es die folgenden Trident Protect-Einstellungen enthält:
+
[source, yaml]
----
---
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
    - name: regcred
webhooksCleanup:
  imagePullSecrets:
    - name: regcred
----
+

NOTE: Der `controller.image.registry` Die Einstellung gilt für alle Komponentenbilder, einschließlich `resourcebackup` Und `resourcerestore`. Wenn Sie Images in einen bestimmten Repository-Pfad innerhalb Ihrer Registry übertragen (zum Beispiel, `example.com:443/my-repo`), geben Sie den vollständigen Pfad im Registrierungsfeld an. Dadurch wird sichergestellt, dass alle Bilder abgerufen werden von `<private-registry-url>/<image-name>:<tag>`.

. Verwenden Sie Helm, um Trident Protect zu installieren. Ersetzen Sie `<name_of_cluster>` ihn durch einen Cluster-Namen, der dem Cluster zugewiesen wird und zum Identifizieren der Backups und Snapshots des Clusters verwendet wird:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2506.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----


--
====

NOTE: Weitere Konfigurationsoptionen für Helm-Charts, einschließlich AutoSupport Einstellungen und Namespace-Filterung, finden Sie unter link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Passen Sie die Trident Protect-Installation an"].
