---
sidebar: sidebar 
permalink: trident-protect/trident-protect-use-snapmirror-replication.html 
keywords: trident, protect, netapp, snapmirror, data, asynchronous, replication, clusters 
summary: Mit Trident Protect können Sie die asynchronen Replikationsfunktionen der NetApp SnapMirror Technologie nutzen, um Daten und Anwendungsänderungen von einem Speichersystem auf ein anderes zu replizieren, entweder innerhalb desselben Clusters oder zwischen verschiedenen Clustern. 
---
= Anwendungen mit NetApp SnapMirror und Trident Protect replizieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Mit Trident Protect können Sie die asynchronen Replikationsfunktionen der NetApp SnapMirror Technologie nutzen, um Daten und Anwendungsänderungen von einem Speichersystem auf ein anderes zu replizieren, entweder innerhalb desselben Clusters oder zwischen verschiedenen Clustern.



== Namespace-Annotationen und -Labels bei Restore- und Failover-Vorgängen

Während von Restore- und Failover-Vorgängen werden Labels und Annotationen im Ziel-Namespace so angefertigt, dass sie den Labels und Annotationen im Quell-Namespace entsprechen. Beschriftungen oder Anmerkungen aus dem Quell-Namespace, die nicht im Ziel-Namespace vorhanden sind, werden hinzugefügt. Alle bereits vorhandenen Beschriftungen oder Anmerkungen werden überschrieben, um dem Wert aus dem Quell-Namespace zu entsprechen. Beschriftungen oder Anmerkungen, die nur im Ziel-Namespace vorhanden sind, bleiben unverändert.


NOTE: Wenn Sie Red Hat OpenShift verwenden, ist es wichtig, die entscheidende Rolle von Namespace-Annotationen in OpenShift-Umgebungen zu beachten. Namespace-Anmerkungen stellen sicher, dass wiederhergestellte Pods die entsprechenden Berechtigungen und Sicherheitskonfigurationen einhalten, die durch die OpenShift-Sicherheitskontextbeschränkungen (SCCs) definiert sind, und ohne Berechtigungsprobleme auf Volumes zugreifen können. Weitere Informationen finden Sie imlink:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["Dokumentation zu den Einschränkungen für den Sicherheitskontext von OpenShift"^] .

Sie können verhindern, dass bestimmte Annotationen im Ziel-Namespace überschrieben werden, indem Sie die Kubernetes-Umgebungsvariable vor der Wiederherstellung oder dem Failover einstellen `RESTORE_SKIP_NAMESPACE_ANNOTATIONS`. Beispiel:

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: Bei der Durchführung einer Wiederherstellungs- oder Failover-Operation werden alle in angegebenen Namespace-Annotationen und -Labels berücksichtigt. `restoreSkipNamespaceAnnotations` Und `restoreSkipNamespaceLabels` sind von der Wiederherstellungs- oder Failover-Operation ausgeschlossen. Stellen Sie sicher, dass diese Einstellungen während der ersten Helm-Installation konfiguriert werden. Weitere Informationen finden Sie unter link:../trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Konfigurieren Sie zusätzliche Trident Protect Helm-Chart-Einstellungen"].

Wenn Sie die Quellanwendung mit Helm installiert haben `--create-namespace` Flagge, besondere Behandlung wird der `name` Legende mit Beschriftung. Während des Wiederherstellungs- oder Failover-Prozesses kopiert Trident Protect diese Bezeichnung in den Ziel-Namespace, aktualisiert aber den Wert auf den Wert des Ziel-Namespace, wenn der Wert aus der Quelle mit dem Quell-Namespace übereinstimmt. Stimmt dieser Wert nicht mit dem Quell-Namespace überein, wird er unverändert in den Ziel-Namespace kopiert.



=== Beispiel

Im folgenden Beispiel wird ein Quell- und Ziel-Namespace präsentiert, der jeweils unterschiedliche Annotationen und Labels enthält. Sie können den Status des Ziel-Namespace vor und nach dem Vorgang anzeigen und sehen, wie die Annotationen und Labels im Ziel-Namespace kombiniert oder überschrieben werden.



==== Vor der Wiederherstellung oder dem Failover

Die folgende Tabelle zeigt den Status der Beispiel-Namespaces für Quelle und Ziel vor dem Restore- oder Failover-Vorgang:

[cols="1,2a,2a"]
|===
| Namespace | Anmerkungen | Etiketten 


| Namespace ns-1 (Quelle)  a| 
* Annotation.one/key: „Aktualisiertwert“
* Anmerkung.zwei/Taste: "Wahr"

 a| 
* Umgebung = Produktion
* Compliance=hipaa
* Name=ns-1




| Namespace ns-2 (Ziel)  a| 
* Anmerkung.One/key: „True“
* Anmerkung.drei/Taste: "False"

 a| 
* Rolle=Datenbank


|===


==== Nach dem Wiederherstellungsvorgang

In der folgenden Tabelle wird der Status des Beispiel-Ziel-Namespace nach der Wiederherstellung oder dem Failover-Vorgang dargestellt. Einige Schlüssel wurden hinzugefügt, einige wurden überschrieben und das Label wurde aktualisiert, `name` um dem Ziel-Namespace zu entsprechen:

[cols="1,2a,2a"]
|===
| Namespace | Anmerkungen | Etiketten 


| Namespace ns-2 (Ziel)  a| 
* Annotation.one/key: „Aktualisiertwert“
* Anmerkung.zwei/Taste: "Wahr"
* Anmerkung.drei/Taste: "False"

 a| 
* Name=ns-2
* Compliance=hipaa
* Umgebung = Produktion
* Rolle=Datenbank


|===

NOTE: Sie können Trident Protect so konfigurieren, dass Dateisysteme während Datensicherungsvorgängen eingefroren und wieder freigegeben werden. link:trident-protect-requirements.html#protecting-data-with-kubevirt-vms["Erfahren Sie mehr über die Konfiguration des Einfrierens von Dateisystemen mit Trident Protect."].



== Ausführungs-Hooks während Failover- und Reverse-Operationen

Wenn Sie zum Schutz Ihrer Anwendung eine AppMirror-Beziehung verwenden, gibt es bestimmte Verhaltensweisen im Zusammenhang mit Ausführungs-Hooks, die Sie bei Failover- und Reverse-Vorgängen beachten sollten.

* Während des Failovers werden die Ausführungs-Hooks automatisch vom Quellcluster in den Zielcluster kopiert. Sie müssen sie nicht manuell neu erstellen. Nach dem Failover sind Ausführungs-Hooks in der Anwendung vorhanden und werden bei allen relevanten Aktionen ausgeführt.
* Beim Reverse- oder Reverse-Resync werden alle vorhandenen Ausführungs-Hooks der Anwendung entfernt. Wenn die Quellanwendung zur Zielanwendung wird, sind diese Ausführungs-Hooks ungültig und werden gelöscht, um ihre Ausführung zu verhindern.


Weitere Informationen zu Ausführungshooks finden Sie unterlink:../trident-protect/trident-protect-use-execution-hooks.html["Trident Protect-Ausführungshooks verwalten"] .



== Richten Sie eine Replikationsbeziehung ein

Die Einrichtung einer Replikationsbeziehung umfasst Folgendes:

* Auswahl der Häufigkeit, mit der Trident Protect einen App-Snapshot erstellen soll (der sowohl die Kubernetes-Ressourcen der App als auch die Volume-Snapshots für jedes der App-Volumes umfasst).
* Auswahl des Replizierungszeitplans (einschließlich Kubernetes-Ressourcen und persistenter Volume-Daten)
* Einstellen der Uhrzeit für die Erstellung des Snapshots


.Schritte
. Erstellen Sie im Quellcluster einen AppVault für die Quellanwendung. Ändern Sie abhängig von Ihrem Storage-Anbieter ein Beispiel in link:trident-protect-appvault-custom-resources.html["Benutzerdefinierte Ressourcen von AppVault"]entsprechend Ihrer Umgebung:
+
[role="tabbed-block"]
====
.Erstellen Sie einen AppVault mit einem CR
--
.. Erstellen Sie die benutzerdefinierte Ressourcendatei (CR) und benennen Sie sie (z. B. `trident-protect-appvault-primary-source.yaml`).
.. Konfigurieren Sie die folgenden Attribute:
+
*** *metadata.name*: (_required_) der Name der benutzerdefinierten AppVault-Ressource. Notieren Sie sich den ausgewählten Namen, da sich andere CR-Dateien, die für eine Replikationsbeziehung benötigt werden, auf diesen Wert beziehen.
*** *spec.providerConfig*: (_required_) speichert die Konfiguration, die für den Zugriff auf den AppVault unter Verwendung des angegebenen Providers erforderlich ist. Wählen Sie einen BucketName und alle anderen notwendigen Details für Ihren Anbieter. Notieren Sie sich die ausgewählten Werte, da sich andere CR-Dateien, die für eine Replikationsbeziehung benötigt werden, auf diese Werte beziehen. Beispiele für AppVault CRS mit anderen Anbietern finden Sie unterlink:trident-protect-appvault-custom-resources.html["Benutzerdefinierte Ressourcen von AppVault"].
*** *spec.providerCredentials*: (_required_) speichert Verweise auf alle Anmeldeinformationen, die für den Zugriff auf AppVault unter Verwendung des angegebenen Anbieters erforderlich sind.
+
**** *spec.providerCredentials.valueFromSecret*: (_required_) gibt an, dass der Wert der Zugangsdaten von einem Secret stammen soll.
+
***** *Key*: (_required_) der gültige Schlüssel des zu wählenden Geheimnisses.
***** *Name*: (_required_) Name des Geheimnisses, das den Wert für dieses Feld enthält. Muss sich im gleichen Namespace befinden.


**** *spec.providerCredentials.secretAccessKey*: (_required_) der Zugriffsschlüssel, der für den Zugriff auf den Provider verwendet wird. Der *Name* sollte mit *spec.providerCredentials.valueFromSecret.name* übereinstimmen.


*** *spec.providerType*: (_required_) legt fest, was das Backup bereitstellt, z. B. NetApp ONTAP S3, generisches S3, Google Cloud oder Microsoft Azure. Mögliche Werte:
+
**** AWS
**** Azure
**** GCP
**** Generisch-s3
**** ONTAP-s3
**** StorageGRID-s3




.. Nachdem Sie die Datei mit den richtigen Werten ausgefüllt `trident-protect-appvault-primary-source.yaml` haben, wenden Sie den CR an:
+
[source, console]
----
kubectl apply -f trident-protect-appvault-primary-source.yaml -n trident-protect
----


--
.Erstellen Sie einen AppVault mithilfe der CLI
--
.. Erstellen Sie AppVault und ersetzen Sie Werte in Klammern durch Informationen aus Ihrer Umgebung:
+
[source, console]
----
tridentctl-protect create vault Azure <vault-name> --account <account-name> --bucket <bucket-name> --secret <secret-name> -n trident-protect
----


--
====
. Erstellen Sie auf dem Quellcluster die CR-Quellanwendung:
+
[role="tabbed-block"]
====
.Erstellen Sie die Quellanwendung mit einem CR
--
.. Erstellen Sie die benutzerdefinierte Ressourcendatei (CR) und benennen Sie sie (z. B. `trident-protect-app-source.yaml`).
.. Konfigurieren Sie die folgenden Attribute:
+
*** *metadata.name*: (_required_) der Name der benutzerdefinierten Ressource der Anwendung. Notieren Sie sich den ausgewählten Namen, da sich andere CR-Dateien, die für eine Replikationsbeziehung benötigt werden, auf diesen Wert beziehen.
*** *spec.includedNamespaces*: (_required_) ein Array von Namespaces und zugehörigen Labels. Verwenden Sie Namespace-Namen und Grenzen Sie optional den Umfang der Namespaces mit Beschriftungen ein, um Ressourcen anzugeben, die in den hier aufgeführten Namespaces vorhanden sind. Der Application Namespace muss Teil dieses Arrays sein.
+
*Beispiel YAML*:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: my-app-name
  namespace: my-app-namespace
spec:
  includedNamespaces:
    - namespace: my-app-namespace
      labelSelector: {}
----


.. Nachdem Sie die Datei mit den richtigen Werten ausgefüllt `trident-protect-app-source.yaml` haben, wenden Sie den CR an:
+
[source, console]
----
kubectl apply -f trident-protect-app-source.yaml -n my-app-namespace
----


--
.Erstellen Sie die Quellanwendung mithilfe der CLI
--
.. Erstellen Sie die Quellanwendung. Beispiel:
+
[source, console]
----
tridentctl-protect create app <my-app-name> --namespaces <namespaces-to-be-included> -n <my-app-namespace>
----


--
====
. Optional kann auf dem Quellcluster ein Snapshot der Quellanwendung erstellt werden. Dieser Snapshot dient als Grundlage für die Anwendung auf dem Zielcluster. Wenn Sie diesen Schritt überspringen, müssen Sie warten, bis der nächste geplante Snapshot erstellt wird, damit Sie über einen aktuellen Snapshot verfügen. Informationen zum Erstellen eines On-Demand-Snapshots finden Sie unter link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-protect-apps.html#create-an-on-demand-snapshot["Erstellen Sie einen On-Demand Snapshot"^]Die
. Erstellen Sie auf dem Quellcluster den Replikationsplan CR:
+
[NOTE]
====
Zusätzlich zum unten aufgeführten Zeitplan empfiehlt es sich, einen separaten täglichen Snapshot-Zeitplan mit einer Aufbewahrungsdauer von 7 Tagen zu erstellen, um einen gemeinsamen Snapshot zwischen den Peering-ONTAP-Clustern zu gewährleisten. Dadurch sind Snapshots bis zu 7 Tage lang verfügbar. Die Aufbewahrungsdauer kann jedoch an die Benutzeranforderungen angepasst werden.

Im Falle eines Failovers kann das System diese Snapshots bis zu sieben Tage lang für Rückwärtsvorgänge verwenden. Dieser Ansatz beschleunigt und optimiert den Rückwärtsvorgang, da nur die seit dem letzten Snapshot vorgenommenen Änderungen und nicht alle Daten übertragen werden.

Wenn ein vorhandener Zeitplan für die Anwendung bereits die gewünschten Aufbewahrungsanforderungen erfüllt, sind keine zusätzlichen Zeitpläne erforderlich.

====
+
[role="tabbed-block"]
====
.Erstellen Sie den Replikationszeitplan mithilfe einer CR.
--
.. Erstellen Sie einen Replikationszeitplan für die Quellanwendung:
+
... Erstellen Sie die benutzerdefinierte Ressourcendatei (CR) und benennen Sie sie (z. B. `trident-protect-schedule.yaml`).
... Konfigurieren Sie die folgenden Attribute:
+
**** *metadata.name*: (_required_) der Name der benutzerdefinierten Ressource für den Zeitplan.
**** *spec.appVaultRef*: (_Erforderlich_) Dieser Wert muss mit dem Feld metadata.name des AppVaults für die Quellanwendung übereinstimmen.
**** *spec.applicationRef*: (_Erforderlich_) Dieser Wert muss mit dem Feld metadata.name der Quellanwendung CR übereinstimmen.
**** *Spec.backupRetention*: (_required_) Dieses Feld ist erforderlich und der Wert muss auf 0 gesetzt werden.
**** *Spec.enabled*: Muss auf true gesetzt werden.
**** *spec.granularity*: muss auf eingestellt sein `Custom`.
**** *Spec.recurrenceRule*: Definieren Sie ein Startdatum in UTC-Zeit und ein Wiederholungsintervall.
**** *Spec.snapshotRetention*: Muss auf 2 gesetzt werden.
+
Beispiel YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: appmirror-schedule
  namespace: my-app-namespace
spec:
  appVaultRef: my-appvault-name
  applicationRef: my-app-name
  backupRetention: "0"
  enabled: true
  granularity: Custom
  recurrenceRule: |-
    DTSTART:20220101T000200Z
    RRULE:FREQ=MINUTELY;INTERVAL=5
  snapshotRetention: "2"
----


... Nachdem Sie die Datei mit den richtigen Werten ausgefüllt `trident-protect-schedule.yaml` haben, wenden Sie den CR an:
+
[source, console]
----
kubectl apply -f trident-protect-schedule.yaml -n my-app-namespace
----




--
.Erstellen Sie den Replikationszeitplan mithilfe der Befehlszeilenschnittstelle.
--
.. Erstellen Sie den Replikationszeitplan und ersetzen Sie die Werte in Klammern durch Informationen aus Ihrer Umgebung:
+
[source, console]
----
tridentctl-protect create schedule --name appmirror-schedule --app <my_app_name> --appvault <my_app_vault> --granularity Custom --recurrence-rule <rule> --snapshot-retention <snapshot_retention_count> -n <my_app_namespace>
----
+
*Beispiel:*

+
[source, console]
----
tridentctl-protect create schedule --name appmirror-schedule --app <my_app_name> --appvault <my_app_vault> --granularity Custom --recurrence-rule  "DTSTART:20220101T000200Z\nRRULE:FREQ=MINUTELY;INTERVAL=5" --snapshot-retention 2 -n <my_app_namespace>
----


--
====
. Erstellen Sie auf dem Zielcluster eine Quellanwendung AppVault CR, die mit der AppVault CR identisch ist, die Sie auf das Quellcluster angewendet haben, und benennen Sie sie (z. B. `trident-protect-appvault-primary-destination.yaml` ).
. CR anwenden:
+
[source, console]
----
kubectl apply -f trident-protect-appvault-primary-destination.yaml -n trident-protect
----
. Erstellen Sie ein Ziel-AppVault CR für die Zielanwendung auf dem Zielcluster. Ändern Sie abhängig von Ihrem Storage-Anbieter ein Beispiel in link:trident-protect-appvault-custom-resources.html["Benutzerdefinierte Ressourcen von AppVault"]entsprechend Ihrer Umgebung:
+
.. Erstellen Sie die benutzerdefinierte Ressourcendatei (CR) und benennen Sie sie (z. B. `trident-protect-appvault-secondary-destination.yaml`).
.. Konfigurieren Sie die folgenden Attribute:
+
*** *metadata.name*: (_required_) der Name der benutzerdefinierten AppVault-Ressource. Notieren Sie sich den ausgewählten Namen, da sich andere CR-Dateien, die für eine Replikationsbeziehung benötigt werden, auf diesen Wert beziehen.
*** *spec.providerConfig*: (_required_) speichert die Konfiguration, die für den Zugriff auf den AppVault unter Verwendung des angegebenen Providers erforderlich ist. Wählen Sie eine `bucketName` und alle anderen notwendigen Details für Ihren Provider. Notieren Sie sich die ausgewählten Werte, da sich andere CR-Dateien, die für eine Replikationsbeziehung benötigt werden, auf diese Werte beziehen. Beispiele für AppVault CRS mit anderen Anbietern finden Sie unterlink:trident-protect-appvault-custom-resources.html["Benutzerdefinierte Ressourcen von AppVault"].
*** *spec.providerCredentials*: (_required_) speichert Verweise auf alle Anmeldeinformationen, die für den Zugriff auf AppVault unter Verwendung des angegebenen Anbieters erforderlich sind.
+
**** *spec.providerCredentials.valueFromSecret*: (_required_) gibt an, dass der Wert der Zugangsdaten von einem Secret stammen soll.
+
***** *Key*: (_required_) der gültige Schlüssel des zu wählenden Geheimnisses.
***** *Name*: (_required_) Name des Geheimnisses, das den Wert für dieses Feld enthält. Muss sich im gleichen Namespace befinden.


**** *spec.providerCredentials.secretAccessKey*: (_required_) der Zugriffsschlüssel, der für den Zugriff auf den Provider verwendet wird. Der *Name* sollte mit *spec.providerCredentials.valueFromSecret.name* übereinstimmen.


*** *spec.providerType*: (_required_) legt fest, was das Backup bereitstellt, z. B. NetApp ONTAP S3, generisches S3, Google Cloud oder Microsoft Azure. Mögliche Werte:
+
**** AWS
**** Azure
**** GCP
**** Generisch-s3
**** ONTAP-s3
**** StorageGRID-s3




.. Nachdem Sie die Datei mit den richtigen Werten ausgefüllt `trident-protect-appvault-secondary-destination.yaml` haben, wenden Sie den CR an:
+
[source, console]
----
kubectl apply -f trident-protect-appvault-secondary-destination.yaml -n trident-protect
----


. Erstellen Sie auf dem Zielcluster eine AppMirrorRelationship CR-Datei:
+
[role="tabbed-block"]
====
.Erstellen Sie eine AppMirrorRelationship mithilfe eines CR
--
.. Erstellen Sie die benutzerdefinierte Ressourcendatei (CR) und benennen Sie sie (z. B. `trident-protect-relationship.yaml`).
.. Konfigurieren Sie die folgenden Attribute:
+
*** *metadata.name:* (erforderlich) der Name der benutzerdefinierten AppMirrorRelationship-Ressource.
*** *spec.destinationAppVaultRef*: (_required_) dieser Wert muss mit dem Namen des AppVault für die Zielanwendung auf dem Zielcluster übereinstimmen.
*** *spec.namespaceMapping*: (_required_) der Ziel- und Quellnamepaces muss mit dem im jeweiligen Anwendungs-CR definierten AnwendungsNamespace übereinstimmen.
*** *Spec.sourceAppVaultRef*: (_required_) dieser Wert muss mit dem Namen des AppVault für die Quellanwendung übereinstimmen.
*** *Spec.sourceApplicationName*: (_required_) dieser Wert muss mit dem Namen der Quellanwendung übereinstimmen, die Sie in der Quellanwendung CR definiert haben.
*** *spec.sourceApplicationUID*: (Erforderlich) Dieser Wert muss mit der UID der Quellanwendung übereinstimmen, die Sie im Quellanwendungs-CR definiert haben.
*** *spec.storageClassName*: (_Optional_) Wählen Sie den Namen einer gültigen Speicherklasse im Cluster. Die Speicherklasse muss mit einer ONTAP Speicher-VM verknüpft sein, die mit der Quellumgebung per Peering verbunden ist. Wird keine Speicherklasse angegeben, wird standardmäßig die im Cluster vorhandene Standard-Speicherklasse verwendet.
*** *Spec.recurrenceRule*: Definieren Sie ein Startdatum in UTC-Zeit und ein Wiederholungsintervall.
+
Beispiel YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AppMirrorRelationship
metadata:
  name: amr-16061e80-1b05-4e80-9d26-d326dc1953d8
  namespace: my-app-namespace
spec:
  desiredState: Established
  destinationAppVaultRef: generic-s3-trident-protect-dst-bucket-8fe0b902-f369-4317-93d1-ad7f2edc02b5
  namespaceMapping:
    - destination: my-app-namespace
      source: my-app-namespace
  recurrenceRule: |-
    DTSTART:20220101T000200Z
    RRULE:FREQ=MINUTELY;INTERVAL=5
  sourceAppVaultRef: generic-s3-trident-protect-src-bucket-b643cc50-0429-4ad5-971f-ac4a83621922
  sourceApplicationName: my-app-name
  sourceApplicationUID: 7498d32c-328e-4ddd-9029-122540866aeb
  storageClassName: sc-vsim-2
----


.. Nachdem Sie die Datei mit den richtigen Werten ausgefüllt `trident-protect-relationship.yaml` haben, wenden Sie den CR an:
+
[source, console]
----
kubectl apply -f trident-protect-relationship.yaml -n my-app-namespace
----


--
.Erstellen Sie eine AppMirrorRelationship mithilfe der CLI
--
.. Erstellen und wenden Sie das AppMirrorRelationship-Objekt an und ersetzen Sie die Werte in Klammern durch Informationen aus Ihrer Umgebung:
+
[source, console]
----
tridentctl-protect create appmirrorrelationship <name_of_appmirorrelationship> --destination-app-vault <my_vault_name> --source-app-vault <my_vault_name> --recurrence-rule <rule> --namespace-mapping <ns_mapping> --source-app-id <source_app_UID> --source-app <my_source_app_name> --storage-class <storage_class_name> -n <application_namespace>
----
+
*Beispiel:*

+
[source, console]
----
tridentctl-protect create appmirrorrelationship my-amr --destination-app-vault appvault2 --source-app-vault appvault1 --recurrence-rule "DTSTART:20220101T000200Z\nRRULE:FREQ=MINUTELY;INTERVAL=5" --source-app my-app --namespace-mapping "my-source-ns1:my-dest-ns1,my-source-ns2:my-dest-ns2" --source-app-id 373f24c1-5769-404c-93c3-5538af6ccc36 --storage-class my-storage-class -n my-dest-ns1
----


--
====
. (_Optional_) Überprüfen Sie auf dem Zielcluster den Status und den Status der Replikationsbeziehung:
+
[source, console]
----
kubectl get amr -n my-app-namespace <relationship name> -o=jsonpath='{.status}' | jq
----




=== Failover zum Ziel-Cluster

Mit Trident Protect können Sie replizierte Anwendungen auf einen Zielcluster verschieben, ohne dass es zu einem Failover kommt. Dieses Verfahren beendet die Replikationsbeziehung und schaltet die Anwendung auf dem Zielcluster online.  Trident Protect stoppt die Anwendung auf dem Quellcluster nicht, wenn sie betriebsbereit war.

.Schritte
. Bearbeiten Sie im Zielcluster die AppMirrorRelationship CR-Datei (z. B. `trident-protect-relationship.yaml` ) und ändern Sie den Wert von *spec.desiredState* in `Promoted`.
. Speichern Sie die CR-Datei.
. CR anwenden:
+
[source, console]
----
kubectl apply -f trident-protect-relationship.yaml -n my-app-namespace
----
. (_Optional_) Erstellen Sie alle Schutzzeitpläne, die Sie für die Failover-Anwendung benötigen.
. (_Optional_) Status und Status der Replikationsbeziehung prüfen:
+
[source, console]
----
kubectl get amr -n my-app-namespace <relationship name> -o=jsonpath='{.status}' | jq
----




=== Neusynchronisierung einer fehlgeschlagenen Replikationsbeziehung

Durch den Neusynchronisierung wird die Replikationsbeziehung wiederhergestellt. Nach einer Neusynchronisierung wird die ursprüngliche Quellanwendung zur laufenden Anwendung, und alle Änderungen, die an der laufenden Anwendung auf dem Zielcluster vorgenommen werden, werden verworfen.

Der Prozess stoppt die App auf dem Zielcluster, bevor die Replikation wiederhergestellt wird.


IMPORTANT: Alle Daten, die während des Failovers auf die Zielapplikation geschrieben werden, gehen verloren.

.Schritte
. Optional: Erstellen Sie auf dem Quellcluster einen Snapshot der Quellanwendung. Dadurch wird sichergestellt, dass die neuesten Änderungen vom Quellcluster erfasst werden.
. Bearbeiten Sie im Zielcluster die AppMirrorRelationship CR-Datei (z. B. `trident-protect-relationship.yaml` ) und ändern Sie den Wert spec.desiredState in `Established`.
. Speichern Sie die CR-Datei.
. CR anwenden:
+
[source, console]
----
kubectl apply -f trident-protect-relationship.yaml -n my-app-namespace
----
. Wenn Sie Schutzzeitpläne auf dem Zielcluster erstellt haben, um die Failover-Anwendung zu schützen, entfernen Sie sie. Alle Zeitpläne, die weiterhin zu Fehlern bei Volume-Snapshots führen.




=== Reverse Resynchronisierung einer Failover-Replizierungsbeziehung

Wenn Sie eine Failover-Replikationsbeziehung umkehren, wird die Zielanwendung zur Quellanwendung, und die Quelle wird zum Ziel. Änderungen, die während des Failovers an der Zielapplikation vorgenommen werden, werden beibehalten.

.Schritte
. Löschen Sie auf dem ursprünglichen Zielcluster die AppMirrorRelationship-CR. Dadurch wird das Ziel zur Quelle. Wenn auf dem neuen Ziel-Cluster noch Schutzpläne vorhanden sind, entfernen Sie sie.
. Richten Sie eine Replikationsbeziehung ein, indem Sie die CR-Dateien anwenden, die Sie ursprünglich zum Einrichten der Beziehung zu den anderen Clustern verwendet haben.
. Stellen Sie sicher, dass das neue Ziel (ursprünglicher Quellcluster) mit beiden AppVault CRS konfiguriert ist.
. Richten Sie eine Replikationsbeziehung auf dem anderen Cluster ein, und konfigurieren Sie Werte für die umgekehrte Richtung.




== Richtung der Anwendungsreplikation umkehren

Wenn Sie die Replikationsrichtung umkehren, verschiebt Trident Protect die Anwendung zum Ziel-Speicher-Backend, während die Replikation zurück zum ursprünglichen Quell-Speicher-Backend fortgesetzt wird.  Trident Protect stoppt die Quellanwendung und repliziert die Daten zum Ziel, bevor ein Failover zur Zielanwendung erfolgt.

In dieser Situation tauschen Sie Quelle und Ziel aus.

.Schritte
. Erstellen Sie auf dem Quellcluster einen Snapshot zum Herunterfahren:
+
[role="tabbed-block"]
====
.Erstellen Sie einen Snapshot zum Herunterfahren mit einem CR
--
.. Deaktivieren Sie die Schutzrichtlinienpläne für die Quellanwendung.
.. Erstellen Sie eine CR-Datei für den ShutdownSnapshot:
+
... Erstellen Sie die benutzerdefinierte Ressourcendatei (CR) und benennen Sie sie (z. B. `trident-protect-shutdownsnapshot.yaml`).
... Konfigurieren Sie die folgenden Attribute:
+
**** *metadata.name*: (_required_) der Name der benutzerdefinierten Ressource.
**** *Spec.AppVaultRef*: (_required_) dieser Wert muss mit dem Feld metadata.name des AppVault für die Quellanwendung übereinstimmen.
**** *Spec.ApplicationRef*: (_required_) dieser Wert muss mit dem Feld metadata.name der CR-Datei der Quellanwendung übereinstimmen.
+
Beispiel YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: ShutdownSnapshot
metadata:
  name: replication-shutdown-snapshot-afc4c564-e700-4b72-86c3-c08a5dbe844e
  namespace: my-app-namespace
spec:
  appVaultRef: generic-s3-trident-protect-src-bucket-04b6b4ec-46a3-420a-b351-45795e1b5e34
  applicationRef: my-app-name
----




.. Nachdem Sie die Datei mit den richtigen Werten ausgefüllt `trident-protect-shutdownsnapshot.yaml` haben, wenden Sie den CR an:
+
[source, console]
----
kubectl apply -f trident-protect-shutdownsnapshot.yaml -n my-app-namespace
----


--
.Erstellen Sie einen Snapshot zum Herunterfahren über die CLI
--
.. Erstellen Sie den Snapshot zum Herunterfahren, und ersetzen Sie Werte in Klammern durch Informationen aus Ihrer Umgebung. Beispiel:
+
[source, console]
----
tridentctl-protect create shutdownsnapshot <my_shutdown_snapshot> --appvault <my_vault> --app <app_to_snapshot> -n <application_namespace>
----


--
====
. Rufen Sie auf dem Quellcluster nach Abschluss des Snapshot zum Herunterfahren den Status des Snapshot zum Herunterfahren ab:
+
[source, console]
----
kubectl get shutdownsnapshot -n my-app-namespace <shutdown_snapshot_name> -o yaml
----
. Suchen Sie im Quellcluster den Wert von *shutdownSnapshot.Status.appArchivePath* mit dem folgenden Befehl und notieren Sie den letzten Teil des Dateipfads (auch Basisname genannt; dies ist alles nach dem letzten Schrägstrich):
+
[source, console]
----
k get shutdownsnapshot -n my-app-namespace <shutdown_snapshot_name> -o jsonpath='{.status.appArchivePath}'
----
. Führen Sie mit der folgenden Änderung ein Failover vom neuen Zielcluster zum neuen Quellcluster durch:
+

NOTE: Fügen Sie in Schritt 2 des Failover-Verfahrens das Feld in die AppMirrorRelationship CR-Datei ein `spec.promotedSnapshot`, und setzen Sie den Wert auf den Basisnamen, den Sie oben in Schritt 3 aufgezeichnet haben.

. Führen Sie die Schritte für die umgekehrte Resynchronisierung in <<Reverse Resynchronisierung einer Failover-Replizierungsbeziehung>>aus.
. Aktivieren Sie Schutzzeitpläne auf dem neuen Quellcluster.




=== Ergebnis

Die folgenden Aktionen werden aufgrund der umgekehrten Replikation durchgeführt:

* Von den Kubernetes-Ressourcen der ursprünglichen Quell-Applikation wird ein Snapshot erstellt.
* Die PODs der ursprünglichen Quell-App werden mit sanfter Weise gestoppt, indem die Kubernetes-Ressourcen der App gelöscht werden (wodurch PVCs und PVS aktiviert bleiben).
* Nach dem Herunterfahren der Pods werden Snapshots der Volumes der App erstellt und repliziert.
* Die SnapMirror Beziehungen sind beschädigt, wodurch die Zieldatenträger für Lese-/Schreibvorgänge bereit sind.
* Die Kubernetes-Ressourcen der App werden aus dem Snapshot vor dem Herunterfahren wiederhergestellt. Dabei werden die Volume-Daten verwendet, die nach dem Herunterfahren der ursprünglichen Quell-App repliziert wurden.
* Die Replizierung wird in umgekehrter Richtung wieder hergestellt.




=== Führen Sie ein Failback von Anwendungen auf das ursprüngliche Quellcluster durch

Mit Trident Protect können Sie nach einem Failover-Vorgang ein „Failback“ erreichen, indem Sie die folgende Abfolge von Operationen verwenden.  In diesem Workflow zur Wiederherstellung der ursprünglichen Replikationsrichtung repliziert (resynchronisiert) Trident Protect alle Anwendungsänderungen zurück in die ursprüngliche Quellanwendung, bevor die Replikationsrichtung umgekehrt wird.

Dieser Prozess beginnt mit einer Beziehung, bei der ein Failover zu einem Ziel durchgeführt wurde, und umfasst die folgenden Schritte:

* Starten Sie mit einem Failover-Status fehlgeschlagen.
* Umgekehrte Neusynchronisierung der Replikationsbeziehung.
+

CAUTION: Führen Sie keine normale Neusynchronisierung durch, da dadurch während des Failover Daten, die auf das Ziel-Cluster geschrieben werden, verworfen werden.

* Kehren Sie die Replikationsrichtung um.


.Schritte
. Führen Sie die <<Reverse Resynchronisierung einer Failover-Replizierungsbeziehung>> Schritte aus.
. Führen Sie die <<Richtung der Anwendungsreplikation umkehren>> Schritte aus.




=== Löschen einer Replikationsbeziehung

Sie können eine Replikationsbeziehung jederzeit löschen. Wenn Sie die Anwendungsreplikationsbeziehung löschen, führt dies zu zwei separaten Anwendungen ohne Beziehung zwischen ihnen.

.Schritte
. Löschen Sie auf dem aktuellen Desination-Cluster die CR-Datei AppMirrorRelationship:
+
[source, console]
----
kubectl delete -f trident-protect-relationship.yaml -n my-app-namespace
----

