---
sidebar: sidebar 
permalink: trident-protect/trident-protect-cli.html 
keywords: trident, protect, command line utility, cli, netapp, custom, resources 
summary: Mit dem Befehl protectctl können Sie benutzerdefinierte Ressourcen von Trident Protect erstellen und mit ihnen interagieren. 
---
= Installieren Sie das Trident Protect CLI-Plugin.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können das Trident Protect-Befehlszeilen-Plugin verwenden, das eine Erweiterung von Trident ist. `tridentctl` Hilfsprogramm zum Erstellen und Interagieren mit benutzerdefinierten Ressourcen (CRs) von Trident Protect.



== Installieren Sie das Trident Protect CLI-Plugin.

Bevor Sie das Befehlszeilendienstprogramm verwenden, müssen Sie es auf dem Computer installieren, mit dem Sie auf das Cluster zugreifen. Befolgen Sie diese Schritte, je nachdem, ob Ihr Computer eine x64- oder ARM-CPU verwendet.

[role="tabbed-block"]
====
.Laden Sie das Plugin für Linux AMD64 CPUs herunter
--
.Schritte
. Laden Sie das Trident Protect CLI-Plugin herunter:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.10.0/tridentctl-protect-linux-amd64
----


--
.Download Plugin für Linux ARM64 CPUs
--
.Schritte
. Laden Sie das Trident Protect CLI-Plugin herunter:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.10.0/tridentctl-protect-linux-arm64
----


--
.Laden Sie das Plugin für Mac AMD64 CPUs herunter
--
.Schritte
. Laden Sie das Trident Protect CLI-Plugin herunter:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.10.0/tridentctl-protect-macos-amd64
----


--
.Download Plugin für Mac ARM64 CPUs
--
.Schritte
. Laden Sie das Trident Protect CLI-Plugin herunter:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.10.0/tridentctl-protect-macos-arm64
----


--
====
. Ausführungsberechtigungen für die Plug-in-Binärdatei aktivieren:
+
[source, console]
----
chmod +x tridentctl-protect
----
. Kopieren Sie die Plugin-Binärdatei an einen Speicherort, der in Ihrer PFADVARIABLE definiert ist. Beispiel `/usr/bin`: Oder `/usr/local/bin` (Sie benötigen möglicherweise erhöhte Privileges):
+
[source, console]
----
cp ./tridentctl-protect /usr/local/bin/
----
. Optional können Sie die Plugin-Binärdatei an einen Speicherort in Ihrem Home-Verzeichnis kopieren. In diesem Fall wird empfohlen, sicherzustellen, dass der Speicherort Teil Ihrer PFADVARIABLE ist:
+
[source, console]
----
cp ./tridentctl-protect ~/bin/
----



NOTE: Das Kopieren des Plugins an einen Ort in Ihrer PFADVARIABLE ermöglicht es Ihnen, das Plugin durch Eingabe oder `tridentctl protect` von einem beliebigen Ort zu verwenden `tridentctl-protect`.



== Trident CLI Plug-in-Hilfe ansehen

Sie können die integrierten Plug-in-Hilfefunktionen nutzen, um detaillierte Hilfe zu den Funktionen des Plug-ins zu erhalten:

.Schritte
. Verwenden Sie die Hilfefunktion, um die Verwendungshilfe anzuzeigen:
+
[source, console]
----
tridentctl-protect help
----




== Aktivieren Sie die automatische Vervollständigung von Befehlen

Nach der Installation des Trident Protect CLI-Plugins können Sie die automatische Vervollständigung für bestimmte Befehle aktivieren.

[role="tabbed-block"]
====
.Aktivieren Sie die automatische Vervollständigung für die Bash-Shell
--
.Schritte
. Erstellen Sie das Vervollständigungsskript:
+
[source, console]
----
tridentctl-protect completion bash > tridentctl-completion.bash
----
. Erstellen Sie ein neues Verzeichnis in Ihrem Home-Verzeichnis, um das Skript zu enthalten:
+
[source, console]
----
mkdir -p ~/.bash/completions
----
. Das heruntergeladene Skript in das Verzeichnis verschieben `~/.bash/completions`:
+
[source, console]
----
mv tridentctl-completion.bash ~/.bash/completions/
----
. Fügen Sie der Datei im Home-Verzeichnis folgende Zeile hinzu `~/.bashrc`:
+
[source, console]
----
source ~/.bash/completions/tridentctl-completion.bash
----


--
.Aktivieren Sie die automatische Vervollständigung für die Z-Shell
--
.Schritte
. Erstellen Sie das Vervollständigungsskript:
+
[source, console]
----
tridentctl-protect completion zsh > tridentctl-completion.zsh
----
. Erstellen Sie ein neues Verzeichnis in Ihrem Home-Verzeichnis, um das Skript zu enthalten:
+
[source, console]
----
mkdir -p ~/.zsh/completions
----
. Das heruntergeladene Skript in das Verzeichnis verschieben `~/.zsh/completions`:
+
[source, console]
----
mv tridentctl-completion.zsh ~/.zsh/completions/
----
. Fügen Sie der Datei im Home-Verzeichnis folgende Zeile hinzu `~/.zprofile`:
+
[source, console]
----
source ~/.zsh/completions/tridentctl-completion.zsh
----


--
====
.Ergebnis
Bei Ihrer nächsten Shell-Anmeldung können Sie den Befehl Auto-Vervollständigung mit dem tridentctl-Protect-Plugin verwenden.
