---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: Passen Sie die Standardeinstellungen von Trident Protect an Ihre spezifischen Bedürfnisse an. 
---
= Trident Protect-Installation anpassen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Standardkonfiguration von Trident Protect an die spezifischen Anforderungen Ihrer Umgebung anpassen.



== Legen Sie die Ressourcenbeschränkungen für Trident Protect-Container fest.

Sie können nach der Installation von Trident Protect eine Konfigurationsdatei verwenden, um Ressourcenlimits für Trident Protect-Container festzulegen.  Durch das Festlegen von Ressourcenlimits können Sie steuern, wie viele der Clusterressourcen von Trident Protect-Operationen verbraucht werden.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `resourceLimits.yaml`.
. Füllen Sie die Datei mit Ressourcenlimitierungsoptionen für Trident Protect-Container entsprechend den Anforderungen Ihrer Umgebung.
+
Die folgende Beispielkonfigurationsdatei zeigt die verfügbaren Einstellungen und enthält die Standardwerte für jedes Ressourcenlimit:

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. Anwenden der Werte aus der `resourceLimits.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== Passen Sie die Einschränkungen des Sicherheitskontexts an

Sie können eine Konfigurationsdatei verwenden, um die OpenShift-Sicherheitskontextbeschränkungen (SCCs) für Trident Protect-Container nach der Installation von Trident Protect zu ändern. Diese Einschränkungen definieren Sicherheitsbeschränkungen für Pods in einem Red Hat OpenShift-Cluster.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `sccconfig.yaml`.
. Fügen Sie der Datei die SCC-Option hinzu und ändern Sie die Parameter entsprechend den Anforderungen Ihrer Umgebung.
+
Das folgende Beispiel zeigt die Standardwerte der Parameter für die SCC-Option:

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
In dieser Tabelle werden die Parameter für die SCC-Option beschrieben:

+
|===
| Parameter | Beschreibung | Standard 


| Erstellen | Legt fest, ob eine SCC-Ressource erstellt werden kann. Eine SCC-Ressource wird nur erstellt, wenn `scc.create` auf festgelegt ist `true` und der Helm-Installationsprozess eine OpenShift-Umgebung identifiziert. Wenn nicht unter OpenShift ausgeführt wird oder wenn `scc.create` auf eingestellt ist `false`, wird keine SCC-Ressource erstellt. | Richtig 


| Name | Gibt den Namen des SCC an. | Trident-Protect-Job 


| Priorität | Definiert die Priorität des SCC. SCCS mit höheren Prioritätswerten werden vor denen mit niedrigeren Werten bewertet. | 1 
|===
. Anwenden der Werte aus der `sccconfig.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
Dadurch werden die Standardwerte durch die in der Datei angegebenen ersetzt `sccconfig.yaml`.





== Konfigurieren Sie zusätzliche Trident Protect Helm-Chart-Einstellungen

Sie können die AutoSupport Einstellungen und die Namespace-Filterung an Ihre spezifischen Anforderungen anpassen.  In der folgenden Tabelle werden die verfügbaren Konfigurationsparameter beschrieben:

|===
| Parameter | Typ | Beschreibung 


| autoSupport.proxy | Zeichenfolge | Konfiguriert eine Proxy-URL für NetApp AutoSupport Verbindungen.  Verwenden Sie dies, um Support-Bundle-Uploads über einen Proxyserver zu leiten.  Beispiel: `http://my.proxy.url` . 


| autoSupport.unsicher | boolesch | Überspringt die TLS-Verifizierung für AutoSupport Proxy-Verbindungen, wenn diese Einstellung aktiviert ist. `true` .  Nur für unsichere Proxy-Verbindungen verwenden.  (Standard: `false` ) 


| autoSupport.enabled | boolesch | Aktiviert oder deaktiviert tägliche Trident Protect AutoSupport Bundle-Uploads. Wenn eingestellt auf `false` Tägliche Uploads sind deaktiviert, Support-Bundles können aber weiterhin manuell generiert werden. (Standard: `true` ) 


| restoreSkipNamespaceAnnotations | Zeichenfolge | Durch Kommas getrennte Liste von Namespace-Anmerkungen, die von Sicherungs- und Wiederherstellungsvorgängen ausgeschlossen werden sollen.  Ermöglicht Ihnen, Namespaces basierend auf Anmerkungen zu filtern. 


| restoreSkipNamespaceLabels | Zeichenfolge | Durch Kommas getrennte Liste von Namespace-Bezeichnungen, die von Sicherungs- und Wiederherstellungsvorgängen ausgeschlossen werden sollen.  Ermöglicht Ihnen, Namespaces basierend auf Labels zu filtern. 
|===
Sie können diese Optionen entweder mithilfe einer YAML-Konfigurationsdatei oder mithilfe von Befehlszeilenflags konfigurieren:

[role="tabbed-block"]
====
.YAML-Datei verwenden
--
.Schritte
. Erstellen Sie eine Konfigurationsdatei und benennen Sie sie `values.yaml` .
. Fügen Sie in der von Ihnen erstellten Datei die Konfigurationsoptionen hinzu, die Sie anpassen möchten.
+
[source, console]
----
autoSupport:
  enabled: false
  proxy: http://my.proxy.url
  insecure: true
restoreSkipNamespaceAnnotations: "annotation1,annotation2"
restoreSkipNamespaceLabels: "label1,label2"
----
. Nachdem Sie die `values.yaml` Datei mit den richtigen Werten, wenden Sie die Konfigurationsdatei an:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f values.yaml --reuse-values
----


--
.CLI-Flag verwenden
--
.Schritte
. Verwenden Sie den folgenden Befehl mit dem `--set` Flag zum Festlegen einzelner Parameter:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set autoSupport.enabled=false \
  --set autoSupport.proxy=http://my.proxy.url \
  --set-string restoreSkipNamespaceAnnotations="{annotation1,annotation2}" \
  --set-string restoreSkipNamespaceLabels="{label1,label2}" \
  --reuse-values
----


--
====


== Trident Protect-Pods auf bestimmte Knoten beschränken

Mithilfe der Kubernetes-Knotenauswahlbeschränkung nodeSelector können Sie anhand der Knotenbezeichnungen steuern, welche Ihrer Knoten für die Ausführung von Trident Protect-Pods geeignet sind.  Standardmäßig ist Trident Protect auf Knoten beschränkt, auf denen Linux ausgeführt wird. Sie können diese Einschränkungen je nach Ihren Bedürfnissen weiter anpassen.

.Schritte
. Erstellen Sie eine Datei mit dem Namen `nodeSelectorConfig.yaml`.
. Fügen Sie der Datei die Option nodeSelector hinzu und ändern Sie die Datei, um Knoten-Bezeichnungen hinzuzufügen oder zu ändern, um sie entsprechend den Anforderungen Ihrer Umgebung zu beschränken. Die folgende Datei enthält beispielsweise die standardmäßige OS-Beschränkung, zielt aber auch auf eine bestimmte Region und einen bestimmten App-Namen ab:
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. Anwenden der Werte aus der `nodeSelectorConfig.yaml` Datei:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
Dadurch werden die Standardbeschränkungen durch die in der Datei angegebenen ersetzt `nodeSelectorConfig.yaml`.


