---
sidebar: sidebar 
permalink: trident-protect/trident-protect-restore-settings.html 
keywords: trident, protect, restore, data, backup 
summary: Sie können die Wiederherstellungsvorgänge von Trident Protect mithilfe von Annotationen, Namespace-Einstellungen und Speicheroptionen anpassen. 
---
= Verwenden Sie die erweiterten Trident Protect-Wiederherstellungseinstellungen.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können Wiederherstellungsvorgänge mithilfe erweiterter Einstellungen wie Anmerkungen, Namespace-Einstellungen und Speicheroptionen an Ihre spezifischen Anforderungen anpassen.



== Namespace-Annotationen und -Labels bei Restore- und Failover-Vorgängen

Während von Restore- und Failover-Vorgängen werden Labels und Annotationen im Ziel-Namespace so angefertigt, dass sie den Labels und Annotationen im Quell-Namespace entsprechen. Beschriftungen oder Anmerkungen aus dem Quell-Namespace, die nicht im Ziel-Namespace vorhanden sind, werden hinzugefügt. Alle bereits vorhandenen Beschriftungen oder Anmerkungen werden überschrieben, um dem Wert aus dem Quell-Namespace zu entsprechen. Beschriftungen oder Anmerkungen, die nur im Ziel-Namespace vorhanden sind, bleiben unverändert.


NOTE: Wenn Sie Red Hat OpenShift verwenden, ist es wichtig, die entscheidende Rolle von Namespace-Annotationen in OpenShift-Umgebungen zu beachten. Namespace-Anmerkungen stellen sicher, dass wiederhergestellte Pods die entsprechenden Berechtigungen und Sicherheitskonfigurationen einhalten, die durch die OpenShift-Sicherheitskontextbeschränkungen (SCCs) definiert sind, und ohne Berechtigungsprobleme auf Volumes zugreifen können. Weitere Informationen finden Sie imlink:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["Dokumentation zu den Einschränkungen für den Sicherheitskontext von OpenShift"^] .

Sie können verhindern, dass bestimmte Annotationen im Ziel-Namespace überschrieben werden, indem Sie die Kubernetes-Umgebungsvariable vor der Wiederherstellung oder dem Failover einstellen `RESTORE_SKIP_NAMESPACE_ANNOTATIONS`. Beispiel:

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: Bei der Durchführung einer Wiederherstellungs- oder Failover-Operation werden alle in angegebenen Namespace-Annotationen und -Labels berücksichtigt. `restoreSkipNamespaceAnnotations` Und `restoreSkipNamespaceLabels` sind von der Wiederherstellungs- oder Failover-Operation ausgeschlossen. Stellen Sie sicher, dass diese Einstellungen während der ersten Helm-Installation konfiguriert werden. Weitere Informationen finden Sie unter link:../trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Konfigurieren Sie zusätzliche Trident Protect Helm-Chart-Einstellungen"].

Wenn Sie die Quellanwendung mit Helm installiert haben `--create-namespace` Flagge, besondere Behandlung wird der `name` Legende mit Beschriftung. Während des Wiederherstellungs- oder Failover-Prozesses kopiert Trident Protect diese Bezeichnung in den Ziel-Namespace, aktualisiert aber den Wert auf den Wert des Ziel-Namespace, wenn der Wert aus der Quelle mit dem Quell-Namespace übereinstimmt. Stimmt dieser Wert nicht mit dem Quell-Namespace überein, wird er unverändert in den Ziel-Namespace kopiert.



=== Beispiel

Im folgenden Beispiel wird ein Quell- und Ziel-Namespace präsentiert, der jeweils unterschiedliche Annotationen und Labels enthält. Sie können den Status des Ziel-Namespace vor und nach dem Vorgang anzeigen und sehen, wie die Annotationen und Labels im Ziel-Namespace kombiniert oder überschrieben werden.



==== Vor der Wiederherstellung oder dem Failover

Die folgende Tabelle zeigt den Status der Beispiel-Namespaces für Quelle und Ziel vor dem Restore- oder Failover-Vorgang:

[cols="1,2a,2a"]
|===
| Namespace | Anmerkungen | Etiketten 


| Namespace ns-1 (Quelle)  a| 
* Annotation.one/key: „Aktualisiertwert“
* Anmerkung.zwei/Taste: "Wahr"

 a| 
* Umgebung = Produktion
* Compliance=hipaa
* Name=ns-1




| Namespace ns-2 (Ziel)  a| 
* Anmerkung.One/key: „True“
* Anmerkung.drei/Taste: "False"

 a| 
* Rolle=Datenbank


|===


==== Nach dem Wiederherstellungsvorgang

In der folgenden Tabelle wird der Status des Beispiel-Ziel-Namespace nach der Wiederherstellung oder dem Failover-Vorgang dargestellt. Einige Schlüssel wurden hinzugefügt, einige wurden überschrieben und das Label wurde aktualisiert, `name` um dem Ziel-Namespace zu entsprechen:

[cols="1,2a,2a"]
|===
| Namespace | Anmerkungen | Etiketten 


| Namespace ns-2 (Ziel)  a| 
* Annotation.one/key: „Aktualisiertwert“
* Anmerkung.zwei/Taste: "Wahr"
* Anmerkung.drei/Taste: "False"

 a| 
* Name=ns-2
* Compliance=hipaa
* Umgebung = Produktion
* Rolle=Datenbank


|===


== Unterstützte Felder

In diesem Abschnitt werden zusätzliche Felder beschrieben, die für Wiederherstellungsvorgänge verfügbar sind.



=== Speicherklassenzuordnung

Der `spec.storageClassMapping` Attribut definiert eine Zuordnung von einer in der Quellanwendung vorhandenen Speicherklasse zu einer neuen Speicherklasse im Zielcluster.  Sie können dies verwenden, wenn Sie Anwendungen zwischen Clustern mit unterschiedlichen Speicherklassen migrieren oder wenn Sie das Speicher-Backend für BackupRestore-Vorgänge ändern.

*Beispiel:*

[source, yaml]
----
storageClassMapping:
  - destination: "destinationStorageClass1"
    source: "sourceStorageClass1"
  - destination: "destinationStorageClass2"
    source: "sourceStorageClass2"
----


== Unterstützte Anmerkungen

In diesem Abschnitt werden die unterstützten Anmerkungen zum Konfigurieren verschiedener Verhaltensweisen im System aufgelistet. Wenn eine Anmerkung nicht explizit vom Benutzer festgelegt wird, verwendet das System den Standardwert.

[cols="1,1,3,1"]
|===
| Anmerkung | Typ | Beschreibung | Standardwert 


| protect.trident.netapp.io/data-mover-timeout-sec | Zeichenfolge | Die maximal zulässige Zeit (in Sekunden), für die der Data Mover-Vorgang angehalten werden darf. | "300" 


| protect.trident.netapp.io/kopia-content-cache-size-limit-mb | Zeichenfolge | Die maximale Größenbeschränkung (in Megabyte) für den Kopia-Inhaltscache. | "1000" 


| protect.trident.netapp.io/pvc-bind-timeout-sec | Zeichenfolge | Maximale Wartezeit (in Sekunden), bis neu erstellte PersistentVolumeClaims (PVCs) die Zieladresse erreichen. `Bound` Phase vor dem Fehlschlagen der Operationen. Gilt für alle Wiederherstellungs-CR-Typen (BackupRestore, BackupInplaceRestore, SnapshotRestore, SnapshotInplaceRestore). Verwenden Sie einen höheren Wert, wenn Ihr Speichersystem oder Cluster häufig mehr Zeit benötigt. | "1200" (20 Minuten) 
|===