---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: Beginnen Sie mit der Überprüfung der Einsatzbereitschaft Ihrer Betriebsumgebung, Anwendungscluster, Anwendungen und Lizenzen. Stellen Sie sicher, dass Ihre Umgebung diese Anforderungen erfüllt, um Trident Protect bereitstellen und betreiben zu können. 
---
= Anforderungen von Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Beginnen Sie mit der Überprüfung der Einsatzbereitschaft Ihrer Betriebsumgebung, Anwendungscluster, Anwendungen und Lizenzen. Stellen Sie sicher, dass Ihre Umgebung diese Anforderungen erfüllt, um Trident Protect bereitstellen und betreiben zu können.



== Trident Protect Kubernetes-Clusterkompatibilität

Trident Protect ist mit einer Vielzahl von vollständig verwalteten und selbstverwalteten Kubernetes-Angeboten kompatibel, darunter:

* Amazon Elastic Kubernetes Service (EKS)
* Google Kubernetes Engine (GKE)
* Microsoft Azure Kubernetes Service (AKS)
* Red hat OpenShift
* SUSE Rancher
* VMware Tanzu Portfolio
* Vorgelagerte Kubernetes-Systeme


[NOTE]
====
* Trident Protect-Backups werden nur auf Linux-Rechenknoten unterstützt. Windows-Rechenknoten werden für Sicherungsvorgänge nicht unterstützt.
* Stellen Sie sicher, dass der Cluster, auf dem Sie Trident Protect installieren, mit einem laufenden Snapshot-Controller und den zugehörigen CRDs konfiguriert ist. Informationen zur Installation eines Snapshot-Controllers finden Sie unter https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["Diese Anweisungen"] .
* Stellen Sie sicher, dass mindestens eine VolumeSnapshotClass vorhanden ist. Weitere Informationen finden Sie unterlink:https://docs.netapp.com/us-en/trident_main/trident-reference/objects.html#kubernetes-volumesnapshotclass-objects["VolumeSnapshotKlasse"] .


====


== Kompatibilität des Trident Protect-Speicher-Backends

Trident Protect unterstützt die folgenden Speichersysteme:

* Amazon FSX für NetApp ONTAP
* Cloud Volumes ONTAP
* ONTAP Storage-Arrays
* Google Cloud NetApp Volumes
* Azure NetApp Dateien


Stellen Sie sicher, dass Ihr Storage-Back-End die folgenden Anforderungen erfüllt:

* Stellen Sie sicher, dass der mit dem Cluster verbundene NetApp-Speicher Trident 24.02 oder neuer verwendet (Trident 24.10 wird empfohlen).


* Stellen Sie sicher, dass Sie über ein NetApp ONTAP Storage-Back-End verfügen.
* Stellen Sie sicher, dass Sie einen Objekt-Storage-Bucket zum Speichern von Backups konfiguriert haben.
* Erstellen Sie alle Anwendungs-Namespaces, die Sie für Anwendungen oder Anwendungsdatenverwaltungsvorgänge verwenden möchten. Trident Protect erstellt diese Namespaces nicht für Sie; wenn Sie in einer benutzerdefinierten Ressource einen nicht existierenden Namespace angeben, schlägt der Vorgang fehl.




== Anforderungen für nas-Economy-Volumen

Trident Protect unterstützt Backup- und Wiederherstellungsvorgänge auf nas-economy-Volumes. Snapshots, Klone und die SnapMirror Replikation auf nas-economy-Volumes werden derzeit nicht unterstützt.  Sie müssen für jedes NAS-Economy-Volume, das Sie mit Trident Protect verwenden möchten, ein Snapshot-Verzeichnis aktivieren.

[NOTE]
====
Einige Anwendungen sind nicht mit Volumes kompatibel, die ein Snapshot-Verzeichnis verwenden. Für diese Anwendungen müssen Sie das Snapshot-Verzeichnis ausblenden, indem Sie den folgenden Befehl auf dem ONTAP-Speichersystem ausführen:

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
Sie können das Snapshot-Verzeichnis aktivieren, indem Sie den folgenden Befehl für jedes nas-Economy-Volume ausführen und durch die UUID des Volumes ersetzen `<volume-UUID>`, das Sie ändern möchten:

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: Sie können Snapshot-Verzeichnisse standardmäßig für neue Volumes aktivieren, indem Sie die Trident-Backend-Konfigurationsoption auf `true` setzen `snapshotDir`. Vorhandene Volumes werden nicht beeinträchtigt.



== Datensicherung mit KubeVirt VMs

Trident Protect bietet Funktionen zum Einfrieren und Auftauen des Dateisystems von KubeVirt-VMs während Datensicherungsvorgängen, um die Datenkonsistenz zu gewährleisten.  Die Konfigurationsmethode und das Standardverhalten für VM-Einfriervorgänge variieren je nach Trident Protect-Version. Neuere Versionen bieten eine vereinfachte Konfiguration über Helm-Chart-Parameter.


NOTE: Während der Wiederherstellung  `VirtualMachineSnapshots` für eine virtuelle Maschine (VM) erstellt wurden, werden nicht wiederhergestellt.

.Trident Protect 25.10 und neuer
[%collapsible%open]
====
Trident Protect friert KubeVirt-Dateisysteme während Datensicherungsvorgängen automatisch ein und wieder auf, um die Konsistenz zu gewährleisten.  Ab Trident Protect 25.10 können Sie dieses Verhalten mit folgender Methode deaktivieren: `vm.freeze` Parameter während der Helm-Chart-Installation. Der Parameter ist standardmäßig aktiviert.

[source, console]
----
helm install ... --set vm.freeze=false ...
----
====
.Trident Protect 24.10.1 bis 25.06
[%collapsible]
====
Ab Trident Protect 24.10.1 friert Trident Protect KubeVirt-Dateisysteme während Datensicherungsvorgängen automatisch ein und wieder auf. Optional können Sie dieses automatische Verhalten mit folgendem Befehl deaktivieren:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----
====
.Trident Protect 24.10
[%collapsible]
====
Trident Protect 24.10 gewährleistet nicht automatisch einen konsistenten Zustand der KubeVirt VM-Dateisysteme während Datensicherungsvorgängen.  Wenn Sie Ihre KubeVirt VM-Daten mit Trident Protect 24.10 schützen möchten, müssen Sie die Freeze/Unfreeze-Funktionalität für die Dateisysteme vor dem Datensicherungsvorgang manuell aktivieren. Dadurch wird sichergestellt, dass sich die Dateisysteme in einem konsistenten Zustand befinden.

Sie können Trident Protect 24.10 so konfigurieren, dass das Einfrieren und Auftauen des VM-Dateisystems während Datensicherungsvorgängen verwaltet wird, indemlink:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["Konfiguration der Virtualisierung"^] und anschließend mit folgendem Befehl:

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
====


== Anforderungen für die SnapMirror-Replizierung

Die NetApp SnapMirror Replikation ist für die Verwendung mit Trident Protect für die folgenden ONTAP Lösungen verfügbar:

* Lokale NetApp FAS, AFF und ASA Systeme. SnapMirror-Replikation mit Trident protect wird derzeit für ASA r2 Systeme nicht unterstützt.
* NetApp ONTAP Select
* NetApp Cloud Volumes ONTAP
* Amazon FSX für NetApp ONTAP




=== ONTAP-Cluster-Anforderungen für die SnapMirror-Replizierung

Stellen Sie sicher, dass Ihr ONTAP Cluster die folgenden Anforderungen erfüllt, wenn Sie SnapMirror Replizierung nutzen möchten:

* * NetApp Trident*: NetApp Trident muss sowohl auf dem Quell- als auch auf dem Ziel-Kubernetes-Cluster vorhanden sein, die ONTAP als Backend verwenden. Trident Protect unterstützt die Replikation mit der NetApp SnapMirror Technologie unter Verwendung von Speicherklassen, die von den folgenden Treibern unterstützt werden:
+
** `ontap-nas` : NFS
** `ontap-san` : iSCSI
** `ontap-san` : FC
** `ontap-san` : NVMe/TCP (erfordert mindestens ONTAP-Version 9.15.1)


* *Lizenzen*: Asynchrone Lizenzen von ONTAP SnapMirror, die das Datensicherungspaket verwenden, müssen sowohl auf den Quell- als auch auf den Ziel-ONTAP-Clustern aktiviert sein. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Übersicht über die SnapMirror Lizenzierung in ONTAP"^] .
+
Ab ONTAP 9.10.1 werden alle Lizenzen als NetApp-Lizenzdatei (NLF) bereitgestellt. Dabei handelt es sich um eine einzelne Datei, die mehrere Funktionen ermöglicht. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["In ONTAP One enthaltene Lizenzen"^] .

+

NOTE: Es wird nur der asynchrone Schutz von SnapMirror unterstützt.





=== Peering-Überlegungen für die SnapMirror-Replizierung

Stellen Sie sicher, dass Ihre Umgebung die folgenden Anforderungen erfüllt, wenn Sie Storage-Back-End-Peering verwenden möchten:

* *Cluster und SVM*: Die ONTAP Speicher-Back-Ends müssen aktiviert werden. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/peering/index.html["Übersicht über Cluster- und SVM-Peering"^] .
+

NOTE: Vergewissern Sie sich, dass die in der Replizierungsbeziehung zwischen zwei ONTAP-Clustern verwendeten SVM-Namen eindeutig sind.

* *NetApp Trident und SVM*: Die per Peering verbundenen Remote-SVMs müssen für NetApp Trident auf dem Zielcluster verfügbar sein.
* *Verwaltete Backends*: Sie müssen ONTAP -Speicher-Backends in Trident Protect hinzufügen und verwalten, um eine Replikationsbeziehung herzustellen.




=== Trident/ONTAP-Konfiguration für SnapMirror-Replikation

Trident Protect erfordert, dass Sie mindestens ein Storage-Backend konfigurieren, das die Replikation sowohl für den Quell- als auch für den Zielcluster unterstützt. Wenn Quell- und Zielcluster identisch sind, sollte die Zielanwendung für eine optimale Ausfallsicherheit ein anderes Speichersystem als die Quellanwendung verwenden.



=== Kubernetes-Clusteranforderungen für die SnapMirror -Replikation

Stellen Sie sicher, dass Ihre Kubernetes-Cluster die folgenden Anforderungen erfüllen:

* *AppVault-Zugriff*: Sowohl Quell- als auch Zielcluster müssen über Netzwerkzugriff verfügen, um für die Replikation von Anwendungsobjekten aus dem AppVault lesen und in diesen schreiben zu können.
* *Netzwerkkonnektivität*: Konfigurieren Sie Firewall-Regeln, Bucket-Berechtigungen und IP-Zulassungslisten, um die Kommunikation zwischen beiden Clustern und dem AppVault über WANs zu ermöglichen.



NOTE: Viele Unternehmensumgebungen implementieren strenge Firewall-Richtlinien für WAN-Verbindungen.  Überprüfen Sie diese Netzwerkanforderungen mit Ihrem Infrastrukturteam, bevor Sie die Replikation konfigurieren.
