---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: Sie können Trident Protect auf die neueste Version aktualisieren, um von neuen Funktionen oder Fehlerbehebungen zu profitieren. 
---
= Upgrade Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können Trident Protect auf die neueste Version aktualisieren, um von neuen Funktionen oder Fehlerbehebungen zu profitieren.

[NOTE]
====
* Beim Upgrade von Version 24.10 können Snapshots während des Upgrades fehlschlagen. Dieser Fehler verhindert jedoch nicht die Erstellung zukünftiger Snapshots, egal ob manuell oder geplant. Sollte ein Snapshot während des Upgrades fehlschlagen, können Sie manuell einen neuen Snapshot erstellen, um den Schutz Ihrer Anwendung sicherzustellen.
+
Um mögliche Fehler zu vermeiden, können Sie alle Snapshot-Zeitpläne vor dem Upgrade deaktivieren und anschließend wieder aktivieren. Dies führt jedoch dazu, dass während des Upgrade-Zeitraums alle geplanten Snapshots fehlen.

* Bei Installationen in privaten Registrys stellen Sie sicher, dass das erforderliche Helm-Chart und die Images für die Zielversion in Ihrer privaten Registry verfügbar sind, und überprüfen Sie, ob Ihre benutzerdefinierten Helm-Werte mit der neuen Chart-Version kompatibel sind. Weitere Informationen finden Sie unterlink:trident-protect-installation.html["Installieren Sie Trident Protect aus einer privaten Registry."] .


====
Um Trident Protect zu aktualisieren, führen Sie die folgenden Schritte aus.

.Schritte
. Aktualisieren Sie das Trident Helm-Repository:
+
[source, console]
----
helm repo update
----
. Rüsten Sie die Trident Protect CRDs auf:
+

NOTE: Dieser Schritt ist erforderlich, wenn Sie von einer Version vor 25.06 aktualisieren, da die CRDs jetzt im Trident Protect Helm-Chart enthalten sind.

+
.. Führen Sie diesen Befehl aus, um die Verwaltung von CRDs zu verschieben von  `trident-protect-crds` Zu  `trident-protect` :
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. Führen Sie diesen Befehl aus, um das Helm-Geheimnis für das  `trident-protect-crds` Diagramm:
+

NOTE: Deinstallieren Sie nicht die  `trident-protect-crds` Diagramm mit Helm, da dadurch Ihre CRDs und alle zugehörigen Daten entfernt werden könnten.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Upgrade Trident Protect:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2510.0 --namespace trident-protect
----
+

NOTE: Sie können den Protokollierungsgrad während des Upgrades konfigurieren, indem Sie Folgendes hinzufügen `--set logLevel=debug` zum Upgrade-Befehl. Die Standardprotokollierungsstufe ist `warn` Die Für die Fehlerbehebung wird die Verwendung von Debug-Protokollierung empfohlen, da sie dem NetApp Support hilft, Probleme zu diagnostizieren, ohne dass Änderungen am Protokollierungsgrad oder eine Reproduktion des Problems erforderlich sind.


