---
sidebar: sidebar 
permalink: trident-protect/trident-protect-generate-support-bundle.html 
keywords: trident, protect, bundle, support, netapp, custom, resource, file 
summary: 'Trident Protect ermöglicht es Administratoren, Pakete zu generieren, die für den NetApp -Support nützliche Informationen enthalten, darunter Protokolle, Metriken und Topologieinformationen über die verwalteten Cluster und Anwendungen. Wenn Sie mit dem Internet verbunden sind, können Sie Support-Bundles mithilfe einer benutzerdefinierten Ressourcendatei (CR-Datei) auf die NetApp Support Site (NSS) hochladen.' 
---
= Generieren Sie ein Trident Protect-Supportpaket
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect ermöglicht es Administratoren, Pakete zu generieren, die für den NetApp -Support nützliche Informationen enthalten, darunter Protokolle, Metriken und Topologieinformationen über die verwalteten Cluster und Anwendungen. Wenn Sie mit dem Internet verbunden sind, können Sie Support-Pakete mithilfe einer benutzerdefinierten Ressourcendatei (CR) auf die NetApp Support Site (NSS) hochladen.

[role="tabbed-block"]
====
.Erstellen Sie mithilfe eines CR-Systems ein Supportpaket
--
.Schritte
. Erstellen Sie die benutzerdefinierte Ressourcendatei (CR) und benennen Sie sie (z. B. `trident-protect-support-bundle.yaml`).
. Konfigurieren Sie die folgenden Attribute:
+
** *metadata.name*: (_required_) der Name dieser benutzerdefinierten Ressource; wählen Sie einen eindeutigen und sinnvollen Namen für Ihre Umgebung.
** *Spec.triggerType*: (_required_) legt fest, ob das Support-Bundle sofort generiert oder geplant wird. Die geplante Bundle-Generierung findet um 12:00 UHR UTC statt. Mögliche Werte:
+
*** Geplant
*** Manuell


** *Spec.UploadEnabled*: (_Optional_) steuert, ob das Supportpaket nach der Generierung auf die NetApp-Support-Website hochgeladen werden soll. Wenn nicht angegeben, wird standardmäßig auf `false`. Mögliche Werte:
+
*** Richtig
*** False (Standard)


** *Spec.dataWindowStart*: (_Optional_) Eine Datumstring im RFC 3339-Format, die das Datum und die Uhrzeit angibt, zu der das Fenster der im Support-Bundle enthaltenen Daten beginnen soll. Wenn nicht angegeben, ist die Standardeinstellung vor 24 Stunden. Das früheste Fensterdatum, das Sie angeben können, ist vor 7 Tagen.
+
Beispiel YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AutoSupportBundle
metadata:
  name: trident-protect-support-bundle
spec:
  triggerType: Manual
  uploadEnabled: true
  dataWindowStart: 2024-05-05T12:30:00Z
----


. Nachdem Sie die `trident-protect-support-bundle.yaml` Datei mit den richtigen Werten, wenden Sie den CR an:
+
[source, console]
----
kubectl apply -f trident-protect-support-bundle.yaml -n trident-protect
----


--
.Erstellen Sie ein Support-Bundle mithilfe der CLI
--
.Schritte
. Erstellen Sie das Supportpaket, und ersetzen Sie Werte in Klammern durch Informationen aus Ihrer Umgebung. Der `trigger-type` legt fest, ob das Bündel sofort erstellt wird oder ob die Erstellungszeit vom Zeitplan vorgegeben ist, und kann oder `Scheduled` sein `Manual`. Die Standardeinstellung ist `Manual`.
+
Beispiel:

+
[source, console]
----
tridentctl-protect create autosupportbundle <my-bundle-name> --trigger-type <trigger-type> -n trident-protect
----


--
====


== Überwachen und Abrufen des Support-Pakets

Nachdem Sie mit einer der beiden Methoden ein Support-Paket erstellt haben, können Sie den Generierungsfortschritt überwachen und es auf Ihr lokales System abrufen.

.Schritte
. Warten Sie auf die `status.generationState` erreichen `Completed` Zustand.  Sie können den Generierungsfortschritt mit dem folgenden Befehl überwachen:
+
[source, console]
----
kubectl get autosupportbundle trident-protect-support-bundle -n trident-protect
----
. Rufen Sie das Support-Paket auf Ihr lokales System ab.  Holen Sie sich den Kopierbefehl aus dem vollständigen AutoSupport Paket:
+
[source, console]
----
kubectl describe autosupportbundle trident-protect-support-bundle -n trident-protect
----
+
Finden Sie die `kubectl cp` Befehl aus der Ausgabe und führen Sie ihn aus, wobei Sie das Zielargument durch Ihr bevorzugtes lokales Verzeichnis ersetzen.


